### ISSUE TITLE
[models] glTF doesn't support scaling

### ISSUE THREAD

**Issue by electronstudio** [raysan5/raylib#1024]
Scale a cube in Blender:

![image](https://user-images.githubusercontent.com/7192452/69494446-9f229500-0eb3-11ea-9a83-1de4bf32290d.png)

Export as glTF: 
[scaledcube.gltf.zip](https://github.com/raysan5/raylib/files/3883514/scaledcube.gltf.zip)

Load into models_loading.c example:
```
INFO: [/Users/richard/scaledcube.gltf][gltf] Model meshes/materials: 1/1
INFO: [VAO ID 2] Mesh uploaded successfully to VRAM (GPU)
```

Does not apply scaling:

![image](https://user-images.githubusercontent.com/7192452/69494485-3556bb00-0eb4-11ea-9745-fe5e2c737610.png)

**Comment by electronstudio** [comment]
@Gamerfiend

**Comment by Gamerfiend** [comment]
Hey sorry I just noticed this! @electronstudio Please make sure you have applied all transforms to the model. I've ran into this same issue, and applying transforms before exporting can solve this issue.

**Comment by raysan5** [comment]
@Gamerfiend thanks for the proposed solution.

**Comment by Shr1ftyy** [comment]
**Note to others who may come across this issue.**

I just stumbled upon this issue after my mouse ray mesh collisions weren't working as intended. It turned out, that the ray checks collisions with the original GLTF model, but not the scaled model which is drawn (this also includes the fact that the transform does not change when drawing the model, as well as the rotation), hence the model is always at the center of the world coordinates. to compensate for this, ensure you update the model's transform matrices (example below written in odin).
```
            transform := _unit^.model.transform
            transform[0][0] *= _unit^.modelScale
            transform[1][1] *= _unit^.modelScale
            transform[2][2] *= _unit^.modelScale

            transform[0][3] = _unit^.position.x
            transform[1][3] = _unit^.position.y
            transform[2][3] = _unit^.position.z

```
Below is an image which may help readers identify what they need to modify:
![image](https://github.com/raysan5/raylib/assets/49330057/88d5c267-5952-4349-892d-60d7a463b8ac)

**Comment by Shr1ftyy** [comment]
Also, just wanted to say...

I LOVE THIS LIB SO MUCH OMG <3 <3 <3 GREAT WORK @raysan5

**Comment by keithstellyes** [comment]
I think I ran into this same issue, https://www.reddit.com/r/raylib/comments/175rn75/gltf_models_created_in_blender_have_weird/, but I am totally confused how I'm supposed to apply transforms before exporting with Blender?

Also, other 3D viewers are able to to handle the scaling just fine
