### ISSUE TITLE
[textures] Color faded issue with RenderTexture

### ISSUE THREAD

**Issue by gezzuzz** [raysan5/raylib#1121]
I draw 2 circles... one with TextureMode one without.. i expected these to give me the same result. 
But when i use Fade they act differently. What am i not understanding here?

Thank you in advance and thank you for creating raylib. 
I hope when i get more experience with it I will because to contribute to the project.

<img width="312" alt="circles" src="https://user-images.githubusercontent.com/46981052/76125209-f14e7880-5fc1-11ea-8424-73eaeb687fe7.png">

```
            Vector2 origin = (Vector2){500,500};
            DrawCircleV(origin,100,BLACK);
            for(int i=80;i<=100;i+=5)
                DrawCircleV(origin,i,Fade(RED,.3));
            
            RenderTexture2D temp = LoadRenderTexture(200, 200);
            BeginTextureMode(temp);
            origin = (Vector2){100,100};
            DrawCircleV(origin,100,BLACK);
            for(int i=80;i<=100;i+=5)
                DrawCircleV(origin,i,Fade(RED,.3));
            EndTextureMode();
            DrawTexture(temp.texture,620,400,WHITE);
```

**Comment by raysan5** [comment]
@gezzuzz Good catch! :D Actually this issue is a tricky one. 

Short answer: main framebuffer is RGB by default while `RenderTexture` framebuffer is RBGA by default. This conditions how alpha is blended with previous colors in the framebuffer.

Related function:
```c
[textures.c]
// Load texture for rendering (framebuffer)
// NOTE: Render texture is loaded by default with RGBA color attachment and depth RenderBuffer
RenderTexture2D LoadRenderTexture(int width, int height)
{
    RenderTexture2D target = rlLoadRenderTexture(width, height, UNCOMPRESSED_R8G8B8A8, 24, false);

    return target;
}
```
You can just change `UNCOMPRESSED_R8G8B8A8` to `UNCOMPRESSED_R8G8B8`. It will work for your case but probably you will have problems for other usage cases... it's a tricky issue.
