### ISSUE TITLE
[models] LoadModel fails to load .mtl and .png files that use a relative path.

### ISSUE THREAD

**Issue by ChrisDill** [raysan5/raylib#1134]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When loading a model that has a relative path for the material(.mtl) file it fails to find it and uses the default material instead.

I was trying to load a rock object model in "resources/objects/rock/". This folder contains:
- rock.obj
- rock.mtl
- rock.png

It finds and load rock.obj but fails to find rock.mtl and rock.png which are in the same folder. I looked at the files and saw they were using relative paths. I got it to load by changing the paths to include "resources/objects/rock" however this will break if I ever move or rename those folders.

Here is where it tries to load the .mtl file in tiny_obj_loader_c 
https://github.com/raysan5/raylib/blob/6f41b9594a3f107ad7332af197cdd3565b7d33fe/src/external/tinyobj_loader_c.h#L1320. 

I noticed that it was calling fopen with rock.mtl which fails. This does not seem intentional and I think it should be changed so it looks relative to the .obj file. I think similar changes will need to be made for loading rock.png too although I think loading for that happens in models.c.

Closest issue I found to this is #788. Some of the changes to make might be to models.c not just tiny_obj_loader so that is why I opened a new issue here.

Here is a zip of the rock folder I was loading from.
[rock.zip](https://github.com/raysan5/raylib/files/4343041/rock.zip)

Platform: Desktop
Operating System: Arch Linux
OpenGL Version: 4.5 (Core Profile) Mesa 19.3.4
GPU details: AMD RX 580 Series 8GB

### Issue Screenshot

Model loads using default material.
![image](https://user-images.githubusercontent.com/7503113/76849412-48174600-683d-11ea-889e-16fef39dfc2e.png)

Works when I changed the .mtl and .png paths to include "resources/objects/rock".
![image](https://user-images.githubusercontent.com/7503113/76849451-55cccb80-683d-11ea-85df-8a9a46c14880.png)

### Code Example
```c
Model asteroid = LoadModel("resources/objects/rock/rock.obj");
```

**Comment by raysan5** [comment]
Just verified this issue and it seems to be internal to `tinyobjloader-c`.

 1. `tinyobj_parse_obj()` parses obj text data (loaded from `resources/model/rock.obj` into a buffer) to find references to materials (`mtllib rock.mtl`), data comes from a buffer, so this function has no filename awareness.
 2. Once material is found, it tries to load it with `tinyobj_parse_and_index_mtl_file("rock.mtl")`, looking for provided filename.
 3. But filename reference does not consider the base path for the original obj file and it tries to load it from the current working directory.
 4. It fails on finding the file.

Possible solutions:

 1. Use `chdir()` function to move to `rock.obj` base path before loading... we need to return to original working directory after that!
 2. Modify `tinyobjloader-c` to support a relative path... or implement a custom obj loader on raylib, like the one we had before switching to `tinyobjloader-c` library...

I tried Solution 1. but `chdir()` is platform dependant and requires some ugly code... but it works. I prefere Solution 2. but it requires some rewrite.

For the moment I'll keep it as it is, letting the user load the material manually instead of trying to find it automatically...

**Comment by ChrisDill** [comment]
That sounds similar to what I found. I agree that solution 2 sounds better. I can open a issue in tinyobjloader-c and link to this one if that will help.

How do I load the material manually without it first trying to load the .mtl file or is that not possible?

**Comment by raysan5** [comment]
Finally implemented Solution 1, at least as temporal solution... but really, I don't like it at all...

After lot of thinking, I'm afraid there is not a simple solution for this, `tinyobjloader-c` should probably redesigned to just return material filenames and let the user manage the loading... that would also avoid I/O accesses inside `tinyobjloader-c`.

@ChrisDill Feel free to open an issue on `tinyobjloader-c` and link with this one.

**Comment by raysan5** [comment]
Closing this issue... despite I really don't like the implemented solution...

**Comment by chriscamacho** [comment]
much as you don't like the solution which is sub optimal, unless you you PR upstream or fork you're not going to get a good solution... strongly recommend where you can to get some relationship with the upstream dependencies, make them aware that their code is valued and used and you wish to help improve it.... (then we all benefit)
