### ISSUE TITLE
[core] Add Load*Data() functions for virtual asset loading

### ISSUE THREAD

**Issue by RobLoach** [raysan5/raylib#1165]
### Issue description

Add `Load*Data(data, filename)` functions to allow loading assets from raw data. This would allow for the implementation of some virtual file systems.

- `LoadTextureData()`
- `LoadImageData()`
- `LoadFontData()`
- `LoadModelData()`
- `LoadSoundData()`
- `LoadMusicData()`
- etc

### Code Example

``` c
unsigned char* file = LoadFileData("cat.png", bytesRead);
Texture cat = LoadTextureData(file, "cat.png");
```

**Comment by danimartin82** [comment]
Hi, just wondering....these functions are already available. Is it what you want?

```
RLAPI void SaveFileData(const char *fileName, void *data, unsigned int bytesToWrite); // Save data to file from byte array (write)
RLAPI char *LoadFileText(const char *fileName);                   // Load text data from file (read), returns a '\0' terminated string

```

**Comment by RobLoach** [comment]
You can call `LoadFileData()`, but you're unable to use that data to load a Sound object, or Model. This is about allowing using the data across objects in raylib.

**Comment by raysan5** [comment]
@RobLoach This is a functionality that was added and removed at some point in the past. 

Due to the nature of raylib, data structures (`Image`, `Font`, `Mesh`, `Wave`...) can be directly accessed and filled by the users:
```c
Image image = { 
    .data = myImageData,
    .width = 256,
    .height = 256,
    .format = UNCOMPRESSED_GRAYSCALE,
    .mipmaps = 1
};
```
There is still one remnant functions (that I will probably remove):
```c
Image LoadImagePro(void *data, int width, int height, int format);
```
  > This would allow for the implementation of some virtual file systems.

Actually, VFS can be supported through the `LoadFileData()`/`SaveFileData()` mechanism. Those functions can map directly to a VFS, after all, you need an ID to reference data in the file system; that ID could be directly the file name.

This is also related to the upcoming [`rres`](https://github.com/raysan5/rres) file format support, that also comes with its [custom data loading](https://github.com/raysan5/rres/blob/master/src/rres-raylib.h) functionality.

**Comment by RobLoach** [comment]
That's! I'll check out rres ☺️
