### ISSUE TITLE
[module] Cannot run compiled examples

### ISSUE THREAD

**Issue by ramiil** [raysan5/raylib#1173]
### Issue description

Compilation is ok, but I cannot run compiled files. Error: Entry point for procedure "timeEndPeriod" not found at DLL kernel32.dll

### Environment

Windows 7 x64, raylib_installer_v300.tcc

### Issue Screenshot
![изображение](https://user-images.githubusercontent.com/5654231/78455433-37c9ec80-76c0-11ea-898e-81c22abbf2c6.png)

### Code Example

All examples failed to run.

**Comment by raysan5** [comment]
`timeEndPeriod()` function is contained in `WinMM` library but early versions of Windows 7 do not include this library. To avoid using `WinMM` you should edit `raylib/src/config.h` and change it to use `SUPPORT_BUSY_WAIT_LOOP` instead of `SUPPORT_HALFBUSY_WAIT_LOOP`:
```c
// Use busy wait loop for timing sync, if not defined, a high-resolution timer is setup and used
#define SUPPORT_BUSY_WAIT_LOOP      1
// Use a half-busy wait loop, in this case frame sleeps for some time and runs a busy-wait-loop at the end
//#define SUPPORT_HALFBUSY_WAIT_LOOP
```
Now you must recompile raylib library, it can be done with Notepad++ script `raylib_source_compile`. Recompile your example again and it should work.

Please, feel free to reopen the issue if it still fails.
