### ISSUE TITLE
[texture] some ImageDraw routines not respecting alpha

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1196]
Please, before submitting a new issue verify and check:

 - [ x ] I tested it on latest raylib version from master branch
 - [ x ] I checked there is no similar issue already reported
 - [ x ] My code has no errors or misuse of raylib

### Issue description

Its possible to cut out a mask from a BLACK texture by drawing on the image with the BLANK colour, this works with anything that ends up drawing with ImageDrawPixel but NOT any routine relying on ImageDrawRectangleRec

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*
Linux 64bit, GL 4.6 (Core Profile), Intel(R) UHD Graphics (CML GT2)

### Issue Screenshot
wanna see a completely black screen ? :)

### Code Example

	img = GenImageColor(256,256,BLACK);
	for (int y = 0; y<256; y+=8) {
		for (int x = 0; x<256; x+=8) {
			//for (float r=1; r<4; r+=0.5) {
			//	ImageDrawCircle(&img, x+4, y+4, r, BLANK);
			//}
			ImageDrawRectangle(&img, x+4, y+4, 4, 4, BLANK);
		}		
	}
	Texture grid = LoadTextureFromImage(img);
	UnloadImage(img);

draw grid texture over something you can see, with circles you can see something through the grid texture with rectangle you can't

**Comment by raysan5** [comment]
Actually, this is a tricky issue... the proposed behaviour was the original one but it has been reviewed several times...

Most `ImageDraw*()` functions rely on `ImageDraw()`, that's a `src->dst` data blitting function. I reviewed that function in several ocasions and ther is still way for improvement, it's not as efficient as should could be... the current `ImageDrawPixel()` is probably a reference to follow.

Problems with color blending: it depends on the user needs. In the specific case of this issue, what happens if original image where we want to draw the the rectangle has already some alpha amount and the color is not BLANK but only half-BLANK? Alpha won't be blended (as most users expect?).

I'm afraid some blending configuration function for image could be required and that takes us down to the rabbit hole of software rendering...

**Comment by chriscamacho** [comment]
The only practical solution I can think of is to add a blend mode

if the resultant image is extracted from a render texture, then the speed and convenience of OpenGL can be leveraged.  see https://www.khronos.org/opengl/wiki/GLAPI/glBlendFuncSeparate

GLES2.0 does support BlendEquationSeparate (at least according to the spec)

I would attempt a PR but every time I end up doing anything with blending modes I end up bashing my head against a wall !!

**Comment by raysan5** [comment]
Keep in mind that `Image*()` are purely software rendering, no OpenGL involved, no hardware accelerated, everything happens in CPU side.

Supporting multiple [blending modes](https://en.wikipedia.org/wiki/Alpha_compositing#Alpha_blending) is the solution but blending maths should be done manually pixel by pixel and considering the multiple image.format supported. It would be like implementing OpenGL graphic functionality in software... it could take some work...

**Comment by chriscamacho** [comment]
well it does now, but why not use the GPU ? it would be faster and all the blending is already there ready to be used...

**Comment by raysan5** [comment]
@chriscamacho because that's what `Texture` drawing functions do, `Image` equivalents are only the CPU version (no hardware accelerated) for very specific use cases (i.e. trying to use raylib in a custom embedded system with no GPU).

**Comment by chriscamacho** [comment]
DOH I keep forgetting about them....
