### ISSUE TITLE
[model] GenCubicMap front and back faces have wrong normals

### ISSUE THREAD

**Issue by GoldenThumbs** [raysan5/raylib#1243]
I was trying to use the basic lighting shader provided in the examples in the first person maze example and I notices the front and back faces of the maze were incorrect.

I'm on Windows 10 and everything was compiled with VS 2019. OpenGL version 3.3.

![image](https://user-images.githubusercontent.com/24837412/81519608-7e39e900-9307-11ea-9a07-70f483c3282f.png)

Solution is fairly simple, just switch the signs on `n5` and `n6` at lines `2021 `and `2022 `in [models.c](https://github.com/raysan5/raylib/blob/master/src/models.c)
or change the normal vector used in lines `2126` through `2131` to n5 and n6 at lines `2158` through `2163`

**Comment by raysan5** [comment]
Hi @GoldenThumbs thanks for the review on PR https://github.com/raysan5/raylib/pull/1244

I did a quick test to verify it works and it seems there are still issues:

![screenshot000](https://user-images.githubusercontent.com/5766837/81547826-add70880-937c-11ea-8ae9-2c784a90af9e.png)
![screenshot001](https://user-images.githubusercontent.com/5766837/81547836-b0d1f900-937c-11ea-8e78-f2cc82d1024b.png)

As you can see, outer walls are not correctly light.

Here the example for testing: [models_cubicmap_lighting.zip](https://github.com/raysan5/raylib/files/4608823/models_cubicmap_lighting.zip)

**Comment by raysan5** [comment]
After some tests with a single light and reviewing the lighting shader:

![screenshot000](https://user-images.githubusercontent.com/5766837/81574362-fd7dfa00-93a5-11ea-9fed-6fbcd7a88c83.png)
![screenshot001](https://user-images.githubusercontent.com/5766837/81574391-08d12580-93a6-11ea-8067-01a5a6bed5a7.png)

Conclusion is that it's the expected behaviour. Light angle of incidence with the opposite walls is direct so the walls get the full light intensity, attenuation function should be more aggressive to eventually reduce that light. The confusing point here is that the full wall gets illuminated (it would be expected that around the corner there was no light in the wall) but this is also expected because we are not considering any shadows mechanism.
