### ISSUE TITLE
[core] ToggleFullscreen() could change screen width/height

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1294]
When calling `ToggleFullscreen()`, it could (wrongly) change requested `screenWidth` or `screenHeight`.

Internal call sequence go as follow: 
```c
ToggleFullScreen() 
    glfwSetWindowMonitor()      // This function calculate the closest monitor-supported width x height
        WindowSizeCallback()    // This function is called with a wrong width or height
            SetupViewport()     // Setup viewport and projection matrix 
```

Maybe issue is GLFW side and `glfwSetWindowMonitor()` shouldn't call `WindowSizeCallback()`?

EDIT 1: One possible solution is just commenting `WindowSizeCallback()` internals.

EDIT 2: `InitGraphicsDevice()` also looks for closest monitor supported `width x height` and modifies it.

**Comment by funcelot** [comment]
ok, i need to test https://github.com/raysan5/raylib/pull/1512 with this one, sadly enougth, i can test on windows only

**Comment by raysan5** [comment]
@object71 Tested after latest PR and it still fails, GLFW picks a valid resolution for the monitor and scales to it ignoring requested width/height... :(

**Comment by object71** [comment]
@raysan5 Sorry, it was working when I submitted it but I haven't tested it in some time, I will take another look.

**Comment by object71** [comment]
@raysan5 I've explored the problem some more. What you probably want to achieve is already done in an example "**core_window_letterbox.c**" .

The main points are that:

- When in fullscreen mode you can only use resolution formats that the monitor supports.
- When toggling to fullscreen mode you would get the resolution closest to the window resolution you specified.
- You can't control that behavior

My proposal:

- **Always set to the highest possible resolution for the current monitor**. This is because you get problems if you scale the whole fullscreen to a lower resolution - all other windows get scaled down which is anoying and if you try to switch with alt+tab everything is in the resolution of your game.
- Leave it to library user to implement it with a render target texture if they want to achieve a more pixelated low-res result.

I will prepare a pull request for that and link it and you can take a look and decide.

**Comment by raysan5** [comment]
@object71 Excuse for the late response! You are right with the main points but I don't think setting the higher possible resolution for fullscreen is the right approach, for example, a game that runs at HD (1280x720) will turn into 4K in a monitor supporting it with a consequent frame drop and possible issues with physics and logic (designed for 1280x720 resolution).

Fullscreen must use the closest resolution to user request, actually, for most standard resolutions, current implementation works ok, the only problem comes when using no-standard resolutions...

**Comment by object71** [comment]
@raysan5 Well, okay, tomàto-tòmato. People could still set a higher resolution even for fullscreen using SetWindowSize. Maybe we need to also expose somehow the available monitor video modes
