### ISSUE TITLE
[raudio] LoadSound() doesn't rely LoadFileData()

### ISSUE THREAD

**Issue by TSnake41** [raysan5/raylib#1312]
raylib commit : https://github.com/raysan5/raylib/commit/bdd253a66ad4944b07d29a8533b795fd214c33fd

`LoadSound` doesn't use `LoadFileData` as expected with raylib v3.0.0 (which expects to use buffers instead of file I/O).

LoadWAV, LoadOGG, LoadMP3 and LoadFLAC should use buffers (with `LoadFileData`) with appropriate functions (like stb_vorbis_open_memory and drwav_open_memory_and_read_pcm_frames_s16)

https://github.com/raysan5/raylib/blob/master/src/raudio.c#L1879
https://github.com/raysan5/raylib/blob/master/src/raudio.c#L1947
https://github.com/raysan5/raylib/blob/master/src/raudio.c#L1984
https://github.com/raysan5/raylib/blob/master/src/raudio.c#L2009

**Comment by raysan5** [comment]
Wow! How could I miss that... very weird... if I left it that way there was probably some reason to do that...

I'll review it again...

**Comment by raysan5** [comment]
`LoadSound()` now uses `LoadFileData()` but `LoadMusicStream()` still rely on files. 

Music is streamed from the file in chunks, moving to a memory approximation would imply loading the full file to memory and decompress chunks for streaming. When using `MP3/OGG` it could be fine because files are relatively small (3MB-10MB) but `WAV/FLAC` would require a big chunk of memory to preload them (>100MB).

What is the best option here? Maybe an additional API call `LoadMusicFromMemory()`?

**Comment by raysan5** [comment]
`LoadMusicStream(const char *fileName);` uses internally the following file-access calls:
```
format        file-access-call                       memory-access-call
---------------------------------------------------------------------------------
.wav      -> drwav_init_file()                  ---> drwav_init_memory()
.ogg      -> stb_vorbis_open_filename()         ---> stb_vorbis_open_memory()
.flac     -> drflac_open_file()                 ---> drflac_open_memory()
.mp3      -> drmp3_init_file()                  ---> drmp3_open_memory()
.xm       -> jar_xm_create_context_from_file()  ---> jar_xm_create_context_safe()
.mod      -> jar_mod_load_file()                ---> <no alternative>
```

**Comment by raysan5** [comment]
This issue is actually solved, stream system could require some improvements in the future.
