### ISSUE TITLE
[examples] Model picking

### ISSUE THREAD

**Issue by kororro** [raysan5/raylib#1313]
In  models_mesh_picking.c
when I change tower model's position ie
Vector3 towerPos = { -10.0f, 0.0f, 0.0f };                    // Set model position

picking doesnt work right anymore. 
GetCollisionRayModel() function needs models to be in origin?

**Comment by raysan5** [comment]
@kororro It happens because model vertex position transformation happens in the drawing but it's not directly assigned to the model. To attach the transformation to the model to be considered by `GetCollisionRayModel()`, just do at init: 
```c
model.transform = MatrixTranslate(-10.0f, 0.0f, 0.0f);
Vector3 towerPos = { 0.0f, 0.0f, 0.0f };
```
That way, model translation is defined inside model and considered on mesh picking.

**Comment by JohnLudlow** [comment]
Hi @raysan5 I just hit the same problem and it took me a while to figure out. Could the sample be updated to show that?
