### ISSUE TITLE
[rlgl] rlEnd, rlPopMatrix, and DEFAULT_BATCH_BUFFER_ELEMENTS

### ISSUE THREAD

**Issue by seanpringle** [raysan5/raylib#1320]
Why is it necessary for `rlEnd` to leave the matrix stack into an unbalanced state when forcing an `rlglDraw`?
https://github.com/raysan5/raylib/blob/14d37464adecd4d29504ff9f11702a58df2de7da/src/rlgl.h#L1203

I see the nearby comment:
https://github.com/raysan5/raylib/blob/14d37464adecd4d29504ff9f11702a58df2de7da/src/rlgl.h#L1200

Should the stack be restored afterwards so that callers that nest `rlPushMatrix` and `rlPopMatrix` can operate reliably?

Since `rlBegin` can also force an `rlglDraw` should it also be unwinding/winding the matrix stack?

I'm trying to track down a bug in my code that manifests like this:

- many calls to `DrawCube` which exceeds `DEFAULT_BATCH_BUFFER_ELEMENTS` and so `rlEnd` forces a batch draw.
- subsequent direct calls to `rlDrawMesh` which relies on `RLGL.State.modelview` containing the camera view matrix, but it is not reliable after the first forced batch draw.

I can work around the problem by doing one of:

- manually restoring `RLGL.State.modelview` to a clean `BeginMode3D` state for the camera, or
- commenting out the `rlPopMatrix` loop in `rlEnd`

Hence, these matrix stack theory questions! I would prefer to work with the batching system rather than against it :-)

**Comment by raysan5** [comment]
@seanpringle If I remember correctly, the origin of this issue is https://github.com/raysan5/raylib/issues/901.

It's been some time since I wrote that code so I can miss some detail on my explanation but when `rlEnd()` requires to force a `rlglDraw()` and that happens between rlPushMatrix()/rlPopMatrix(), we reset all matrix transformations for the following calls... but actually you are right with your issue, it breaks the following calls... mmmh...

I'm afraid I don't remember right now why that loop needed to be there... I'm sure there was some side-case that required it...

**Comment by raysan5** [comment]
No plans to review this implementation for the moment.
