### ISSUE TITLE
[Core] GetMonitorWidth() and GetMonitorHeight() returns wrong value when in fullscreen

### ISSUE THREAD

**Issue by fossegutten** [raysan5/raylib#1322]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description
GetMonitorWidth() and GetMonitorHeight() returns wrong value when in fullscreen. When in window mode, they return the correct value!
I want to set the screen size to be the same as the actual monitor size, when in fullscreen. To do this I need the monitor size.
### Environment
Surface Go 2, Windows 10, open GL 330. Integrated intel GPU.

### Code Example

```
            ToggleFullscreen();
            if (IsWindowFullscreen()) { 
                // SetWindowSize(GetMonitorHeight(0), GetMonitorHeight(0)); // returns wrong values
                SetWindowSize(1920, 1200); // hardcoded values work fine!
            } 
            else {
                SetWindowSize(640, 360);
            }
```

**Comment by raysan5** [comment]
@fossegutten What are the values returned? I'm afraid it could be the expected behaviour, when switching to fullscreen monitor resolution is adjusted to fullscreen requested resolution (probably the one returned).

**Comment by fossegutten** [comment]
@raysan5 the values seem to change, depending on the previous window size.
I get wrong values when calling the same two functions before the InitWindow() function too.

Not sure if it is relevant, but I have commented out this in the config `//#define SUPPORT_HIGH_DPI            1`

**Comment by raysan5** [comment]
@fossegutten Those functions can't be called before `InitWindow()` because they actually depend on GLFW initialization. Also returned values when toggling fullscreen are constrained to the closer monitor supported fullscreeen resolution, for example asking for a 800x450 fullscreen will probably return a 800x600 fullscreen because it's the closed fullscreen mode supported by the monitor.

Actually, displaySize is already stored internally but fullscreen monitor mode selected also depends on the screen resolution desired. Easy solution: use always a standard screen/monitor resolution, for example 1280x720 or 1920x1080.

**Comment by fossegutten** [comment]
Oh, right. That is probably what happened! Seems like the values returned was constrained to my monitors supported fullscreen resolutions.
Sorry for reporting this, I thought it was a bug. This is complicated stuff to me!

**Comment by raysan5** [comment]
@fossegutten No worries, it's also complicate stuff for me! I've been trying to find the better solution for fullscreen mode for long time but there are lots of side cases, especially when dealing with small/non-standard resolutions... also, every platform deals with that in a different way... Here two open issues related: https://github.com/raysan5/raylib/issues/1294, https://github.com/raysan5/raylib/issues/1241
