### ISSUE TITLE
[rlgl] Multiple sampler2D per shader in 2d

### ISSUE THREAD

**Issue by atomicstan** [raysan5/raylib#1333]
I wanted to use multiple sampler2D within one fragment shader for 2d. I struggled a bit but then I found: #594 and I realized it's probably not even possible in 2d mode, so the only way to handle that is in 3d mode (as described in the last comment in #594). I managed to do that, but further changes seem to require creating my own mesh (to have plane aligned with XY, the default is XZ), allocating native memory in C# (I use https://github.com/ChrisDill/Raylib-cs) , so everything became way more complex than I originally anticipated.

I wonder if you plan to simplify this for 2d since this makes raylib quite cumbersome for anyone who wants to play with some 2d effects per sprite.

Anyway thank you for such a great library and the effort you spend on it.

**Comment by raysan5** [comment]
Hi @prokopst! I think changing the current batch system to allow multiple sampler2D will add an unnecessary level of complexity and overload for most use cases but I could consider providing some ready-to-use function to avoid this cubersome process.

For example, `rlgl` defines internally a `GenDrawQuad()` used on some shader-based texture generation operation (`GenTextureBRDF()`). Actually, that API approach is being redesigned (#721), I can try to accomodate some function just for that use case.

**Comment by prokopst** [comment]
@raysan5 thank you for your thoughts.

While this would definitely help, I wonder if there is a better direction - for example making 2d API more powerful, like provide functionality which would introduce sprites which would also understand the concept of materials. Or to expose materials in something like `BeginMaterialMode`, which would apply the material on everything between `BeginMaterialMode`/`BeginMaterialMode`?

Note my knowledge of the library internals is limited so anything above can be pure 💩 since it wouldn't necessarily address the problem of the current batching mechanism. But I personally think that a bit more powerful functionality for 2d could be another selling point. And as long as you help to shape the new API and give a few hints I guess that someone like me can try to implement that.

**Comment by raysan5** [comment]
@atomicstan Please, could you give it a test to this addition?

**Comment by atomicstan** [comment]
Oh well, I'm sorry, I assumed it's not going to happen in foreseen future and I later abandoned and deleted (?) my little 2d project completely. 😢 Is anyone from the community available to play with that?

**Comment by raysan5** [comment]
@atomicstan ok, no worries. I already asked the community to test it.

**Comment by raysan5** [comment]
I'm not fully convinced with current solution but it works.
