### ISSUE TITLE
[shaders] Standard shader artifacts on web

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#139]
Weird artifacts with lighting on platform web... it could related to some `clamp()` on shader or maybe depth buffer being only 16 bit? Need some testing...

![image](https://cloud.githubusercontent.com/assets/5766837/17029903/7876d41a-4f6d-11e6-88f9-8c2aca26b4f9.png)

![image](https://cloud.githubusercontent.com/assets/5766837/17029897/703a4656-4f6d-11e6-8472-3eaba96f84df.png)

Running example can be checked [here](http://www.raylib.com/examples_web/exmain.html?name=shaders_standard_lighting).

**Comment by victorfisac** [comment]
I have just opened the example in a MAC using Chrome and it displays fine like on desktop platform :O!

MAC info:
OSX The Captain (version 10.11.6)
iMac (Retina 5K)
CPU: 3,3 GHz Intel Core i5
RAM: 8 GB 1600 MHz DDR3
GPU: AMD Radeon R9 M290 2048 MB

Chrome version: Versión 53.0.2785.143 (64-bit)

@raysan5 Could it be because it uses an AMD GPU and the problem is with Nvidia GPUs?

<img width="1728" alt="standard_lighting_mac_chrome" src="https://cloud.githubusercontent.com/assets/10688349/19230373/7a02aa9c-8ed4-11e6-9347-2ad8ae97bd54.png">

**Comment by raysan5** [comment]
Hi @victorfisac, thank you very much for the feedback!

I got the same issue with Intel GPU (didn't expect to work better than nvidia... :P), I think some of the maths should be simplified...

**Comment by victorfisac** [comment]
@raysan5 tested adding a abs() to every 'f' parameter in pow(f, e) in shader_standard.h and it fixes the artifacts issue :D! I let you apply the changes by yourself because I don't have my fork up to date. Congratulations!

**Comment by raysan5** [comment]
Hi @victorfisac, I've just been working in this issue. Using `abs(f)` didn't solve the issue for me... After some investigation I find the problem. Specular value was not obtained correctly from texture; the following line needed to be changed:
```c
if (useSpecular == 1) spec *= normalize(texture2D(texture2, fragTexCoord).r);
```
by this:
```c
if (useSpecular == 1) spec = texture2D(texture2, fragTexCoord).r;
```
The reason is because texture2D already returns values normalized in range 0..1, that's exactly what we need. If you check specularity now, it has more sense following texture values (i.e. skulls have some specular level but not the skin).

Updated on commit https://github.com/raysan5/raylib/commit/97e3277d58060df96cd002b1377a51ca4adcbb9e

Still thinking this shader could be optimized... ;)
