### ISSUE TITLE
APPCRASH error

### ISSUE THREAD

**Issue by EdwardAngeles** [raysan5/raylib#154]
Hi. I'm using raylib for the first time. I open one of the examples and when I try to compile and execute it, it gives me this an APPCRASH error.

![0](https://cloud.githubusercontent.com/assets/6760623/17075333/7f4fb4b8-505e-11e6-9230-a6db44ed69af.png)

I'm on Windows 7 Ultimate 64bit. Graphics: Mobile Intel® GM45 Express Chipset.

**Comment by raysan5** [comment]
Hi @EdwardAngeles! Your GPU is quite old and it only supports up to OpenGL 2.0 on Windows systems. By default raylib uses OpenGL 3.3... but you can change that easily! :)

1. Open Notepad++ and open `C:\raylib\raylib\src\core.c`
2. Execute Notepad++ script: `raylib_source_compile_gl11` (this will recompile raylib with support for OpenGL 1.1 and copy all required files in required folders)
3. Open in Notepad++ any raylib example (`core_basic_window.c`) and execute script: `raylib_compile_execute`

It should work. Just keep in mind that some examples (shaders-based ones) will not work because they are not supported by the GPU.

**Comment by EdwardAngeles** [comment]
It works! Thank you. Can't wait to start playing with the raylib.
