### ISSUE TITLE
audio doesn't work on Chrome m88

### ISSUE THREAD

**Issue by maks** [raysan5/raylib#1555]
https://raylibtech.itch.io/rfxgen as an example doesn't work on current stable Chrome.

The error in the console is pretty self-explainatory:
```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
29698 @ rfxgen.js:1
```

**Comment by raysan5** [comment]
@maks yeap, that's a know issue and I'm afraid it's a security constraint, it's required an user action to enable it. You can check https://www.raylib.com/examples.html and https://www.raylib.com/games.html. Audio should be working in those cases because Audio Context is started with a user action.

rfxgen does not work if accessed directly from the link you shared but if you access from https://raylibtech.itch.io/ it should work, well, it works from me on Windows 10, Chrome 88.
