### ISSUE TITLE
The lib looks very cool , any chance to support VSC++ ?

### ISSUE THREAD

**Issue by meiry** [raysan5/raylib#156]
I tried to run cmake for VSC++ 2013 , but it is to many compilation errors ?
is there any change to do VSC++ port ?
Thanks!

i started to do it , but stoped here ... 
```
>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(461): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(461): error C2146: syntax error : missing ')' before identifier 'b1111100000000000'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(462): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(462): error C2146: syntax error : missing ')' before identifier 'b0000011111000000'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(463): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(463): error C2146: syntax error : missing ')' before identifier 'b0000000000111110'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(464): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(464): error C2146: syntax error : missing ')' before identifier 'b0000000000000001'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(472): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(472): error C2146: syntax error : missing ')' before identifier 'b1111100000000000'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(473): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(473): error C2146: syntax error : missing ')' before identifier 'b0000011111100000'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(474): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(474): error C2146: syntax error : missing ')' before identifier 'b0000000000011111'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(483): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(483): error C2146: syntax error : missing ')' before identifier 'b1111000000000000'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(484): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(484): error C2146: syntax error : missing ')' before identifier 'b0000111100000000'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(485): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(485): error C2146: syntax error : missing ')' before identifier 'b0000000011110000'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(486): error C2059: syntax error : 'bad suffix on number'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(486): error C2146: syntax error : missing ')' before identifier 'b0000000000001111'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(517): error C2061: syntax error : identifier 'GetTextureData'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(517): error C2059: syntax error : ';'
1>G:\dev\cpp\2d\2d_engins\raylib-master\raylib-master\src\textures.c(517): error C2059: syntax error : 'type'
```

**Comment by raysan5** [comment]
Undoubtly is an improvement to consider! 

Actually, I remember some raylib user was using it with VSC++, don't remember which version... It shouldn't be difficult to get it working...

I'll try to do some tests.

**Comment by NoxAtMidnight** [comment]
Hello there!
I've been trying to get raylib to work in Visual Studio 2015. I have a partial conversion of raylib.h to C++ (which is what I want to run it as) but even if I set the project to compile as C code I get some errors.

I'm including the header into my main.c file and I'm getting the following errors:

> 1>libraylib.a(core.o) : error LNK2019: unresolved external symbol _sinf referenced in function _MatrixRotate
1>libraylib.a(core.o) : error LNK2019: unresolved external symbol _cosf referenced in function _MatrixRotate
1>libraylib.a(textures.o) : error LNK2019: unresolved external symbol ___chkstk_ms referenced in function _stbi__jpeg_test
1>libraylib.a(rlgl.o) : error LNK2001: unresolved external symbol ___chkstk_ms
1>libraylib.a(utils.o) : error LNK2001: unresolved external symbol ___chkstk_ms
1>libglfw3.a(init.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
1>libraylib.a(utils.o) : error LNK2019: unresolved external symbol __imp___iob referenced in function _TraceLog

I'm currently linking to:
> libraylib.a
libglfw3.a
legacy_stdio_definitions.lib
libpthreadGC2.a
libgdi32.a

The "legacy_stdio_definitions.lib" fixes some _scanf linker errors but I can't figure out how to fix the rest. Could you help me out with this? If I get this working in C I could probably help with a commit to get it working in C++ (maybe even a .sln?). 

You mentioned another user that got it working in VS2015, are you refering to [this pull](https://github.com/raysan5/raylib/pull/56)?

I've been trying directly linking to the MinGW libs but I'll try a native VS compile now. By the way, older VS editions won't work because they don't have the C99 compiler.

**Comment by raysan5** [comment]
Hi @NoxAtMidnight, yes, actually @ghassanpl was the user that get it working on VS 2015! He also ported raylib to Lua and worked with a VS 2015 solution...

I'll try to take a look myself.

**Comment by raysan5** [comment]
Oh, I see one possible issue. You're trying to use MinGW compiled .a libraries directly in Visual Studio 2015. It's possible but libraries should include some MinGW specific objects (related: http://stackoverflow.com/questions/3537368/c-building-static-library-question) you should use Visual Studio 2015 library versions.

You probably need to re-compile raylib with Visual Studio 2015 to generate `libraylib.lib`; the other required libs (.lib) can be downloaded from their respective pages:

  - GLFW3 - http://www.glfw.org/download.html
  - OpenAL Soft - http://kcat.strangesoft.net/openal.html#download
  - pthread Win32 - ftp://sourceware.org/pub/pthreads-win32/dll-latest (actually, only required if you're using physac module)

I'll try to setup a VS 2015 project to compile source and also a project solution template for examples.

**Comment by ghassanpl** [comment]
Making it *compile* on VS2015 (latest preview) is fairly easy: http://pastebin.com/raw/hyhptRm4

Didn't try to link/run it, so can't check if it actually runs and works :)

**Comment by raysan5** [comment]
Hi @ghassanpl! Thank you very much for the diff! :D

**Comment by NoxAtMidnight** [comment]
Hey guys I've managed to mostly get it working right now! I've more-or-less managed to replicate @ghassanpl 's diff on my own and it's compiling. Including raylib as a different project in my solution so I could compile it manually also fixed the linking errors I mentioned above.

However, now I'm having another issue - rlgl is failing to link with OpenGL and it's pretty much a wall of 
> raylib.lib(rlgl.obj) : error LNK2019: unresolved external symbol __imp__glBegin@4 referenced in function _rlBegin

I'll keep trying to see what I can do.

**Comment by raysan5** [comment]
Are you linking with OpenGL library?

**Comment by NoxAtMidnight** [comment]
Nevermind, realised I wasn't :)) It works in C now! I'll try converting it to C++ next, at least partially, and I'll try to post some files over the weekend if I'm home if you guys still need it.

**Comment by raysan5** [comment]
Wow! Great news @NoxAtMidnight! I'll try adding @ghassanpl corrections for MSC compiler on raylib. It would be great to have a solution available for VS 2015! :D

**Comment by ghassanpl** [comment]
@raysan5 You may also want to add the MSVC *.lib files to the src/external/*/lib directories, for easier out-of-the-box linking.

**Comment by raysan5** [comment]
sure!

**Comment by NoxAtMidnight** [comment]
Some minor progress: I actually got it running in C++ but the C compound literals are C++ incompatible (see the color defines) and there's no constructors for the C structs so I had to write something like 
`Color rayWhite = { 245, 245, 245, 255 };`
instead of passing
`RAYWHITE`

However, the biggest issue was some strange include weirdness where CloseWindow(), ShowCursor() and Rectangle were complaining of redefinition in the winuser32 and wingdi headers. I had to rename those to rayCloseWindow() etc. which worked, and I included windows.h right before gl.h in rlgl.c.

I'm not sure how to fix that and it kind of works right now so I'm happy with that. I tried a bunch of small changes in the code and it's still working OK so I'll chalk that up to a success for today!

**Comment by raysan5** [comment]
Great! Thanks for the update @NoxAtMidnight.

About redefinition issue, I face that problem several times when including "`windows.h`" (hate that header), why need to include that header?

**Comment by NoxAtMidnight** [comment]
I'm not at home now so I can't check but basically I'm getting tons of errors from gl.h if I don't include windows.h ahead of it (mainly because it can't find the windows functions it's calling). The gl.h file itself belongs in the standard VS header folder so now that I'm thinking more clearly it could be an issue with that configuration in particular.

**Comment by raysan5** [comment]
Ok, just an update: Corrected MSC issues on commit https://github.com/raysan5/raylib/commit/a008d49230c0f7543d8921e68f757dea7934a8c5. 

I setup a solution in Visual Studio Community 2015 with 3 projects:
 - **raylib** (static library) - Configured as Compile as C Code -> OK!
 - **raylib_example** (core_basic_window.c) - Configured as Compile as C Code -> OK!
 - **raylib_example_cpp** (core_basic_window.cpp) - Configured as Compile as C++ Code -> Issue with compound literals, replaced by vars -> OK!

Please @NoxAtMidnight, let me know how if it worked for you.

**Comment by meiry** [comment]
@raysan5  and other great job ! 
is it problem to ask to provide manual on how to configure VS or to Make VS 2013 solution also 
as 2015 is to much for my poor pc . 
and this is the point of this lib to be able to run on low end pc's , right ? 
Thanks

**Comment by NoxAtMidnight** [comment]
@raysan5 Hey there, I just looked into your commit and I can't seem to find the .sln/vcproj/cpp files, nor anywhere else in the develop branch. I'm new to github though, if you could point me to the right place?
@meiry if @raysan5 can't do it I can give it a try on Monday when I get back to work, we use VS2013 there so I should be able to get it to run. Theoretically there shouldn't be any problem since VS2013 has the C99 features raylib uses - it wouldn't work on VS2012 for example without some large changes to the code.

**Comment by raysan5** [comment]
Sorry @NoxAtMidnight, not uploaded yet the solution, need to do some tests (examples) and organize it properly. I will post it in this issue (that's the reason it's still open :P).

About VS2013 I don't have it installed on my computer... but it shouldn't be difficult to configure, just setup *Project Properties*:

  - **Include directories**: C/C++ > General > Additional Include Directories
  - **Library directories**: Linker > General > Additional Library Directories
  - **Libraries to compile with code**: Linker > Input > Additional Dependencies (glfw3.lib;gdi32.lib)

By the way, I solved the issue with compound literals for MSC C++ compiler, just redefined them with Color constructor. I'll upload everything ASAP.

**Comment by raysan5** [comment]
Just uploaded VS2015 solution with raylib project and a couple of example projects (C and C++). Check commit https://github.com/raysan5/raylib/commit/7e367273282f4ce1986b2b95cd86a2b8c8c4a81c.

Please, could someone let me know if it works? Thanks!

**Comment by ghassanpl** [comment]
Works for me, however:


#ifdef __cplusplus
    Color(unsigned char cr, unsigned char cg, unsigned char cb, unsigned char ca) : r(cr), g(cg), b(cb), a(ca) { }
#endif

Is not necessary. Plain structures in C++ (without constructors) can be initialized from { } initializers.

**Comment by raysan5** [comment]
Hi @ghassanpl! Thank you very much for the note! Just changed in commit https://github.com/raysan5/raylib/commit/cc2b3228d18f3bc4cd58ee4298cde78846cfde9e.
