### ISSUE TITLE
[models] DrawPoint3D() draws a point using line segment

### ISSUE THREAD

**Issue by copark86** [raysan5/raylib#1655]
It is drawing a line segment instead of a point. Looking at the code, it looks like the intension was to draw a point as a very short line segment. 

p.s I just saw the comment above the function and realized that the actual intension is to draw a line segment. But it still looks like a line. Need to shorten the line length? 

https://github.com/raysan5/raylib/blob/bc9194690c43a6a72d0fc9d16e29bc9831b030f9/src/models.c#L148

**Comment by raysan5** [comment]
@copark86 Yes, it's designed this way because raylib does not expose `GL_POINTS`, internal buffers for the batching system are just for lines, triangles and quads.

Actually, that function was contributed by a raylib user and I accepted it for convenience for other users, I'm not specially happy with it.

**Comment by yukkysaito** [comment]
@raysan5 By the way, is there any reason why GL_POINTS is not provided?
In my environment, even with rlBegin(GL_POINTS), it did not work as expected.

**Comment by raysan5** [comment]
@yukkysaito Points drawing was kept out of raylib for simplicity, at the time raylib was designed it was focused on gamedev education and drawing with points is hardly ever used in that environment, afaik.
