### ISSUE TITLE
[rglfw] Support continue drawing while windows is being resized

### ISSUE THREAD

**Issue by lazaroblanc** [raysan5/raylib#1680]
I've already asked this question over [on the Discord server](https://discord.com/channels/426912293134270465/427518168995725317/824759090756583485).

I'd like for my windows to continue drawing while they are being resized.
At the moment drawing is interrupted until resizing of the window has stopped.

This issue has been addressed over [on Stack Overflow](https://stackoverflow.com/questions/45880238/how-to-draw-while-resizing-glfw-window).

![image](https://user-images.githubusercontent.com/40198445/112549430-17f27380-8dbe-11eb-9faf-b96f0782bd11.png)

GLFW would allow such a feature but according to @raysan5 this would need a library redesign to be supported in raylib.

Maybe we can get this in a future major version? (v4 or higher?)

**Comment by lazaroblanc** [comment]
Can we update this to "(...) while window is being dragged & resized" ?

**Comment by raysan5** [comment]
I've been investigating if this is feasible and it seems with current raylib implementation it's not possible, users should work at a lower level to accomplish this. In any case, if anyone feels brave enough to investigate it further and find a possible solution, you are welcome.

**Comment by beetaa** [comment]
@efejjota @raysan5 @IanBand  I found this pr in glfw repo. [Win32: Do the event processing during window resize/move](https://github.com/glfw/glfw/pull/1426)

**Comment by Not-Nik** [comment]
This could possibly be resolved by polling GLFW events on a seperate thread and syncing them up with the main thread later. This would require a C version bump to C11, to use `threads.h` and `stdatomic.h` as well as a minor increase in internal complexity from what I can tell, but it would be virtually invisible to the end user. The most challenging part of this, would be the proper handling of resizing, because `WindowSizeCallback` calls `SetupViewport`, which in turn calls `glViewport` via `rlViewport` and OpenGL isn't thread-safe.

Since Microsoft's MSVC doesn't support C11's threading anyways, we could also add a library to handle threading or write some functions into raylib (I'm thinking rthreads).

I'd be willing to type up a prototype, but I can totally understand if this feels like too much of a complexity increase.

**Comment by orcmid** [comment]
Microsoft has announced the addition of C11 atomics, threads, and **`complex`** to Visual Studio C/C++ support.  `stdatomics.h` will be available immediately with [Visual Studio 17.5 Preview 2](https://devblogs.microsoft.com/cppblog/c11-atomics-in-visual-studio-2022-version-17-5-preview-2/).  

I suspect it is probably better to wait for the VS 17.5 release than attempt to build such functionality separately, especially where C reserved-words and qualifiers come into play.

PS: `raylib` already requires the version bump because of the use of **`struct`** initializers and returns.

**Comment by raysan5** [comment]
@Not-Nik It will add a level of complexity to the library just for a small feature that I prefer to avoid.

> raylib already requires the version bump because of the use of struct initializers and returns.

@orcmid afaik, all raylib sources code is C99 valid, in which cases it requires C11?

**Comment by Not-Nik** [comment]
Maybe instead of putting the whole solution into raylib, we could make the `rlViewport` call lazy, so it's only called on `BeginDrawing`. This way users could put the `WindowShouldClose` call into another thread themselves, without increasing library complexity by a lot.

**Comment by raysan5** [comment]
@Not-Nik Still, it requires a complexity increase... and moving `rlViewport()` to `BeginDrawing()` could imply redundant code called every frame and if trying to avoid it, it implies extra variables to be checked every frame.

**Comment by orcmid** [comment]
@raysan5 
> @orcmid afaik, all raylib sources code is C99 valid, in which cases it requires C11?

In the current releases of Visual Studio, there is no option for compiling `std:c99` although `std:c11` and `std:c17` can be specified.

Here is a compilation of mine doing something similar to what `raylib/projects/scripts/build-windows.bat` accomplishes, using `std:c11` and raylib 4.0.0.

![F23xy004-2023-01-12-1557-VCrayApp-C11](https://user-images.githubusercontent.com/3372580/212210131-5d78e21e-279f-4b2e-91dc-481f1e1fe4dd.png)
 
What matters here is the first part, the compilation of a cache of raylib `.obj` files.  The rest just shows that it all works to produce an executable.

I can't say `std:c99` but I can specify `Zc:__STDC__` and this is all the farther the compilation gets.

![F23xy003-2023-01-12-1621-VCrayApp-nonC11](https://user-images.githubusercontent.com/3372580/212210419-78e6dd9a-784a-43a1-b1f6-03436bf3a7c0.png)

I have seen other failures related to certain assignment operations with structures, but the current VC/VC++ compiler either accepts those or they have been repaired.  
 I have no idea..

**Comment by chriscamacho** [comment]
This all seems like a lot of trouble and complexity (certainly doesn't follow the KISS principle!) for something that might only be used once or twice per run, for seconds at a time, and often not at all.

what you get in return for all the hard work is the certainty that some corner case will bite you, depending on platform and or hardware.

... and indeed many games are full screen in any case.

Is it really worth potentially breaking things where the majority of users are not impacted and if they are its a minor artefact for a few seconds per run ?

**Comment by ivanjaros** [comment]
I just noticed this bug(from UX point of view). I understand that for games and alike, this is a non issue as they operate in fixed dimensions. But take a file explorer or a text editor, where manual window resizing is a norm, and this looks terrible for the end-user and makes the author look like a fool for making such a bad application.
