### ISSUE TITLE
Poor CPU Performance

### ISSUE THREAD

**Issue by kd7tck** [raysan5/raylib#17]
When running simple text based games, the CPU usage can be as high as 30%. It can be traced back to a poor implementation of system polling with GLFW.

**Comment by raysan5** [comment]
After further investigation, it seems that high (100% or 25% for quad-cores) CPU usage is the expected behavior for most cases in OpenGL/Direct3D games, **it mainly depends on graphics driver implementation**. Game loop just keeps running all the time if not locked in any way. In GLFW3 is possible to glfwWaitEvents() instead of glfwPollEvent() so frame swap can be locked waiting for events and CPU usage falls to ~1% but that's not the desired behaviour in a game. Enabling VSYNC could have a similar effect but it also depends on graphics driver...

A couple of links with further info:

http://stackoverflow.com/questions/18365269/cpu-usage-is-high-when-using-opengl-control-class
http://gamedev.stackexchange.com/questions/19066/why-is-opengl-using-100-cpu-shortly-after-start-up-when-wglswapintervalext-is-e

**Comment by kd7tck** [comment]
Having an option in the lib API for vsync might help allot. When vendor drivers have trouble with vsync, the opengl software can make up for that and override the driver settings.

```c++
#ifdef _WIN32
    // Turn on vertical screen sync under Windows.
    // (I.e. it uses the WGL_EXT_swap_control extension)
    typedef BOOL (WINAPI *PFNWGLSWAPINTERVALEXTPROC)(int interval);
    PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT = NULL;
    wglSwapIntervalEXT = (PFNWGLSWAPINTERVALEXTPROC)wglGetProcAddress("wglSwapIntervalEXT");
    if(wglSwapIntervalEXT)
        wglSwapIntervalEXT(1);
#endif
```

**Comment by raysan5** [comment]
GLFW already uses `WGL_EXT_swap_control` extension to provide VSYNC (where this extension is available) but, again, it can be overriden by graphic driver, forcing on or off. Here it is further information on `Swap Internal`:

https://www.opengl.org/wiki/Swap_Interval

But there is something I can do; I can expose GLFW VSYNC mechanism to raylib users through a flag, to be set before windows creation. That way users can try forcing VSYNC and wait for the driver to respond.

I'm working on it.

**Comment by kd7tck** [comment]
Thank you for the time and effort you have put into this.

**Comment by raysan5** [comment]
Use function:     SetConfigFlags(FLAG_VSYNC_HINT);    // Use before InitWindow()

Underlying system, GLFW3, will try to enable vsync if graphic driver allows it.

Upcoming raylib v1.3 includes this change.

**Comment by raysan5** [comment]
Issue corrected on commit https://github.com/raysan5/raylib/commit/b681e8c2775bbb467c0f0607afd9840fda25c563.
