### ISSUE TITLE
[core] texture coordinates in shader don't work with rectangle

### ISSUE THREAD

**Issue by Nv7-GitHub** [raysan5/raylib#1730]
When drawing a fullscreen rectangle, `fragTexCoord` (Texture Coordinates) isn't correct in a post-processing shader. However, when drawing a `RenderTexture2D`, the texture coordinates are mapped correctly.

**Comment by Nv7-GitHub** [comment]
I forgot to add the images, so I'm adding the images here.
When rendering with fullscreen rectangle:
![notex](https://user-images.githubusercontent.com/50369270/115621542-85090400-a2ab-11eb-9f04-8e29fc0c9472.png)
When rendering with `RenderTexture2D`:
![tex](https://user-images.githubusercontent.com/50369270/115621598-99e59780-a2ab-11eb-95ac-f1144ca0fe8e.png)
Relevant GLSL Code:
```glsl
finalColor = vec4(fragTexCoord, 0, 1);
```

**Comment by raysan5** [comment]
@Nv7-GitHub I investigated this issue, specially the first case, why the `fragCoords` result is that green color? Here it is the reason:

![raylib_frag_coords_issue](https://user-images.githubusercontent.com/5766837/115628294-bb24a300-a300-11eb-93e6-9ea701fa7e24.png)

Actually this image is not completely accurate due to the internal texture vertical flip and other concerns but the idea can be seen. Shapes use by default a white rectangle from font texture when being drawn. This is designed this way to optimize draw calls batching when combining shapes and default font.

This behavior can be changed calling the following function (it requires including `rlgl.h`):
```c
// Set default internal texture (1px white) and rectangle to be used for shapes drawing
SetShapesTexture(rlGetTextureDefault(), (Rectangle){ 0.0f, 0.0f, 1.0f, 1.0f });
```

In that case, the default 1x1 px internal texture will be used on shapes drawing.

Is there any specific use case where using the font rectangle is a bad idea?

**Comment by EliTheCoder** [comment]
How can we do this now that rlGetTextureDefault has changed to GetTextureIdDefault?

**Comment by raysan5** [comment]
@EliTheCoder You can do it using:
```c
Texture2D texture = { rlGetTextureIdDefault(), 1, 1, 1, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 };
SetShapesTexture(texture, (Rectangle){ 0.0f, 0.0f, 1.0f, 1.0f });
```
