### ISSUE TITLE
[raudio] Audio files loop with a slight delay

### ISSUE THREAD

**Issue by Not-Nik** [raysan5/raylib#1776]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When looping audio files where timing is important, for example music a slight delay can be observed, causing files that don't loop at the exact same time to fall out of sync.

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*
MacOS 11.3.1, MacBook Pro 2018 13" 4 Ports

### Issue Screenshot

No screenshot, for obvious reasons

### Code Example

Code and sound files used are in the attached zip file:

[Sound.zip](https://github.com/raysan5/raylib/files/6490016/Sound.zip)

**Comment by raysan5** [comment]
@Not-Nik It seems the issue could be on `raudio.c`, on the following lines:
```c
static void OnSendAudioDataToDevice(ma_device *pDevice, void *pFramesOut, const void *pFramesInput, ma_uint32 frameCount)
{
    //...

                    // If we weren't able to read all the frames we requested, break
                    if (framesJustRead < framesToReadRightNow)
                    {
                        if (!audioBuffer->looping)
                        {
                            StopAudioBuffer(audioBuffer);
                            break;
                        }
                        else
                        {
                            // Should never get here, but just for safety,
                            // move the cursor position back to the start and continue the loop
                            audioBuffer->frameCursorPos = 0;
                            continue;
                        }
                    }
    //...
}

It should be reviewed with a bit of care...

**Comment by Not-Nik** [comment]
From my testing these lines are never reached.

**Comment by raysan5** [comment]
Related function is `UpdateMusicStream()`. I tested it on Windows and it seems to work ok... anyone can confirm?

I'd need a contiguous sound to verify it properly...

**Comment by mausimus** [comment]
I had a look at this, here are my findings:

@Not-Nik 
* your audio files are not matching in length, they are 24815 and 46703 samples long so won't loop perfectly (6% off)
* please switch to .ogg - .mp3 has a quirk where it rounds audio length to mp3 frame size (1152) introducing another cause of desync, Audacity shows correct lengths while dr_mp3 reports them incorrectly to raylib as 25334 and 47232 (after dividing by 2 for stereo)
![audacity](https://user-images.githubusercontent.com/73635663/119215047-b77c6b80-baba-11eb-9b21-91e37f34e288.png)
![raylib_samples](https://user-images.githubusercontent.com/73635663/119215049-b9dec580-baba-11eb-895c-f450f6af4fa1.png)

@raysan5 
I believe the main cause of desync is the fact when a stream ends (streamEnding = true at raudio.c:1699) then StopMusicStream below stops it immediately (discarding the possibly partial buffer that just got filled in) and the stream will be restarted from zero on the next frame, regardless of how all of this aligns with audio duration. While this is fine for music in general, if we'd want to have better loops perhaps one way would be to rewind the stream within UpdateMusicStream and requeue its beginning into the last partial buffer, avoiding doing Stop/Play altogether.

I've put together an improved example with two streams of 0.51s (uneven frame boundary) of the drum at 44.1kHz and at 48kHz so that they have different sample counts. Ideally this would produce just one drum sound (i.e. two in unison) twice a second without any desyncing, which atm I can hear plenty (on Windows).

[sound_bug_v2.zip](https://github.com/raysan5/raylib/files/6525829/sound_bug_v2.zip)

**Comment by raysan5** [comment]
@mausimus Thank very much for the detailed investigation of this issue! About the proposed solution:

 > rewind the stream within UpdateMusicStream and requeue its beginning into the last partial buffer, avoiding doing Stop/Play altogether.

It could be an update to consider, actually, it's been quite a long time that I want to do a complete review of `raudio` module...

For now, it's seems the better solution is on user side, just taking care of the provided audios to fit the system properly.

**Comment by z7ealth** [comment]
In my case it was caused by an extra silence at the end of the sound file. I managed to fix it by checking the "Export as a loop" option when exporting a file in LMMS.
