### ISSUE TITLE
[templates] Error Compiling advance game for android 

### ISSUE THREAD

**Issue by hero2002** [raysan5/raylib#1833]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I can't compile advance game for android

### Environment

Win 10,Ndk 21r,minigw_x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0,openjdk 8
btw I tried the official mingw that came with the package and the issue happened
also tried copying the JDK to just C: and edited the path and the same thing happened
### Issue Screenshot
![لقطة الشاشة (4)](https://user-images.githubusercontent.com/20283475/122237527-11a8fa80-cec8-11eb-85bb-e70b8f9e7d4a.png)

**Comment by DarkKnight2000** [comment]
I had the same problem. This happens because there's a space character in the JDK path ("Program Files"). So line 248 is seen as:
    run the program `C:\Program` with `Files\AdoptOpenJDK` as an argument (Because arguments are separated by space).
I found a workaround.
1. Replace all spaces in JAVA_HOME (line 50 currently) with a '+' like:

`JAVA_HOME              ?= C:\Program+Files\Android\Android+Studio\jre`

2. Then go to line 248 where the `generate_apk_keystore` recipe is defined and add this line above the recipe

`KEYTOOL="$(subst +, ,$(JAVA_HOME)\bin\keytool)"`

3. Inside the recipe replace `$(JAVA_HOME)\bin\keytool` with `$(KEYTOOL)`

You need to do this wherever a program from `$(JDK_HOME)` is used in a recipe. For me, it was in `compile_project_class` and `sign_project_apk_package` recipes. Create a dummy variable above the recipes and use it inside the commands instead of directly using `$(JAVA_HOME)\some_program_name`.

**Comment by raysan5** [comment]
@DarkKnight2000 thanks for reporting. Did you try just using:
```
JAVA_HOME ?= "C:\Program Files\Android\Android+Studio\jre"
```

**Comment by DarkKnight2000** [comment]
@raysan5 yes that's working, Thanks! I thought of using that but assumed that `"` would be considered another character and will be added to the path when calculating values like `$(JAVA_HOME)\bin\keytool`. This is simpler. Edited my answer to include this.
