### ISSUE TITLE
[physac] Problems with ground detection

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#187]
It seems that there is some problem with ground detection.

**Comment by victorfisac** [comment]
I will work on that and other physics features those days. I will review everything and support custom shapes collisions, resolve collisions based on Contacts (new struct) and other features I saw by the Internet in other physics engines and tutorials. :)

**Comment by raysan5** [comment]
Hey @victorfisac! It sounds great to me! Please, take it easy! :D

By the way, for next raylib release I updated MinGW (GCC 5.3.0) and new version already comes with theading libraries, no need to link them manually.

**Comment by victorfisac** [comment]
*Current Physac development state*

- [x] Create physics thread based on time steps.
- [x] Add physics bodies and manifolds structs and functions.
- [x] Physics bodies basic dynamics (force -> velocity -> position).
- [x] Physics collision detection between circles.
- [x] Physics collision solving based on impulses and position correction due to overlapping.
- [x] [NEW] Physics angular velocity and torque calculations between circles.
- [ ] Physics collision detection and solving between polygons and circle vs polygons.
- [ ] Add debug functions (contacts position, normal vector and other information draws).
- [ ] Global review for performance and code consistency.
- [ ] Global review for bugs and strange behaviours (physics bodies values like friction, restitution) and comment code with result observations (best physics values for nice results).
- [ ] Create Physac Hello World example with user interactive features (create bodies with mouse, etc.).
- [ ] Clean spacing, comments corrections and improvements... and other little tweaks.

*Optional*
- [ ] Add third dimension to Physac module and adapt 3D polygon shapes creation to procedural meshes requested feature (#165). (*Note: I need to think about the best way to implement it and avoid typical if () conditions for Z axis calculations*).
- [ ] Create tool to perform polygon shapes by mouse clicks and export/import data to file (by default polygon shapes are created based on random values).
- [ ] Create platform mini-game with Physac (characters movement, explosions, shatter effects, etc).

It looks really nice comparing to first physac version. The code structure is better and simpler. I hope it will look so good at the end :D

**Comment by raysan5** [comment]
Wow @victorfisac! What a list of features! Please, take it easy... :)

**Comment by raysan5** [comment]
Hey @victorfisac! Any news on those features? I'm planning to launch next raylib release in a couple of weeks and it 'd be great to include a `physac` update! :D

**Comment by victorfisac** [comment]
Hi @raysan5 I'm currently trying to test Physac in Android. Then, I'll send you a zip with my repository and you can review the structure and suggest any changes or feedback. After making final changes, I'll release the Physac repository to public and you can add it to raylib with two examples I created :)

**Comment by raysan5** [comment]
Hey @victorfisac! It sounds like a plan! Great! :D

**Comment by raysan5** [comment]
Just for reference: https://github.com/victorfisac/Physac
