### ISSUE TITLE
[raudio] Feature Request for Audio Effects

### ISSUE THREAD

**Issue by adct-the-experimenter** [raysan5/raylib#1943]
I would like to request a feature for some general audio effects into raudio module such as low-pass filter, high-pass filter, echo, reverb, etc. 

This would be useful for making a special dynamic environment in a video game such as applying reverb to sounds in a cave level.

Also it would be useful for a synth or other sound applications requiring effects.

**Comment by adct-the-experimenter** [comment]
I am doing some work on it in my fork. 
https://github.com/adct-the-experimenter/raylib

I was wondering if others would be interested in working on this.

**Comment by orcmid** [comment]
I think this is an interesting ideal.  I'm more interested in supporting beginners with raylib though.

 I do wonder whether a digital audio workstation (DAW) and all that makes available might be a better approach to creation of audio elements for games though, including atmospherics.

**Comment by orcmid** [comment]
Please move this issues to Discussions, since you are not providing a feature request or submission.

Also, I suggest you work on the side of a fork and not directly in a raylib/ fork.  I think it will make development of your ideas more observable, even more than working in a branch.  The idea of ambient effects and maybe even sensitive to player position is intriguing.

**Comment by adct-the-experimenter** [comment]
Thank you. I will move this to Discussions.
