### ISSUE TITLE
[text] Unicode text rendering

### ISSUE THREAD

**Issue by ibesora** [raysan5/raylib#2022]
### Issue description

This is quite similar to https://github.com/raysan5/raylib/issues/1095 but it's not exactly the same.
Using DrawText and passing a char* with foreign characters (ç, à, ...) results in `?` being rendered instead of those characters

### Environment

Windows 10, RTX 3080 with the latest drivers

### Issue Screenshot
![image](https://user-images.githubusercontent.com/2301378/135513930-de133700-763a-4303-b1a3-4ef326ab8fbc.png)

### Code Example

`DrawText("Comença a jugar", 190, 350, 20, RED);`

**Comment by orcmid** [comment]
See [#69 of Chris Dill](https://github.com/ChrisDill/Raylib-cs/issues/69).

The problem with char* strings, unless you are using UTF8 (tricky) is that there are code-page and code-point issues, depending on ISO 8859-x cases, etc.    It also appears to be the case that DrawText just doesn't accept 8-bit codes with values over 127 (x7F), so you're stuck in what is called the International Reference Version of ISO 646-1973 :).

The expected cure is to handle Unicode and then also have fonts that provide glyphs for the Unicode code points used.  You can try compiling with Unicode options, but there may need to be work on DrawText also.  

(It would be very good news that the treatment you're seeing is because those are invalid as UTF-8.  Probably wishful thinking though.)

**Comment by raysan5** [comment]
@ibesora Could you try saving the code file as UTF-8? I think those characters are included in the default raylib font.

**Comment by ibesora** [comment]
Sorry @raysan5 I couldn't check it before. 
I thought it was already UTF-8 encoded but I tried saving the file with UTF-8 encoding in VS2019 just in case but the same thing happens

**Comment by orcmid** [comment]
Try adding `/utf-8 /validate-charset` to the compile options, including for the build of raylib object files.   UTF-8 is not automatically detectable*, although VS2019 should not be fooled.  (`/std:c11` too.)

You might need /Wall just for your own code  or maybe /W3 to see any warnings this might raise.

This does not get around any `DrawText` deficiency but you'll know that you've done all that is in your power separate from that.

----
* Microsoft created a file-prefix trick for signaling UTF-8 that is simply not in the spirit of the Unicode standard and I don't think their editors do it consistently if at all any longer.  It doesn't harmonize with *nix (and Java).

**Comment by raysan5** [comment]
@ibesora @orcmid It works ok on my side:
![screenshot000](https://user-images.githubusercontent.com/5766837/135749927-e09fdb0e-3099-4206-863d-3a0dcdb7bc94.png)
Please, could you share the code file? Are you using latest raylib from github master branch?
Please, also test drawing the font to check the characters are there:
```
DrawRectangle(0, 0, 128, 128, BLACK);
DrawTexture(GetFontDefault().texture, 0, 0, WHITE);
```

**Comment by raysan5** [comment]
I'm closing this issue. I would reopen it if problem persists after the checks.
