### ISSUE TITLE
[core] Make the Makefile for PLATFORM_WEB more agnostic

### ISSUE THREAD

**Issue by hidden-r4d** [raysan5/raylib#2200]
In examples/core/Makefile.Web:

```make
ifeq ($(PLATFORM),PLATFORM_WEB)
    # Emscripten required variables
    EMSDK_PATH         ?= C:/emsdk
    EMSCRIPTEN_PATH    ?= $(EMSDK_PATH)/upstream/emscripten
    CLANG_PATH          = $(EMSDK_PATH)/upstream/bin
    PYTHON_PATH         = $(EMSDK_PATH)/python/3.9.2-1_64bit
    NODE_PATH           = $(EMSDK_PATH)/node/14.15.5_64bit/bin
    export PATH         = $(EMSDK_PATH);$(EMSCRIPTEN_PATH);$(CLANG_PATH);$(NODE_PATH);$(PYTHON_PATH);C:\raylib\MinGW\bin:$$(PATH)
endif
```
I'm pretty sure `$$(PATH)` is an error, and this uses hardcoded windows paths.

**Comment by raysan5** [comment]
@hidden-r4d I think that syntax is correct: https://stackoverflow.com/questions/8941110/how-i-could-add-dir-to-path-in-makefile

**Comment by raysan5** [comment]
@orcmid No, it shouldn't be hardcoded that way. I was referrin to `:$$(PATH)` statement. I'm removing that hardcoded path.

Actually, when building with `emscripten` toolchain, it should be used the tool [`emmake make`](https://emscripten.org/docs/compiling/Building-Projects.html) instead of `make`.
