### ISSUE TITLE
[core] GetScreenToWorld2D() jitters when setting camera rotation to look direction of mouse

### ISSUE THREAD

**Issue by DrBellubins** [raysan5/raylib#2251]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

TL;DR: I want my player to look at the mouse cursor, then have the camera follow the player's rotation. Doing so makes both the camera, and player rotation jitter.

I'm using GetScreenToWorld2D() to obtain the mouse position in world-space, obtaining the relative look direction from this, then obtaining the "look at" rotation through the use of atan2(), and finally setting an object's rotation to it (such as a triangle sprite). The result works as expected, the object rotates to look towards the mouse cursor.

Problems arise when attempting to set the camera's rotation to that same "look at" rotation. In my testing, no matter the order-of-operation, not only does the camera's rotation begin to jitter, but the rotation of the object it's following does as well.

Any help would be greatly appreciated,
DrBellubins.

### Environment

PC, Windows 11 64-bit, OpenGL 4.3, Intel i5 1135G7 - Intel Iris Xe Graphics

### Issue Screenshot

Below are gifs showing the code example in action:

Without setting camera rotation:
![uOOvcdvCFA](https://user-images.githubusercontent.com/88703839/147524211-88b3fb16-2e06-4e34-b31d-3b21f742f9bf.gif)

With setting camera rotation:
![gNjkV2XEzF](https://user-images.githubusercontent.com/88703839/147524399-16cabc97-1b84-43fb-8170-b4107587769b.gif)

### Code Example

(Code did not paste correctly so here's a gist link, sorry)
[Raylib GetScreenToWorld2D camera jittering example](https://gist.github.com/DrBellubins/e966682a999322e70896e8db46dfcc4f)

**Comment by JeffM2501** [comment]
I don't think this is a problem with the raylib code, but a problem with what you are trying to do in concept. You are rotating two things at the same time with one angle input, I'm not sure what you expect to happen in that case.  The raylib functions all work on a single frame of data, so any 'jitter' has to be problems in your code that happen over time.
  
Setting the rotation for the camera is going to rotate the space the camera is in. This will change what the next call to GetScreenToWorld2D does, because it's going to use the new angle. This means that even if the mouse does not move, the world coordinates you get back for the mouse position will take the new rotation into account. Then you rotate to that new rotation and start the problem all over again. Your code works when you don't rotate the camera because the absolute angle you compute is always relative to a fixed frame of reference. When you rotate the camera, you are computing it relative to a rotating frame of reference and not compensating for that.
I'm not sure what your goal is, but I think you want to compute your angle in screen space, and then always align the camera to the screen relative angle.

Here is a quick test I did.
![angle_test](https://user-images.githubusercontent.com/322174/147684986-87af5082-462f-4f8c-b1a5-c863cad958e1.gif)
There appears to be no problem with GetScreenToWorld2D working at any rotation. The world angle (WA) is computed in world space, and as you can see as the camera rotates the angle to the mouse point changes. This is because the world is rotating, but the screen is not. A screen point at one angle will not map to the same world point at a different angle.

If you could explain more in detail what you are trying to do, we can probably help you find the best way to do that, it most likely does not involve using GetScreenToWorld2D to compute a camera rotation every frame.

**Comment by DrBellubins** [comment]
I apologize for not understanding the how the way I was following the player rotation is wrong. My original intent was to have a sort of top-down mouse look where the player looks around, and the camera follows, but I ultimately decided to not rotate the camera at all as it would have been too disorienting for my game. Thanks for the thoughtful reply, sorry to waste everyone's time... This issue can be closed, if you want.

**Comment by raysan5** [comment]
I'm closing this issue.
