### ISSUE TITLE
Enable to run the exe file

### ISSUE THREAD

**Issue by Ponot** [raysan5/raylib#2266]
Error:
![z3086579254813_d2c3fc37433bf336f4f9a4397e5e82ce](https://user-images.githubusercontent.com/97088175/148367053-3578a696-8dc3-447b-a258-8748b6a8c704.jpg)
Can anyone help me?

**Comment by raysan5** [comment]
It seems it's an issue related to C#, not raylib C library.

**Comment by orcmid** [comment]
@Ponot this does not appear to be an issue with raylib, as @raysan5 remarks.

You should ask this on the raylib Discord where people can help you learn to handle the C# bindings and also whatever is required to use and execute with assemblies properly.

PS: Also retype the error message and/or include the entire output so that it is easily readable.  (Making your window narrower will help with that.)

**Comment by Ponot** [comment]
![z3088216514391_1348c7ad82e9a995f16c0408350efe81](https://user-images.githubusercontent.com/97088175/148481803-0017ed9b-25a6-482d-9d3b-ac974c48a67d.jpg)

**Comment by orcmid** [comment]
This is not enough information.  It is too cumbersome to work through this here.  Go to Discord.  Also, where did you get the VSCode folder that you are using and where have you put it?
