### ISSUE TITLE
[Documentation/Wiki] Compiling for wasm/html5 on Linux

### ISSUE THREAD

**Issue by hidden-r4d** [raysan5/raylib#2273]
In the [Wiki,](https://github.com/raysan5/raylib/wiki/Working-for-Web-(HTML5)) it instructs to compile for linux using the command `make PLATFORM=PLATFORM_WEB -B`, however, this does not pass the enviornment variables to `make`, (using GNU Make 4.3 on Ubuntu) resulting in an unsuccessful compilation, with `make` unable to find `emcc` and the other emsdk tools. I've found out (from [this stackoverflow post](https://stackoverflow.com/questions/70141302/compiling-raylib-for-html5-wasm)) that passing `-e` to the options is required, and removes this issue.

**Comment by RobLoach** [comment]
It should likely use `emmake make` rather than simply `make` too, but I'm not entirely sure myself. I've run into similar issues myself with the Makefiles, so had switched over to CMake.

Would you mind trying out the change to the project template I made over at https://github.com/raysan5/raylib/pull/2274 ? It adds some documentation to the CMake project template, and enables web compatibility.
