### ISSUE TITLE
raygui ang physac for bindings does not work

### ISSUE THREAD

**Issue by GuvaCode** [raysan5/raylib#2287]
For some reason, the  from the master for raygui ang physac doesn't work. My English is very bad. I made a video so it will be much clearer than I will try to explain.

https://youtu.be/h436771KLqk

**Comment by raysan5** [comment]
I'm afraid I don't understand the issue... `raygui` and `physac` are single-file header-only libraries and they can not be renamed to .c, they should be used in a very specific way, included with the user projects.

Also tried provide raylib Makefile and enabling `raygui` and `physac` flags works as expected.

**Comment by GuvaCode** [comment]
> Also tried provide raylib Makefile and enabling `raygui` and `physac` flags works as expected.

Well, that's what I used for the headers.

> can not be renamed to .c

I copied them and renamed them to make them merge. otherwise, where would the dll/so call for the headers come from?

**I also found a problem in the makefile** 

raygui.o : raygui.c
	$(CC) -c $< $(CFLAGS) $(INCLUDE_PATHS) 

physac.o : physac.c
	$(CC) -c $< $(CFLAGS) $(INCLUDE_PATHS)

changed to 

raygui.o : raygui.c
	$(CC) -c $< $(CFLAGS) $(INCLUDE_PATHS) **-DRAYGUI_IMPLEMENTATION**

physac.o : physac.c
	$(CC) -c $< $(CFLAGS) $(INCLUDE_PATHS)**-DPHYSAC_IMPLEMENTATION**

`

**Comment by raysan5** [comment]
@GuvaCode I'm afraid there is no problem with the Makefile, your change is not required. The Makefile creates `raygui.c` and `physac.c` using `raygui.h` and `physac.h` as a base.

The autogenerated `raygui.c` contains:
```c
#define RAYGUI_IMPLEMENTATION
#include "raygui.h"
```
Same for the autogenerated `physac.c`.

The problem as I said is trying to rename `raygui.h` to `raygui.c`, that's not how a single-file header-only library is supposed to be used.

**Comment by GuvaCode** [comment]
Okay. If I'm just performing 
make PLATFORM=PLATFORM_DESKTOP RAYLIB_LTYPE=SHARED RAYLIB_MODULE_RAYGUI=TRUE RAYLIB_MODULE_PHYSAC=TRUE
then I get the error gcc: error: raygui.c: No such file or directory
gcc: fatal error: no input files

how do i compile the library so it contains the raygui calls?

**Comment by orcmid** [comment]
Stop trying to compile a library.

Please read the `raygui.h` and `physac.h` files.  There is description in those files about how to include their functions directly in your application code or to make them externally accessed.  raylib is set up so that simply embedding the code of those functions in your application is easy, especially when your application is implemented in a single `.c` file. 

 If there are multiple `.c` files in your project, you need to choose which one compiles `raygui.h` and `physac.h` into its code and makes it reachable from any other of your project files.  There is documentation in the headers about such usage.

To make them into separate files that you can use as a link-time library, you need to make a `.c` file that includes those `.h` files, and then establish how to link the object code of that `.c` (which will contain the function implementations visible as externals to other files) as a library or not, whether part of a shared library or static library (easiest).  That is more involved.  Also, you need to understand the makefile for that better.

I recommend using the easy path first, then determine if it is actually important to have an externally-shared library along with the dependency management that will cost you.

**Comment by GuvaCode** [comment]
Yes, I need it all to be compiled in the library. it's for the headers in pascal.

That's why I'm asking how to do it right.

**Comment by raysan5** [comment]
@GuvaCode `raygui.c` is automatically generated by the Makefile (check lines 632):
```mk
# Compile raygui module
# NOTE: raygui header should be distributed with raylib.h
raygui.o : raygui.c
	$(CC) -c $< $(CFLAGS) $(INCLUDE_PATHS)
raygui.c:
	echo #define RAYGUI_IMPLEMENTATION > raygui.c
	echo #include "$(RAYLIB_MODULE_RAYGUI_PATH)/raygui.h" >> raygui.c
```
It could happen that the generation does not work for you, in that case, just create an empty `raygui.c` and copy:
```c
#define RAYGUI_IMPLEMENTATION
#include "raygui.h"
```
Only those two lines are required inside `raygui.c`.

**Comment by GuvaCode** [comment]
> 

Well that explains it almost in Russian :) 
Thank you !!!
