### ISSUE TITLE
[module] Raymath Version

### ISSUE THREAD

**Issue by leowribeiro** [raysan5/raylib#2294]
I donwloaded Raylib v4.0 from the red "Download Now" button on the start page of the "https://www.raylib.com/" website (the raylib_installer_v4.0.mingw.exe self extract executable) and I downloaded raylib from the GitHub repository (as a ZIP file) and I noticed a problem, both are supposed to be the 4.0 version however the "raymath.h" file that comes with the executable defines the function vector2angle as 

RMAPI float Vector2Angle(Vector2 v1, Vector2 v2){
    float result = atan2f(v2.y - v1.y, v2.x - v1.x)*(180.0f/PI);
    if (result < 0) result += 360.0f;
    return result;
}

which is wrong and the "raymath.h" file in the repository defines as 

RMAPI float Vector2Angle(Vector2 v1, Vector2 v2){
    float result = atan2f(v2.y, v2.x) - atan2f(v1.y, v1.x);
    return result;
}

Both files, in their headers, say that this is raymath version 1.5. What's going on?

**Comment by orcmid** [comment]
Well, the master branch on the repository is actually raylib 4.0-bis, and I guess that means raymath is 1.5-bis there because it is all under active development.

There should probably be some sort of management of version numbers to signify when something is under development and then when its version becomes a new stable.  

But mainly, master is always under development. 

I don't have a meaningful suggestion on how to distinguish that from a stable version corresponding to a release unless it would be to make a release branch.  That still leaves some murk around versions of individual components, such as `raymath.h`.

**Comment by raysan5** [comment]
@leowribeiro raylib current master branch is raylib 4.1-dev. `raymath.h` was updated recently but not the version number, it will be updated in next release.
