### ISSUE TITLE
Unable to build physics demo on Linux

### ISSUE THREAD

**Issue by kewp** [raysan5/raylib#232]
> gcc -o physics_demo physics_demo.c -O2 -s -Wall -std=c99 -I. -I../src -I../src/external -I../release/linux -I/usr/local/include/raylib/ -L. -L../src -L../release/linux -lraylib -lglfw3 -lGL -lopenal -lm -lpthread -ldl -lX11 -lXrandr -lXinerama -lXi -lXxf86vm -lXcursor -lpthread -DPLATFORM_DESKTOP 
> In file included from physics_demo.c:15:0:
> ../src/physac.h: In function ‘GetCurrentTime’:
> ../src/physac.h:1956:25: error: storage size of ‘ts’ isn’t known
>          struct timespec ts;
>                          ^~
> ../src/physac.h:1957:9: warning: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
>          clock_gettime(CLOCK_MONOTONIC, &ts);
>          ^~~~~~~~~~~~~
> ../src/physac.h:1957:23: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
>          clock_gettime(CLOCK_MONOTONIC, &ts);
>

**Comment by raysan5** [comment]
This issue was already corrected some days ago in commit https://github.com/raysan5/raylib/commit/c46989a1d961f3d8f898348e25c2b5b948ade9b2

Here it is the PR with more info https://github.com/raysan5/raylib/pull/230

Fix would be included in the upcomming raylib v1.7, in the meantime you can just implement the fix yourself or use develop branch instead.

**Comment by kewp** [comment]
I see. Will fix myself. Thanks.
