### ISSUE TITLE
[physac] Jump sticking in physics movement example

### ISSUE THREAD

**Issue by kewp** [raysan5/raylib#233]
Pressing up does not respond immediately (intermittent). Issue goes away when isGrounded check is removed on line 74.

> // Vertical movement input checking if player physics body is grounded
> if (IsKeyDown(KEY_UP) && body->isGrounded) body->velocity.y = -VELOCITY*4;

**Comment by raysan5** [comment]
I think this issue is related to sync between main game thread and physics thread. Probably @victorfisac, creator of `physac.h`, can provide further info.

**Comment by victorfisac** [comment]
Hi @kewp @raysan5

Yes. I realized about this issue and I couldn't find any solution by the moment. I think too it is related to sync due to physics thread is not limited and maybe the grounded state changes during loops while a physics object is "sleeping" in ground.

Dynamics are all time applying gravity and other forces and solving collisions to avoid colliders overlapping. I just check if any contacts normal is negative in Y axis to simulate grounding of a character.

The physics library I used as reference didn't implement any grounded state so I implemented it as I do in Unity 3D using 2d physics. Maybe I should improve the condition of normal.y value to set grounded state to true...

Any help is welcome!

**Comment by kewp** [comment]
This is strange. I added a print to the normals at the bottom of SolvePhysicsManifold (line 1347).

> // Update physics body grounded state if normal direction is downside
> manifold->bodyB->isGrounded = (manifold->normal.y < 0);
> if (manifold->bodyB->enabled) printf("%.2f\n",manifold->normal.y);

Instead of just negative ones (when leaving the block on the floor) I'm getting zeros as well, repeating 4x between.

http://oi66.tinypic.com/24l3ofn.jpg

That's strange, right ? Only the block is enabled in the scene.

Doesn't explain the intermittent hopping when holding up, though ...

**Comment by victorfisac** [comment]
I reviewed Physac and found the solution!

I was overwriting isGrounded value in each manifold solving. So when player-floor collision sets isGrounded to true, next manifold player-platform (not colliding) was changing isGrounded to false again and obviously manifold->normal.y to 0.0f. 

You can check that removing all colliders except floor and player and normal.y will be always -1.0f and player will jump as expected because there isn't any other physics body to overwrite the isGrounded value...

**Now isGrounded is reset to false before starting step dynamics and isGrounded value is calculated just when its value is false yet. I'm updating Physac repo and starting a pull request for raylib.**

**Comment by victorfisac** [comment]
Fixed in pull request #239

**Comment by kewp** [comment]
Tested on Windows. Works great (no more sticking when jumping).
