### ISSUE TITLE
[core] `IsKeyPressed()` does not work in the `custom frame_control` example on `PLATFORM_WEB`

### ISSUE THREAD

**Issue by thismarvin** [raysan5/raylib#2379]
### Issue description

The `IsKeyPressed` function does not work in the "custom frame_control" example on [raylib.com/examples](https://www.raylib.com/examples/core/loader.html?name=core_custom_frame_control). The circle's movement cannot be paused and the target fps cannot be modified. 

The example does work on Desktop; however, it appears that because of some quirk with emscripten, the example does not work on the Web. Adapting the code to use `emscripten_set_main_loop` also does not work.

### Environment

Web, Linux, 3.3.0 NVIDIA 510.54, NVIDIA GeForce GTX 1060

I would like to add that I have tested this on Firefox 98 and Microsoft Edge 99 beta

### Code Example

Make sure to build raylib with the `SUPPORT_CUSTOM_FRAME_CONTROL` flag enabled and to target `PLATFORM_WEB`.

``` c
#include "raylib.h"

int main(void)
{
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - custom frame control");

    double previousTime = GetTime();
    double currentTime = 0.0;
    double updateDrawTime = 0.0;
    double waitTime = 0.0;

    int targetFPS = 60;

    while (!WindowShouldClose())
    {
        PollInputEvents();

        if (IsKeyPressed(KEY_SPACE)) TraceLog(LOG_INFO, "Here!");

        BeginDrawing();
        ClearBackground(RAYWHITE);
        EndDrawing();

        SwapScreenBuffer();

        currentTime = GetTime();
        updateDrawTime = currentTime - previousTime;

        if (targetFPS > 0)
        {
            waitTime = (1.0f/(float)targetFPS) - updateDrawTime;
            if (waitTime > 0.0)
            {
                WaitTime((float)waitTime*1000.0f);
                currentTime = GetTime();
            }
        }

        previousTime = currentTime;
    }

    CloseWindow();

    return 0;
}
```

**Comment by thismarvin** [comment]
I am not sure if this is actually the best solution, but if anyone every runs into this in the future then just remember to call `PollInputEvents` after `IsKeyPressed` or else `IsKeyPressed` will always be false! 

You can read more about this in the comments of the closed pull request above.

**Comment by raysan5** [comment]
This issue requires further investigation as detailed in the closed PR: https://github.com/raysan5/raylib/pull/2380

----------------------------------------

It seems the issue is not the calling order but the `PollInputEvents()` implementation for `PLATFORM_WEB`. It seems the keyboard inputs are not polled when the function is called (missleading behaviour)... but mouse and gamepad inputs should work with original implementation.

This is probably related to `library_glfw,js` not polling the events as expected: https://github.com/emscripten-core/emscripten/blob/main/src/library_glfw.js#L20

At some point of frame-processing (Update/Draw) the DOM processes the input events (Mouse/Keyboard) and `KeyCallback()`/`Mouse*Callback)` are executed. For some reason, input values are not stored/reseted before `IsKeyPressed()` is called. I don't know why but moving the function to the end is not the solution, or at least not a solution originated from an understanding of the problem.

**Comment by jdoleary** [comment]
FWIW, I get this same behavior on desktop.  It works when I move PollInputEvents() to **after** GetKeyPressed or IsKeyPressed inside the loop.

**Comment by jdoleary** [comment]
I encountered the same issue on desktop.  Strangely, it fails to get key events when I have BeginDrawing occur within the loop but it operates as expected if there is no call to BeginDrawing.

So maybe it has something to do with the screen buffer like you mentioned [here ](https://github.com/raysan5/raylib/pull/2380#issuecomment-1077953356)

**Comment by raysan5** [comment]
@jdoleary Are you recompiling raylib using `SUPPORT_CUSTOM_FRAME_CONTROL`? It seems the behaviour you comment could result if that flag is not used...

**Comment by raysan5** [comment]
I'm not solving this issue. It seems it is out of domain for raylib, it depends on GLFW and DOM behaviour.

Hopefully this issue will serve as documentation for future adventures facing this issue.

**Comment by mrryanjohnston** [comment]
FWIW, I've found that if `IsKeyPressed` does not detect the key press, it's because I run `WindowShouldClose` *after* it. If I run `WindowShouldClose` *before* `IsKeyPressed`, the key press is detected.
