### ISSUE TITLE
[rlgl] MAX_QUADS_BATCH limit?

### ISSUE THREAD

**Issue by Triangle345** [raysan5/raylib#267]
There is a finite size of drawable quads. This would basically make a game crash without warning. Why does it exist?  Thinking maybe remove it as it may cause confusion on larger projects?

https://github.com/raysan5/raylib/blob/develop/src/rlgl.h#L107

**Comment by raysan5** [comment]
Actually, if MAX_QUADS_BATCH is reached, a warning message is output to console log... but the that value is just the maximum quads supported by raylib batching system to be processed in a single draw call, it means, if that limit is reached (my students never reached that limit), a draw call is launched and the buffer starts being filled again. What it means is that you can draw up to 50K quads if you want with no crash.

Finding the right size for the batch system is not easy because that data is uploaded to GPU every frame and it also requires some space on RAM and VRAM, just chosen a value I considered it could work on most scenarios (CPU, GPU, OS...).

In any case, if some advanced user wants to increase that value, it's just changing a value in rlgl.h. One of the key features of upcoming raylib v1.7 is a bunch of configuration flags to configure multiples aspects of the library, that's just one of them.

**Comment by Triangle345** [comment]
Thanks for the reply. I'm not sure where you got the the number 50k from. The code is this:

```
       // Verify that MAX_QUADS_BATCH limit not reached
                if (quads.vCounter/4 < MAX_QUADS_BATCH)
                {
                    quads.vertices[3*quads.vCounter] = x;
                    quads.vertices[3*quads.vCounter + 1] = y;
                    quads.vertices[3*quads.vCounter + 2] = z;

                    quads.vCounter++;

                    draws[drawsCounter - 1].vertexCount++;
                }
                else TraceLog(ERROR, "MAX_QUADS_BATCH overflow");
```

which gives a TraceLog ERROR, which is defaulted to abort.  However; if changed to not abort on ERROR, it would not draw anymore?

I also experimented with increasing this number and noticed that when number of quads is ~18k, any on screen Text just disappears?

**Comment by raysan5** [comment]
Hey @Triangle345, yes, you're right, but quad batch is reset in `rlDisableTexture()`: 

```c
// Disable texture usage
void rlDisableTexture(void)
{
#if defined(GRAPHICS_API_OPENGL_11)
    glDisable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, 0);
#else
    // NOTE: If quads batch limit is reached,
    // we force a draw call and next batch starts
    if (quads.vCounter/4 >= MAX_QUADS_BATCH) rlglDraw();
#endif
}
```

About batch size limit (~18K) it seems related to max number of indexes supported, I was investigating it in the past and so I added the code provided above... actually, I tried a bunnymark and reached about 50K quads drawn.

**Comment by raysan5** [comment]
Mmmm... I see that if you are only drawing with plain color quads, I mean not changing from base white texture, then probably that code point is reached and batch system is not reseted... need to check it!

**Comment by raysan5** [comment]
Just checked it, if used OpenGL 3.3, when `MAX_QUADS_BATCH` is reached, a draw call is launched and buffer starts being filled again.

`MAX_QUADS_BATCH` refers to max number of quads per draw call. Despite that, if `MAX_QUADS_BATCH` is too big it will cause stalls on rendering, dropping frame rate, because it takes some time to upload next draw data to GPU (quads buffer is a dynamic buffer). One solution to those stall would be using a double or triple buffering system, increasing the internal complexity of the library.

For the moment I would leave it as it is.
