### ISSUE TITLE
[rcore] Having Caps-Lock or Num-Lock on locks all pressed keys down

### ISSUE THREAD

**Issue by masterex1000** [raysan5/raylib#2718]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

If you have num lock or caps lock enabled it'll "lock" whatever keys you press to be down, until you disable num/caps lock and press the key again.

It looks like this issue was introduced in a recent commit (ea87491a82a0fc778056d1538d37ec851e8e0fbe), since commenting out line 5273 of rcore.c (introduced in that commit) fixes the issue.

I'm not sure what the point of that commit is, otherwise I'd try to give a fix as well. 

### Code Example

```c
if(isKeyDown(KEY_Q)
    printf("Down\n");
else
    printf("Not Down\n");

// After pressing "q" once with caps/num lock on "Down" will keep printing, even after you release it.
```

**Comment by raysan5** [comment]
@masterex1000 My bad, just fixed the issue.

 > I'm not sure what the point of that commit is

The point of that commit is being able to detect if CAPS/NUM lock keys are enabled. Those two special keys behave different than the other keys because they work like sticky-keys, once pressed they get stuck and that state should be detected. Now raylib can detect it with this fix.

I'm aware it's a bit hacky solution and could imply other issues, let's see if someone complains about it...
