### ISSUE TITLE
Examples build but don't run on Windows

### ISSUE THREAD

**Issue by kewp** [raysan5/raylib#272]
The .exes get generated fine but nothing happens when I run them.

> c:\raylib\raylib\examples>mingw32-make PLATFORM=PLATFORM_DESKTOP
gcc -o core_basic_window core_basic_window.c -O2 -s -Wall -std=c99 -I. -I../src -I../src/external -I../release/win32/mingw32 -I../src/external/glfw3/include -I../src/external/openal_soft/include -L. -L../src -L../release/win32/mingw32 -L../src/external/glfw3/lib/win32 -L../src/external/openal_soft/lib/win32 -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32dll -DPLATFORM_DESKTOP ../src/resources -Wl,--subsystem,windows

**Comment by raysan5** [comment]
Have you tried to compile one example individually with Notepad++ `compile_and_execute` script? What GPU do you have? How old is it?

**Comment by kewp** [comment]
I can't find where the notepad scripts are, or how to run them. Plugins ?

I have an old m14 alienware laptop. Graphics card is a Geforce GT 555M.

**Comment by kewp** [comment]
Oh I see. F6. I ran it. Still nothing comes up.

> > Setup required Environment
-------------------------------------
SET: RAYLIB_DIR = C:\raylib
$(RAYLIB_DIR) = C:\raylib
ENV_SET: PATH=C:\raylib\MinGW\bin
$(SYS.PATH) = C:\raylib\MinGW\bin
CD: C:\raylib\raylib\examples
Current directory: C:\raylib\raylib\examples

NOTE: raylib uses OpenAL Soft library compiled statically and linked into the executable

> Cleaning latest build
---------------------------
cmd /c IF EXIST core_basic_window.exe del /F core_basic_window.exe
Process started >>>
<<< Process finished. (Exit code 0)

> Compiling program
-------------------------
gcc -o core_basic_window.exe core_basic_window.c -s C:\raylib\raylib\raylib_icon -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,--subsystem,windows -Wl,-allow-multiple-definition
Process started >>>
<<< Process finished. (Exit code 0)

> Reset Environment
--------------------------
ENV_UNSET: PATH
$(SYS.PATH) has been restored

> Executing program
-------------------------
cmd /c IF EXIST core_basic_window.exe core_basic_window.exe
Process started >>>
<<< Process finished. (Exit code -1073741819)
================ READY ================

**Comment by kewp** [comment]
Is there a way to compile with verbose debugging logged to the console ?

**Comment by raysan5** [comment]
Hi @kewp, that `Exit code` doesn't look good... 

Your GPU is ok, it supports OpenGL 3.3 (actually, it supports OpenGL up to 4.5), so it should work...

When compiling just delete `-Wl,--subsystem,windows` compilation parameter to show console output and let me know what info do you get.

**Comment by kewp** [comment]
Here's the output

> C:\raylib\raylib\examples>core_basic_window
INFO: Initializing raylib (v1.6.0)
WARNING: [GLFW3 Error] Code: 65543 Decription: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable

**Comment by raysan5** [comment]
Ok, I see, the problem is that an OpenGL 3.3 Core context can not be created, it's not supported by the GPU. I investigated a bit about your Alienware M14x and it seems it comes with two GPUs, the NVIDIA GeForce GT 555M (a very good GPU) and an Intel HD 3000 (a not that good GPU, only supports up to OpenGL 3.1). It seems that system can change automatically from one GPU to the other depending on the program requirements but I bet it's not changing in your laptop, raylib program tries to run using Intel HD 3000.

Don't know exactly how to solve this issue, is it possible to force NVIDIA GPU usage? Are you using latest GPU drivers?

One solution is recompiling raylib sources to use OpenGL 1.1 or 2.1, it can be done automatically using one of the scripts provided in Notepad++. More info: https://github.com/raysan5/raylib/wiki/FAQ

Please, let me know if it works.

**Comment by kewp** [comment]
Worked great. I recompiled to gl21. Nice one. Should have picked that up.

**Comment by raysan5** [comment]
Great to read that! :D

Just in case, I found this: http://forum.notebookreview.com/threads/manually-switch-to-nvidia-graphics-m14x-r2.683706/
