### ISSUE TITLE
[question] How i compile raylib with msvc

### ISSUE THREAD

**Issue by susyboy23** [raysan5/raylib#2758]
so, i was triying to compile raylib with visual studio 2019, and it have me some external linking errors, some one have a clue how to fix this?

![image](https://user-images.githubusercontent.com/89088882/195957351-65ebc5b6-4a21-4f4b-a88e-7a22c35be99d.png)

**Comment by orcmid** [comment]
The problem seems to be in `raylib.lib`.

Have you looked in the `raylib\projects\VS2022\` folder for Visual Studio solutions and examples?  Those should work with VS2019.  If you get one of those to compile and run, you should be able to scavenge from one of the examples to build your own project.

PS: Use one of the release sources available on GitHub.  These should be more stable and suitable for getting started.

**Comment by raysan5** [comment]
@susyboy23 provided VS2022 preconfigured project should work ok.
