### ISSUE TITLE
[audio] MSVC Build error : Cannot open include file: 'stdalign.h': No such file or directory

### ISSUE THREAD

**Issue by clibc** [raysan5/raylib#2762]
Here is the error I get when I run ```build-windows.bat``` in raylib/projects/scripts.
```
W:\RaylibThing>build-windows.bat -c
COMPILE-INFO: Compiling in release mode, flags: /std:c11 /O1 /GL /favor:blend /utf-8 /validate-charset /EHsc /link /LTCG
COMPILE-INFO: Found cached raylib, rebuilding.
RAYLIB_SRC
rcore.c
rshapes.c
rtextures.c
rtext.c
rmodels.c
utils.c
raudio.c
C:\raylib\raylib\src\external/miniaudio.h(3894): fatal error C1083: Cannot open include file: 'stdalign.h': No such file or directory
rglfw.c
```

**Comment by raysan5** [comment]
@clibc It seems this issue is related to the C compiler that does not provide the required library for C11 compilation.

You should try updating/changing the compiler. You can also try compiling with `/std:c99` instead of `/std:c11`.

**Comment by orcmid** [comment]
@raysan5 
> @clibc It seems this issue is related to the C compiler that does not provide the required library for C11 compilation.
> You should try updating/changing the compiler. You can also try compiling with `/std:c99` instead of `/std:c11`.

It's even more complicated than that.   
https://learn.microsoft.com/en-us/cpp/standard-library/cstdalign?view=msvc-170

This problem does not happen with Visual Studio 2022 Build Tools and that script in raylib release 3.7.0.  I will dig a little farther.  As far as I can tell off-hand, `stdalign.h` is not included in any MSVC libraries because of the C++ keyword conflict.

**Comment by orcmid** [comment]
@raysan5 @clibc 

Here's a build with my adaptation of `build-windows.bat` building for x64.  Note that `std:c11` must be used because of `struct` cases that are used in raylib and that are not supported in C99.

Although not shown in the replay of parameter options on the console, the raylib `*.obj` cache is compilied with options `/w /c` and the game file is compiled with options `/w3 /c`.  The difference is to avoid a flood of annoying warnings about slack bytes/alignment with raylib `struct` declarations on x64.  

The important thing is to see what the other parameters are and how the compiles and linking worked with the VS2022 VC x64 developer prompt.  This is all with raylib source for version 3.7.0.  I will use the latest release of raylib version 4 and see what happens.

```
 [VCrayApp] 0.0.0 BUILDING RAYLIB APP WITH VC/C++ TOOLS
          10:05:31.96 2022-10-17 on orcmi's ASTRAENDO2
          VCrayApp.bat at H:\Documents\GitHub\nfoTools\devKits\WinDev\VCrayApp\dev\
Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl /utf-8 /validate-charset /TC /EHsc
   /std:c11 /O1 /GL /favor:blend
   /I"..\..\raylib\src" /I"..\..\raylib\src\external\glfw\include"
   /D_DEFAULT_SOURCE /DPLATFORM_DESKTOP /DGRAPHICS_API_OPENGL_33
   /D_CRT_SECURE_NO_WARNINGS
   "..\..\raylib\src\core.c" "..\..\raylib\src\shapes.c"
   "..\..\raylib\src\textures.c" "..\..\raylib\src\text.c"
   "..\..\raylib\src\models.c" "..\..\raylib\src\utils.c"
   "..\..\raylib\src\raudio.c" "..\..\raylib\src\rglfw.c"

core.c
shapes.c
textures.c
text.c
models.c
utils.c
raudio.c
rglfw.c
 [VCrayApp] FRESH CACHE OF RAYLIB *.OBJ FILES COMPILED

Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl /utf-8 /validate-charset /TC /EHsc
   /std:c11 /O1 /GL /favor:blend
   /I"..\..\raylib\src" /I"..\..\raylib\src\external\glfw\include"

rayConfirm.c

Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl ..\cache\*.obj *.obj
   kernel32.lib user32.lib shell32.lib winmm.lib gdi32.lib opengl32.lib

Microsoft (R) Incremental Linker Version 14.32.31332.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:rayConfirm.exe
/LTCG
/SUBSYSTEM:WINDOWS
/ENTRY:mainCRTStartup
..\cache\*.obj
*.obj
kernel32.lib
user32.lib
shell32.lib
winmm.lib
gdi32.lib
opengl32.lib
Generating code
Finished generating code

 [VCrayApp] RAYLIB-USING rayConfirm.exe COMPILED TO H:\Documents\GitHub\nfoTools\devKits\WinDev\VCrayApp\dev\app


Press any key to continue . . .
```

**Comment by orcmid** [comment]
Here is the Visual Studio 2022 VC command-line x64 compile with my VCrayApp script and raylib release 4.2.0 after I corrected the source file names for creating the `*.obj` cache.

```
 [VCrayApp] 0.0.0 BUILDING RAYLIB APP WITH VC/C++ TOOLS
          11:16:00.13 2022-10-17 on orcmi's ASTRAENDO2
          VCrayApp.bat at H:\Documents\GitHub\nfoTools\devKits\WinDev\VCrayApp\dev\
Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl /utf-8 /validate-charset /TC /EHsc
   /std:c11 /O1 /GL /favor:blend
   /I"..\..\raylib\src" /I"..\..\raylib\src\external\glfw\include"
   /D_DEFAULT_SOURCE /DPLATFORM_DESKTOP /DGRAPHICS_API_OPENGL_33
   /D_CRT_SECURE_NO_WARNINGS
   "..\..\raylib\src\rcore.c" "..\..\raylib\src\rshapes.c"
   "..\..\raylib\src\rtextures.c" "..\..\raylib\src\rtext.c"
   "..\..\raylib\src\rmodels.c" "..\..\raylib\src\utils.c"
   "..\..\raylib\src\raudio.c" "..\..\raylib\src\rglfw.c"

rcore.c
rshapes.c
rtextures.c
rtext.c
rmodels.c
utils.c
raudio.c
H:\Documents\GitHub\nfoTools\devKits\WinDev\VCrayApp\raylib\src\external/miniaudio.h(3894): fatal error C1083: Cannot open include file: 'stdalign.h': No such file or directory
rglfw.c
 [VCrayApp] ****FAIL: COMPILING CACHE OF RAYLIB FILES FAILED ****
            Review the errors reported for the compilation.
            Make repairs and reattempt.
            RESULTS ARE UNPREDICTABLE


Press any key to continue . . .
```
It strikes me that having that in `miniaudio.h` is a mistake with respect to `raudio.c` dependency, but that needs more exploration.

**Comment by orcmid** [comment]
The problem is a mistake in `miniaudio.h` lines 3893-3907.  The `#include <stdalign.h>` is done whenever the `__STDC_VERSION__` variable is larger than `201112L`.  A way to fix it is to add

```
&&  !defined(_MSC_VER)
```
to line 3893.  Then the `#include` will never be attempted with Visual Studio and VC and the `#else` case will work.

(However, my compiled sample program cannot now be executed for some reason that I suspect has nothing to do with `raudio.c`.  I suspect it is related to linking.)

**Comment by orcmid** [comment]
I have confirmed the change to `miniaudio.h` after having to reinstall my VS 2022 Build Tools for some other reason.  

I get clean compiles of `raudio.c` and my example file compiles and runs as expected.

It's interesting that the commentary in `miniaudio.h` confesses that the alignment adjustment is not necessary although there can be slight performance improvements in some cases.  This should not be a raylib concern.

**Comment by orcmid** [comment]
@clibc I have confirmed that the just-released `miniaudio.h` version 0.11.10 repairs the `#include <stdalign.h>` defect.  You can manually introduce it into `raylib/src/external`, revert to raylib-4.0.0, or wait for a new raylib release beyond 4..2.0.
