### ISSUE TITLE
Lack of tests

### ISSUE THREAD

**Issue by JosephSBoyle** [raysan5/raylib#2782]
### Issue description
There are a lack of tests for the functionality contained in raylib, which acts as a barrier to refactoring and improving the quality of the code, as well as adding new features. 

I would be happy to help write some basic unit tests - is this a direction that the project is interested in?

Additionally, what would be the mechanism for running these tests - would it be `Make`?

**Comment by raysan5** [comment]
@JosephSBoyle I'm aware of that and actually, the examples are used as unit tests for the functionality provided.

I'm not interested in following another direction.

**Comment by JosephSBoyle** [comment]
@raysan5 May I ask why you're not interested in supporting tests in this project? To me it seems like an obvious enhancement but I'm interested in your thoughts on this.

**Comment by raysan5** [comment]
@JosephSBoyle Because I'm the only long-term maintainer of the project and I can't assume more work. Maintaining a unit tests system requires lot of work and an increment in the project complexity.

I also think raylib won't benefit that much of unit tests, a prove of that is that it did not required them for the last 9 years and afair, nobody asked for them in that time.

**Comment by chriscamacho** [comment]
unit tests, a great way to find bugs you can think of - shame most bugs are usually things you don't think about...
