### ISSUE TITLE
[core] GLFW: Error: 65539 Description: Invalid window hint 0x0002000D

### ISSUE THREAD

**Issue by lucaiyu** [raysan5/raylib#2873]
### Issue description

When init raylib and create a window, it log a warning "WARNING: GLFW: Error: 65539 Description: Invalid window hint 0x0002000D".
but it doesn't crash and doesn't make any trouble in my program.

### Environment

linux-amd64
OpenGL 3.3 (glsl 330)
AMD Radeon Graphics

### Issue Screenshot

`Fri Jan 20 16:43:14 2023`
`[INFO] Initializing openstg engine`
`WARNING: GLFW: Error: 65539 Description: Invalid window hint 0x0002000D`
`Fri Jan 20 16:43:15 2023`
`[INFO] Initializing stages`
`Fri Jan 20 16:43:15 2023`
`[INFO] Loading resources`
`Fri Jan 20 16:43:15 2023`
`[INFO] resources loaded`
`Fri Jan 20 16:43:15 2023`
`[INFO] Loading stage01`
`Fri Jan 20 16:43:25 2023`
`[INFO] Unloading resources`
`Fri Jan 20 16:43:25 2023`
`[INFO] Cleanup successfully`

### Code Example

`    SetTraceLogLevel(LOG_WARNING);`
`    logStr("Initializing openstg engine\n", INFO);`
`    InitAudioDevice();`
`	InitWindow(640,480,"STG");`
`	SetTargetFPS(60);`

**Comment by raysan5** [comment]
@lucaiyu This issue is probably related to using an external/old GLFW version instead of the statically version compiled inside raylib. That window hint value is defined as `GLFW_MOUSE_PASSTHROUGH` and it's provided in latest GLFW version on GitHub master branch, not officially released yet.

In any case, you can just ignore that warning.
