### ISSUE TITLE
Overloading Operators such as = allowing for Vector3 + Vector3 

### ISSUE THREAD

**Issue by Kerbal-Man** [raysan5/raylib#3011]
the title is all u need tbh like litteraly i just made a header file and put

```cpp
Vector3 operator+(const Vector3& a, const Vector3& b) {
    Vector3 result;
    result.x = a.x + b.x;
    result.y = a.y + b.y;
    result.z = a.z + b.z;
    return result;
}
```
but like 100x more for like Vector2 and Vector4 with +, -, /, * and i also did it with offsets, so adding an int to each element and also done with scalar and other random stuff 

RIP grammar spelling and punctuation

**Comment by orcmid** [comment]
@Kerbal-Man I presume you are doing that in C++.  It does not seem to be valid C language.  I tried it with VC/C++ with `/std:c11` option and both the compiler and Visual Studio Code (with Intellisense) reported problems.

Unless there have been some extreme changes to the C Language standard, I would not expect `operator` to work.  It might be a fun challenge to optimizers though.

**Comment by raysan5** [comment]
@Kerbal-Man I'm afraid C does not support operators overloading.

**Comment by orcmid** [comment]
I added this case to my collection of test cases that I use for a raylib app devkit that I use in support of VC/C++.  I since changed my version of the definition of Vector3 "+" overloading.  I think it is interesting for two reasons.
![FAIL5-2023-04-19-0844-operator c-VCrayApp-0 1 0](https://user-images.githubusercontent.com/3372580/233269577-cd6b838e-91d1-48ad-b21c-556c84ca2da0.png)

First, Virtual Code Intellisense flags the "+" as erroneous.  Without it, the code is a perfectly valid C Language definitions for a function named "operator."  It also found everything else correct.

The second difference is the use of a simple functional expression.  These are inline functions and maybe a declared result variable is optimized away.  Just the same, I prefer straightforward cases.  This is not a case of raylib style though.  

Not only is that my preference.  When I typed the "return", the GitHub Copilot AI suggested the rest of  the line as a kind of command completion.  I accepted it with a smile.
