### ISSUE TITLE
[core] Rename `WindowShouldClose` to `IsWindowClosing`

### ISSUE THREAD

**Issue by wmentha** [raysan5/raylib#3038]
Following on from #1226, `WindowShouldClose` returns a bool and should be consistently renamed with other functions in the library that return a bool by prefixing it with `Is` like `IsWindowClosing`. Currently, the naming is confusing.

I see it is following the naming from a [function in GLFW](https://www.glfw.org/docs/3.3.8/group__window.html#ga24e02fbfefbb81fc45320989f8140ab5) where it [simply returns the close flag for the window](https://github.com/glfw/glfw/blob/3fa2360720eeba1964df3c0ecf4b5df8648a8e52/src/window.c#L500).

I recognize this can break code, so this could by a TODO for a future major raylib release (5?).

If this isn't a good name for the function or I'm misunderstanding what the function does, I apologize.

**Comment by raysan5** [comment]
@wmentha I agree that funtion is not consistent with the naming conventions but unfortunately at this point it is used in thousands of codebases, so, changing it will break lot of code. I'm afarid we should live with it...

**Comment by orcmid** [comment]
I also think the proposed alternative is not quite apt.  `IsWindowsClosing` suggests agency outside of the program, rather than the program is being signalled to close the window (from perspective of the app).  I suppose the problem is that it could be a forced close (the big X) or a requested close (ESC).  But what is called for is the same in either case: stop drawing, establish a clean state, and exit quickly.
