### ISSUE TITLE
[build] Cannot run Linux build on older GLIBC

### ISSUE THREAD

**Issue by vtereshkov** [raysan5/raylib#3046]
When linking against the Raylib 4.5 library, I get the following error messages:
```
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `pthread_attr_setstacksize@GLIBC_2.34'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `dlclose@GLIBC_2.34'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `dlsym@GLIBC_2.34'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `fstat@GLIBC_2.33'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `stat@GLIBC_2.33'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `pthread_key_delete@GLIBC_2.34'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `pthread_setspecific@GLIBC_2.34'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `pthread_create@GLIBC_2.34'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `pthread_join@GLIBC_2.34'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `pthread_getspecific@GLIBC_2.34'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `hypotf@GLIBC_2.35'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `hypot@GLIBC_2.35'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `pthread_key_create@GLIBC_2.34'
/usr/bin/ld: /home/vtereshkov/umka-lang/umka_linux/examples/3dcam/libraylib.so: undefined reference to `dlopen@GLIBC_2.34'
```
I have Ubuntu 20.04.2 LTS with GLIBC 2.31.

**Comment by raysan5** [comment]
@vtereshkov Did you try building raylib yourself against GLIBC?

**Comment by bztsrc** [comment]
This isn't a raylib issue, rather a well-known (and hated) problem with glibc.

It's not just raylib, many many other projects suffer from this versioning non-sense too. The proper solution would be to compile glibc with canonical symbol names (all these functions like `pthread_attr_setstacksize`, `dlopen`, `fstat` etc. are part of the POSIX standard, so their ABI/API simply *not* allowed to change, no matter the version). But glibc devs are deaf to reasoning and users complaining (google "glibc versioned symbol issue", you'll find thousands and thousands of results, an armada of users suffering because of this stupidity). [Further reading](https://harmful.cat-v.org/software/dynamic-linking/versioned-symbols).

The only workaround I've seen so far involves an assembler (even though there's no actual Assembly in the source, only the .S source files can create such [versioned symbol aliases](https://sourceware.org/binutils/docs/as/Symver.html)), so this isn't portable at all (and incompatible with emscripten for example). And even then, one would have to list ALL glibc versions for ALL linked functions... So this isn't a viable workaround by any means, much less a proper solution. I'd totally understand if @raysan5 wouldn't want to implement this messy workaround.

If you can, try switching to [musl](https://musl.libc.org/), which is free of this symbol naming madness. As for glibc, you'll have to compile raylib yourself (using your system's glibc version), there's no other solution.

Hope this helps,
bzt

**Comment by orcmid** [comment]
@bztsrc I would think that the distinction between POSIX and ISO Standard C (and C++) is also a problem.  

It's a bit startling to me that [(IEEE) POSIX](http://get.posixcertified.ieee.org/) was updated as recently as 2016 (POSIX 1003.1).  I have no idea what the impact on the C Language librraries happened to be.  

One curiosity is that some libraries include POSIX string functions that are not part of ISO Standard C.   That's why `strings.h` is around to grab those additional POSIX functions.  As was noticed over on miniaudio, 'strings.h` doesn't do anything in some libraries because those functions have been included in `string.h`.  So it becomes documentation of a dependency although not very reliably.  The [deprecation](https://stackoverflow.com/questions/4291149/difference-between-string-h-and-strings-h) in favor of `memcpy` and the like is a bit iffy though (at least if you want to maintain a slightly-higher level of abstraction in your code)., apart from the likely use of hardware acceleration.  I'd leave that to the functions and however they might be inlined these days.

**Comment by bztsrc** [comment]
@orcmid

> I would think that the distinction between POSIX and ISO Standard C (and C++) is also a problem.

No, not really (okay, granted, in general functions that only exists in certain POSIX versions could be an issue for portability, but not in this case, raylib does not use anything "tricky", just the basic stuff).

> It's a bit startling to me that [(IEEE) POSIX](http://get.posixcertified.ieee.org/) was updated as recently as 2016 (POSIX 1003.1). I have no idea what the impact on the C Language librraries happened to be.

Nothing. Even if POSIX changes, that can't change ISO C, nor the functions it imports from that spec, because [the former is a *superset* of the latter](https://www.gnu.org/software/libc/manual/html_node/POSIX.html) standard. You can't change a spec in retrospect, much less another spec you rely on.

Not that this matters, because these functions' interface hasn't changed, well, never ever since standardization. And indeed, musl has proven IRL that not just an ISO C compliant libc.so can, but even a POSIX compliant libc.so works fine without these crazy symbols. If anything it sucks much much (much) less.

Anyway, this is a libc problem that surely can't be solved on raylib's side, of that I'm certain. It's not realistic to expect @raysan5 to provide raylib shared libs for *every possible glibc* versions and libc implementations; so the only option for @vtereshkov is to re-compile raylib using the exact libc version his system has (or maybe reinstall to a different distro that ships the latest glibc).

Cheers,
bzt

**Comment by vtereshkov** [comment]
@bztsrc A realistic option for @raysan5 would be to build raylib on a sufficiently old Linux version (not on every possible version). This is similar to what we have done, for example, with the latest releases of [Umka](https://github.com/vtereshkov/umka-lang) and [Tophat](https://tophat2d.dev/). But if this old version is unavailable to @raysan5, I'll have to rebuild raylib myself. Hope this is not very difficult.

**Comment by raysan5** [comment]
@bztsrc thanks for all the details on this issue, I was not aware of that situation.

@vtereshkov I think the best solution is to build raylib yourself for your specific platform, actually, I recommend all raylib users to do so, always.

**Comment by bztsrc** [comment]
> build raylib on a sufficiently old Linux version (not on every possible version).

Yes, you're right about that, but see below. (Full disclosure, I have a project that has to work on lots of platforms, and I'm too using an old Ubuntu to compile it like you said for the reason you said).

> But if this old version is unavailable

The raylib release is compiled against the latest long-term-supported Ubuntu version, which I think is a pretty reasonable choice.

> the latest releases of Umka and Tophat.

Wow, nice projects you have! I've just implemented a C and a BASIC compiler and bytecode vm for my [fantasy console](https://bztsrc.gitlab.io/meg4/), so I can tell how much work you put into Umka! Well done!

> I'll have to rebuild raylib myself. Hope this is not very difficult.

No it's not, raylib's build environment is very good and easy to use, the dependencies are already included in the repo so it just works like a charm! To quote Mando, "This is the way" ;-)

> thanks for all the details on this issue, I was not aware of that situation.

Don't mention, you're welcome!

Cheers,
bzt
