### ISSUE TITLE
[rmodels] M3D incorrect material and mesh count

### ISSUE THREAD

**Issue by DaveH355** [raysan5/raylib#3177]
### Issue description

I loaded the model below as m3d and printed out the material and mesh counts
(the two meshes here share the same material)
![model](https://github.com/raysan5/raylib/assets/101005658/fd1b3fd4-4952-46c0-be78-c2be26d51078)

I expected 
 - Mesh count: 2
- Material count: 2 (+1 because of the default material)

but got this for m3d
- Mesh count: 1
- Material count: 1

Here's the code in question
https://github.com/raysan5/raylib/blob/22895ba14fab982ca74ec1526b48b924d1174e60/src/rmodels.c#L5586-L5597

**Comment by raysan5** [comment]
@DaveH355 I'm afraid that issue could be related to how the format is exported from the creation program or related to the M3D loading library by the creator of the format.

**Comment by DaveH355** [comment]
I'm not sure I understand. You can see in the m3d loading code that `model.materialCount ` is always 1 less than what is actually allocated to `model.materials`

**Comment by raysan5** [comment]
@DaveH355 Sorry, you are right, something strange seems to be in that code...

**Comment by raysan5** [comment]
@bztsrc please, could you take a look to this issue?

**Comment by bztsrc** [comment]
One more thing, not sure how you created the model, but the Blender exporter as well as the CLI converter optimizes the meshes and the materials. It will re-arrange and merge multiple meshes whenever possible to minimize the number of material switch for better performance. The CLI converter also does optimizations for opacity, so that when you display the mesh alpha will correctly handled without extra code.

**Comment by DaveH355** [comment]
@bztsrc The problem seems to be the `model.materialCount` field itself. It is not being incremented to account for the default material.

**Comment by raysan5** [comment]
@DaveH355 Reviewing the code again I think it's actually correct. There is not always a default material, there is ONLY a default material if no material is provided with the model. If a material is provided, then there is no need for a default material.

Maybe you got 1 mesh and 1 material loaded because Blender exporter actually optimizes meshes and materials.

**Comment by DaveH355** [comment]
@raysan5 I understand the Blender exporter optimizes meshes which would result in the 1 mesh count, but the material count is still off.

I ran the test below on different models including the ones from https://bztsrc.gitlab.io/model3d/
In the tests it showed index 0 is always the default material, even on models I knew had 1 material. 
```c
  Model model = //Load model
  TraceLog(LOG_INFO, "Material Count: %i", model.materialCount);
  TraceLog(LOG_INFO, "Mesh Count: %i", model.meshCount);

  Material *material = &model.materials[0];

  int isDefaultMaterial =
      material->maps[MATERIAL_MAP_DIFFUSE].texture.id ==
          rlGetTextureIdDefault() &&
      material->shader.id == rlGetShaderIdDefault() &&
      ColorToInt(material->maps[MATERIAL_MAP_DIFFUSE].color) ==
          ColorToInt(WHITE) &&
      ColorToInt(material->maps[MATERIAL_MAP_SPECULAR].color) ==
          ColorToInt(WHITE);

  TraceLog(LOG_INFO, "Is the first material the default material? %s",
           isDefaultMaterial ? "true" : "false");
```

Sidenote: 
Taking a look at the GLTF loader, it seems to correctly increment the material count to include the default material.

**Comment by bztsrc** [comment]
Here's the diff:
```diff
-            model.meshCount = model.materialCount = 1;
+            model.meshCount = 1; model.materialCount = 0;
            TRACELOG(LOG_INFO, "MODEL: No materials, putting all meshes in a default material");
        }
+        model.materialCount++;

        model.meshes = (Mesh *)RL_CALLOC(model.meshCount, sizeof(Mesh));
        model.meshMaterial = (int *)RL_CALLOC(model.meshCount, sizeof(int));
-        model.materials = (Material *)RL_CALLOC(model.materialCount + 1, sizeof(Material));
+        model.materials = (Material *)RL_CALLOC(model.materialCount, sizeof(Material));
```
This is all the modification needed. However this will always report a material even if there's no material in the model (which I believe isn't correct).

(Note: we must always add the default material because even if a model has materials, it's not guaranteed that all meshes are assigned to a material. Maybe some have vertex colors only, or maybe their referenced material cannot be found etc.)

Cheers,
bzt

**Comment by bztsrc** [comment]
I've added this modification too to the fix in https://github.com/raysan5/raylib/issues/3109

Cheers,
bzt
