### ISSUE TITLE
[text] How to change default fonts

### ISSUE THREAD

**Issue by msmshazan** [raysan5/raylib#322]
I want to change the font so that I can use drawtext without using drawtextex

**Comment by raysan5** [comment]
That option is not available at this moment. Why not using `DrawTextEx()`? 

You can also just create your own `DrawTextB()`:
```c
SpriteFont myfont;    // Global variable, initialize at beginning.

void DrawTextB(const char *text, int posX, int posY, int fontSize, Color color)
{
    DrawTextEx(myfont, text, (Vector2){ posX, posY }, myfont.baseSize, 1, color);
}
```

**Comment by msmshazan** [comment]
So what about implementing it? 
I was wondering if I made a modified raylib library what should I do to use it should I make its code public or something.

**Comment by raysan5** [comment]
> I was wondering if I made a modified raylib library what should I do to use it should I make its code public or something.

You can do it, you can send back changes if you want.

I can consider implementing 
```c
void SetDefaultFont(SpriteFont font);
```

**Comment by raysan5** [comment]
After some thinking I decided not to implement this function, same result could be obtained quite easy with a custom function.

**Comment by Boyfinn** [comment]
> After some thinking I decided not to implement this function, same result could be obtained quite easy with a custom function.

Please reconsider. I have a lot of DrawText calls across my project for debugging purposes, and for that I find the default font to be a bit too chunky. It would be really useful to have a built in way to override the default font so that I don't have to keep a reference to custom debugging fonts every time I want to call DrawText...

**Comment by TrueSgtMonkey** [comment]
It is bad design to force specifying font for each draw call instead of a one-time setting. Seems to be a waste of resources as well as forcing people to cast to a Vector2 in order to send positions.

Also, it is strange that DrawTextEx() uses completely different parameters than DrawText():

<img width="560" height="460" alt="Image" src="https://github.com/user-attachments/assets/7773cf97-8437-4789-9771-4af58ced0df6" />
vs
<img width="544" height="384" alt="Image" src="https://github.com/user-attachments/assets/a32e48ec-5689-4032-8c47-29439e991b28" />
