### ISSUE TITLE
[rlgl] RL_DEFAULT_BATCH_MAX_TEXTURE_UNITS is unreasonably low

### ISSUE THREAD

**Issue by Not-Nik** [raysan5/raylib#3252]
Currently the default limit is 4, but OpenGL requires at least 16 texture units to be available for each stage (since at least 3.0, couldn't find information on earlier versions). This unnecessarily restricts rendering, explicitly for deferred pipelines, where screen quads with multiple textures would be drawn, without use of the `Model` struct (which afaik is the only way to use more than 4 textures currently).

**Comment by raysan5** [comment]
This limit is for the batching system and actually, personally I never required more than 1, just added the option for advance users. In any case, if you need more feel for your specific use case, you have the define for customization.

**Comment by Not-Nik** [comment]
In that case can we make these defines customizable at built time? I'm building a library on top of raylib and I can't just change a line in config.h

**Comment by raysan5** [comment]
@Not-Nik I don't understand, I always configure raylib for my needs for all my tools using `config.h`, why is it not an option?

Allowing configuration at runtime will require a complete redesign of the system.

Still, I can't see why is so dramatic this limitation, what is the specific use case? Keep in mind that this limit only applies to the internal batch system, when using Model/Meshes that limitation does not exist. Maybe I'm not understanding the issue properly.

**Comment by Not-Nik** [comment]
There is no need for runtime configuration, but right now there is no way to set this limit apart from changing the source. All I ask is that we check if the limit is defined before forcibly setting it, similarly to how it already is with the OpenGL version.

**Comment by Not-Nik** [comment]
Ok, I looked a bit more into the code, and I oversaw that rlgl doesn't even use `config.h` and it checks whether the limit is set, so I can easily just set it in CMake. The question now is why the limit is defined again in `config.h`

**Comment by orcmid** [comment]
Well, `config.h` is conditionally included in a number of files; there is no dependence on CMake being used or not in those cases.

Also, where `# include "rlgl.h"` is done, as in `rcore.c`, there is a conditional `#include "config.h"` before it.

I think the whole idea, is for customized `config.h` files.  That could be more clear.

If you are using `rlgl.h` directly yourself, you may need to do something similar from wherever you are doing that.   Otherwise, the intended technique is that `config.h` be customized.  

It looks like `config.h` could be documented a bit better to explain how it is conditionally included by modules and that the flag of choosing to use it is with `EXTERNAL_CONFIG_FLAGS`.  

```C
// Check if config flags have been externally provided on compilation line
#if !defined(EXTERNAL_CONFIG_FLAGS)
    #include "config.h"             // Defines module configuration flags
#endif
```

The initial comment needs some work there too.

**Comment by raysan5** [comment]
> The question now is why the limit is defined again in `config.h`

In practice, `rlgl` is part of `rcore` module so as `config.h` is included before `rlgl.h` it can be used to indirectly configure rlgl limits.

@orcmid The `config.h` approach was the simpler option I was able to find to cover all possible use cases and build systems.
