### ISSUE TITLE
[shapes] Add `CheckCollisionLineRec()` function

### ISSUE THREAD

**Issue by Wytekol** [raysan5/raylib#3289]
I always wanted this function, and why are there `CheckCollision*Rec()` functions for every type of shapes, but not for a line? This will be helpful for low-fps collision detection, 2D lasers, 2D shooting mechanics, etc.

declaration example:
`bool CheckCollisionLineRec(Rectangle rec, Vector2 startPos, Vector2 endPos, Vector2 *collisionPoint);`

**Comment by raysan5** [comment]
@Wytekol Have you faced any real situation on your development where this function was needed? Or is it just a desired feature because there are similar functions available? I try to minimize functions addition as much as possible and only add new functions when they are really needed. Personally, I never had the need for this function.

**Comment by Wytekol** [comment]
@raysan5 I was making a 2D game called 'Eclipse' for a game jam where you had to protect a certain thing from the sunlight with an umbrella, and then I needed it.

**Comment by iAndyHD3** [comment]
What ray says is true, functions should only be added if truly necessary. 

My suggestion is: make your own helper, it shouldn't be too hard and it will be faster than waiting for it to be added oficially. This way you can exactly adapt the function for your use case, since there are several ways this function could work.

**Comment by raysan5** [comment]
@Wytekol @iAndyHD3 If someone provide the implementation through a PR, I can add it. But if you expect someone else to implement it I'd just close the issue. Please, let me know.

**Comment by Wytekol** [comment]
@raysan5 Ok, i will try.

**Comment by Peter0x44** [comment]
I think this would be more suitable for raylib-extras

**Comment by SuperUserNameMan** [comment]
BTW, there is a [CheckCollisionRay2dRect()]( https://github.com/raylib-extras/extras-c/blob/main/ray_collision_2d.h#L28 ) on raylib-extras/extra-c.
