### ISSUE TITLE
[gestures] Tap gesture not properly recognized on Raspberry Pi

### ISSUE THREAD

**Issue by AndrewCapon** [raysan5/raylib#3335]
### Issue description

Using 'core_input_gestures' I see an issue where only HOLD, DRAG, PINCH IN and PINCH OUT are recognised.

I have had a look at the code, starting with why TAP is not recognised as I'm guessing if this started working the rest would!

So with the help of some debug logging:

 [0xf78cf040] is the main thread, [0xf0155440] is the event handling thread :

'UpdateGestures()' is called via 'EndDrawing()' -> 'PollInputEvents()' every frame.

I am logging the current gesture at the start of the main loop.

```
DEBUG: [0xf78cf040] Start Main Loop Gesture = 0
DEBUG: [0xf78cf040] UpdateGestures()

DEBUG: [0xf78cf040] Start Main Loop Gesture = 0
DEBUG: [0xf78cf040] UpdateGestures()

DEBUG: [0xf78cf040] Start Main Loop Gesture = 0
DEBUG: [0xf78cf040] UpdateGestures()

DEBUG: [0xf78cf040] Start Main Loop Gesture = 0
DEBUG: [0xf0155440] processGestureEvent() current = 1
DEBUG: [0xf0155440] processGestureEvent() current = 1
DEBUG: [0xf0155440] processGestureEvent() current = 1
DEBUG: [0xf0155440] processGestureEvent() current = 1
DEBUG: [0xf78cf040] UpdateGestures()

DEBUG: [0xf78cf040] Start Main Loop Gesture = 4
DEBUG: [0xf78cf040] UpdateGestures()
```

If we look at the code for 'UpdateGestures()' we can see the first thing it does is change the TAP (1) to HOLD (4)

```
void UpdateGestures(void)
{
    // NOTE: Gestures are processed through system callbacks on touch events
    TraceLog(LOG_DEBUG, "[%p] UpdateGestures()", pthread_self());
    // Detect GESTURE_HOLD
    if (((GESTURES.current == GESTURE_TAP) || (GESTURES.current == GESTURE_DOUBLETAP)) && (GESTURES.Touch.pointCount < 2))
    {
        GESTURES.current = GESTURE_HOLD;
        GESTURES.Hold.timeDuration = rgGetCurrentTime();
    }

    // Detect GESTURE_NONE
    if ((GESTURES.current == GESTURE_SWIPE_RIGHT) || (GESTURES.current == GESTURE_SWIPE_UP) || (GESTURES.current == GESTURE_SWIPE_LEFT) || (GESTURES.current == GESTURE_SWIPE_DOWN))
    {
        GESTURES.current = GESTURE_NONE;
    }
}
```

So I'm guessing this probably once worked and something may have changed?

There is no synchronisation between the threads so I guess its fairly random what might happen but this seems to be the issue I am seeing all the time.

Anyone any ideas?

Cheers

Andy

**Comment by raysan5** [comment]
@ubkp were you working on gestures lately? or was somebody else?

**Comment by ubkp** [comment]
@raysan5 I was back in july, but was mostly fixing gestures for `PLATFORM_WEB` and `PLATFORM_DESKTOP`:
- #3151
- #3153
- #3155
- #3163
- #3183
- #3190

I don't think I reviewed it for `PLATFORM_RPI` or `PLATFORM_DRM`. I did fix mouse wheel for `PLATFORM_RPI` and `PLATFORM_DRM` (#3193) tho, but that's unrelated.

If you don't mind keeping this open for a few days, I can review it after the split.

**Comment by raysan5** [comment]
> This will also be a lot easier/faster to fix after the split. And less prone to break web and desktop too.

@ubkp Agree. OK, no problem, no hurries.

**Comment by AndrewCapon** [comment]
Thanks Guys.

Has there been any thought put into multi-gestures, not sure that's the right word?

Basically multiple at the same time, so multiple taps for instance.

**Comment by ubkp** [comment]
@AndrewCapon https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L405-L408

**Comment by AndrewCapon** [comment]
Hi @ubkp 

Thanks for the info, I was thinking of the second case but really the idea of multiple controls (say sliders or lists for example) on the screen each being able to have their own gesture handling.

I have had a look at RayGui but that seems to be based on the Mouse code so is not multi touch either.

I'll have a look what I can knock up...

Cheers

Andy

**Comment by ubkp** [comment]
@AndrewCapon The following are my *personal opinions*:
1. Raylib as a `library` should endeavor to provide the _primitive tools_ through which the user can build his _solutions_; as opposed to an `engine` that _manages solutions_ the user can _use_.

2. Functionality (like the one described), IMHO, should be handled inside the program/game.

3. I'm always concerned of [feature creep](https://en.wikipedia.org/wiki/Feature_creep) and the effects it has. For example: the _camera module_ has a set of cameras hardcoded in it ([L432-L511](https://github.com/raysan5/raylib/blob/master/src/rcamera.h#L432-L511)), IMHO, that shouldn't be there at all. Not only any program/game (aside from a quick example/demo) will have to edit `rcamera.h` to do basic stuff like changing the keybinds, but also, if it ever changes, if could break what you've been using. IMHO, the only things the _camera module_ should provide is [L127-L143](https://github.com/raysan5/raylib/blob/master/src/rcamera.h#L127-L143) (and maybe [L514](https://github.com/raysan5/raylib/blob/master/src/rcamera.h#L514)), and examples should teach/suggest to the user _how_ a camera could be implemented with them.

4. I'm also always concerned about performance. The more the library tries to _manage_ itself, the more the program/game has to carry. That's really not a problem on desktop, but try running the examples on web over mobile. You need to be really mindful of what you really need and what you can trim off. And stuff the library triest to _manage_ become really hard to trim off.

5. I'm no way trying to dissuade you, that functionality looks really cool, but I just wouldn't like the library having to _manage_ it. If _primitive tools_ ([L1165-L1172](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L1165-L1172)) necessary to implement such functionality are missing, we should totally look into that tho.

**Comment by raysan5** [comment]
@ubkp 100% agree with all the mentioned points, specially with `feature creep` converns that it's something I'll fight against for years for raylib (and still it kept growing). In that regards, I agree with `rcamera.h` concerns, considered removing it many times and even `raylib-extras` repo contains better alternatives. It was just kept for convenience for small examples and demos.

One of the biggest concerns with raylib at the moment is maintenance, it's already very difficult to maintain the library, not only the source code with its issues/PRs but also all the ecosystem around it (social networks, community, webpage, examples, sample games...), so, adding more features could just make it more difficult.

**Comment by ubkp** [comment]
@raysan5 Yeah, that's way too much. Some things that could help:

1. **Merge windows**. For example, PRs could be evaluated just during the first week of the month. That gives lots of room for the submitter to think over it, revise it, discuss it. And if it's not ready on that week, just continue/try again on the next window. The Linux Kernel uses something akin to that.

2. **Demos instead of examples**. Currently there are _a lot_ of examples and they are usually focused on a single thing. Demos could instead focus on all related functions. For example, a single demo for all these ([L1028-L1039](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L1028-L1039)) would be a lot easier to maintain and reference.

3. **Schedule social media posts**. Social media could be updated once a month with a digest. The [Linux Mint Blog](https://blog.linuxmint.com/) is an excellent example of that. It gets updated just once a month with the gist of what's going on or when there's a new release.

4. **Focus on main/core**. Raylib grew a lot and I'm not sure if it's feasible to maintain in its full extension. At some point I think it will be necessary to choose what is really essential (main/core) and what is not. Linux distros use a similar logic with core vs community/contrib/universe. The parts considered essential should be actively maintained. Everything else could lag behind and/or get updated when there's interest (or even moved out to it's own file/etc).

**Comment by ubkp** [comment]
@AndrewCapon @raysan5 Temporarily working from the current master branch (c8a6093) while the split is in progress. Did a similar test:
```
INFO: Initializing raylib 4.6-dev
[...]
UPDATE       0 NONE
[...]
UPDATE       0 NONE
PROCESS MOVE 0 NONE
PROCESS MOVE 0 NONE
PROCESS MOVE 0 NONE
UPDATE       0 NONE
[...]
UPDATE       0 NONE
PROCESS MOVE 0 NONE
PROCESS DOWN 0 NONE
PROCESS DOWN 1 TAP
UPDATE       1 TAP
UPDATE       4 HOLD
UPDATE       4 HOLD
UPDATE       4 HOLD
PROCESS DOWN 4 HOLD
PROCESS UP   1 UP
PROCESS UP   0 NONE
UPDATE       0 NONE
[...]
UPDATE       0 NONE
[...]
INFO: Window closed successfully
```
It appears that the gestures are correctly detected and processed.

When a tap (`GESTURE_TAP`) begins (`TOUCH_ACTION_DOWN`), it gets processed (`ProcessGestureEvent`) correctly. It's also correctly being turned to hold (`GESTURE_HOLD`) during the update (`UpdateGestures`). And when the tap ends (`TOUCH_ACTION_UP`) it also gets processed correctly and cleared (`GESTURE_NONE`).

### Problem
The problem with `PLATFORM_DRM` appears to be that by the time the program/game does a `GetGestureDetected()` or `IsGestureDetected()` it won't catch the expected "PROCESS DOWN 1 TAP", likely because (unlike the other platforms) `PLATFORM_DRM` uses `evdev` which runs on its own thread and lacks a proper callback system (unlike `GLFW`, `emscripten`, `NDK`).

Nevertheless, I've reviewed all commits I did to the _gesture module_ and none of them should have had any effect into that. So I rolled back to master branch before all those (fdc28fce80d6e9ae04e900079beba7d79673b25d) and it wasn't working for `PLATFORM_DRM` even back then. If it ever worked, it probably was way before.

### Solution
Regarding how to solve this, the ideal would be `PLATFORM_DRM` having access to some callback system. But that's probably not an option.

Give me a few days to think some workaround for it. I just don't want to break (or have to heavily patch) the _gesture module_ to handle just this at the cost of all other platforms.

**Comment by raysan5** [comment]
@ubkp Thank you very much for investigating this issue. It expectable that `PLATFORM_DRM` works different than other platforms considering the raw low-level input access. It would probably be easier to track this kind of platform-specific nuances after the platform-split.

**Comment by ubkp** [comment]
@raysan5 Agreed. :+1: 

Leaving this note here for when it's time to pick up this issue again:
We'll probably need to store the last "meaningful" gesture on some var (similar to #3193) for `PLATFORM_DRM`.

**Comment by AndrewCapon** [comment]
Thanks guys, there is no hurry at all from my point.

**Comment by raysan5** [comment]
@ubkp @michaelfiber do you think this issue could be somewhat addressed now that the platform-split has been completed?

**Comment by ubkp** [comment]
@raysan5 I'm working on it right now. Trying to get it solved today, but it's a tricky issue. I'll do my best.

**Comment by raysan5** [comment]
@ubkp No hurries and no pressure, take it easy! I'm just reviewing the last open issues in case something can be easely addressed but I think `raylib 5.0` can be already published without them.

**Comment by ubkp** [comment]
@raysan5 I just noticed I missed adding the gesture handling to `PLATFORM_DESKTOP_SDL`. I'm so sorry, I really don't know how I missed that.

I'll try to fix both together since, without callbacks, both `SDL` and `DRM` will need a similar handling. I'm giving this total priority.

**Comment by raysan5** [comment]
@ubkp Oh, I just checked the gestures system yesterday, do you think the gestures system could be moved to `rcore.c` after platform `PollInputEvents()` is called? I think it just processes the already registered touch events (or mouse) to translate them into gestures, not sure how platform-dependant it is...

**Comment by ubkp** [comment]
@raysan5 As of right now, I think just part of it could.

The `UpdateGestures()`, that is called every frame, could probably be moved.

But the `ProcessGestureEvent()`, that has to be called where the event is detected (e.g.: callbacks, `EventThread`, etc), couldn't, since that differs for each platform.

But I'd advise against moving it right now. Since `DRM` (and now `SDL`) are not using callbacks systems, the position/timing/location of the `UpdateGestures()` call may have to change on those plataforms. I'm still working on a solution for it that doesn't require having to change `rgestures.h` to accommodate it.

**Comment by ubkp** [comment]
@raysan5 Fixed the gesture system for `PLATFORM_DESKTOP_SDL`. I'll send a PR for it shortly.

**Comment by raysan5** [comment]
@ubkp thanks for the review! Agree that gestures system could be quite callback-dependant, better review it after new release.

**Comment by ubkp** [comment]
@raysan5 I think I found why the `GESTURE_DRAG` and `GESTURE_SWIPE_*` were not wroking reliably on `PLATFORM_DRM`. For some reason the `GESTURE.Drag.distance` and `GESTURE.Drag.intensity` are sometimes zero on this platform. When they are not zero, it works perfectly. I'm still investigating why/where that happens.

**Comment by raysan5** [comment]
@ubkp thanks for investigating this issue! Considering the touch positions are updated on a secondary thread, maybe it could be related to some race-condition...

**Comment by ubkp** [comment]
@raysan5 Yeah, I spent the afternoon trying to confirm it, but there are so many events overlapping (`EV_REL`, `EV_ABS`, `ABS_PRESSURE`, `EV_KEY`) it's hard to isolate. I've started commenting it all and trying to debug it part by part. It's a slow process tho, but I'll get there. :+1:

**Comment by ubkp** [comment]
@raysan5 After trying basically everything I gave up fighting the threads and just moved everything related to `mouse/touch/gesture`'s `evdev` to inside `PollInputEvents()`, like it's done on `SDL`. It works great and reduces complexity considerably. @michaelfiber is absolutely correct, moving the input to the main thread is the way to go.

I'll append it all to the very end of `PollInputEvents()`, so i t doesn't interefere with the `DRM` input rework and can be easily removed when necessary. I'll clean this up and send a PR in a few hours.

**Comment by raysan5** [comment]
@ubkp thanks for the review! No worries about the threads, I know they can be problematic, moving to single-thread is fine for me, actually, afaik, only mouse should be in a second thread. Take your time!

**Comment by ubkp** [comment]
@raysan5 Found a solution. I'm crafting the PR, will send it shortly.
