### ISSUE TITLE
Legacy OpenGL Support

### ISSUE THREAD

**Issue by RDR8** [raysan5/raylib#334]
Field Report, we had everything working briefly on an old Apple PowerBook G4 running Debian 8. Only real issue that I can see is limited OpenGL support. It has an ATI card that only has OpenGL 2 something. But hey! It works! Awesome! If you do drop support for earlier versions of OpenGL, please at least leave a backward compatible version available. Thanks

**Comment by define-private-public** [comment]
I do have to put my 2¢ into this that I think that support for legacy OpenGL, (especially for CPUs that haven't been sold in the last decade) isn't really the best target to be perusing.  It's cool that a library can be that backwards compatible, but what are the odds that other may want (and regularly use) this?

**Comment by RDR8** [comment]
I agree. Odds are slim to none. I just wanted to let Ray know about a successful edge case.  He commented somewhere about moving on from early versions of OpenGL and I don't blame him. It's amazing what he's built so far and it's right to prioritize modern platforms. I'm really just requesting that the last version supporting legacy OpenGL continue to be made available after development has stopped.

**Comment by define-private-public** [comment]
In my opinion, I think everything below OpenGL 4 should be dropped.  That fixed function pipeline needs to die.

**Comment by RDR8** [comment]
Way off-topic but speaking of timely tech, for the long term, I wonder if I should be looking at Android and web tech for end-user application development.  My interest is in the tech behind a LAN based multiplayer game, not necessarily the game itself.The ARM hardware is pretty cheap but open graphics support from Linux isn't really there yet. Android looks to perform better as a client. Render anything heavy on Linux and Intel then display to thin clients running Android on ARM. Any thoughts on or experience with single-board computers or remote display technology?

**Comment by define-private-public** [comment]
I don't have too much experience messing with SBC things, other than the RPi, and its graphics stack kind of sucks.  I tried their experimental hardware accelerated OpenGL drivers a while back with a "Hello Triangle example." and it just wrecked everything.  Running the software implementation of OpenGL rendered correctly, at about 1/4 FPS.

There is already starting to be a flood of ARM SBCs.  I'm not sure how worth it they are for graphics.

As for remote display of graphical applications, ever tunnel X11 over SSH?  It's not that bad if you're on a small local network, but it starts to become a problem when the network gets larger and more congested.  Back at university I tried doing that with some OpenGL code.  Wasn't really the best experience.

**Comment by RDR8** [comment]
Me neither really, but I've been looking at them pretty hard. On ARM, X Windows 2D isn't always accelerated so the gui could be laggy at times. Android is supposedly better supported. It's definitely more responsive in demos. I'm thinking about a tiny application server with a few tinier clients. I can see Linux on an 8-core Odroid XU4 running a gaggle of Odroid C2 Android clients.  

I have done some X forwarding before but haven't tried it lately. Definitely an option. VNC is new to me so I've been using it. x2go is another thing I'd like to look into. 
  
My actual application doesn't need much in the way of graphics. Lot's of colors and crisp text is fine. I wonder how hard it would be to use raygui for the client interface. Just a few activities with alphanumeric input. For fun.  
  
Then there's the database... sigh.  
  
On to CMake...

**Comment by raysan5** [comment]
Hi @define-private-public and @RDR8!

About legacy OpenGL support, no plans to remove it, at least on **raylib 1.x** serie. Main problem with legacy OpenGL is the amount of side cases you have to consider when using one version or another (no VAO support, no compressed textures, mipmaps generation, framebuffers support, shaders, shader versions...), it supposed ~4000 LOCs in [rlgl](https://github.com/raysan5/raylib/blob/develop/src/rlgl.c) instead of ~2000 and some hard decisions (and engineering).

On the other side, raylib can work in mostly any computer from the last 20 years and also low-end devices (RPI), I think that's a key point that differentiate the library from other similar ones. Considering it was designed originally for education, offering a so wide opportunity to learn with it is a plus.

 > That fixed function pipeline needs to die.

Completely agree but for a students it's the most easy way to introduce into computer graphics, just before jumping to buffer and shaders. Actually [rlgl](https://github.com/raysan5/raylib/blob/develop/src/rlgl.c) tried to be that, a middle layer that translates immediate mode drawing into modern OpenGL, it just makes transparent the same work that drivers do when using legacy OpenGL on modern GPUs. By the way, rlgl can be used as [standalone library](https://github.com/raysan5/raylib/blob/develop/examples/others/rlgl_standalone.c).

> I'm really just requesting that the last version supporting legacy OpenGL continue to be made available after development has stopped.

You got all previous raylib releases here: https://github.com/raysan5/raylib/releases

> I wonder how hard it would be to use raygui for the client interface.

I'm working on this module... now trying to simplify to one-draw-call. It should work great on RPI, just draws a bunch of quads and inputs in RPI are managed in second thread.

**Comment by RDR8** [comment]
Thanks to both of you for responding. I was really surprised when everything built the first time on that PowerPC. raylib satisfies.
