### ISSUE TITLE
[core] GetMouseButton{Pressed,Released}

### ISSUE THREAD

**Issue by link2xt** [raysan5/raylib#3354]
Keyboard handling has a function `GetKeyPressed` which queues keys even if the key is pressed and released within a single frame.

However, for mouse there is no similar function. `IsMouseButtonPressed` compares previous and current state, but this approach cannot be used to reliably count the number of clicks. Even implementing a "clicker" game with raylib is not possible.

I would like to have a function `GetMouseButtonPressed` that returns true once for each click, so calling it in a loop will make it possible to count clicks.

Overall input handling in raylib seems suitable for platformer and shooter games where having a button pressed makes the character constantly move or shoot, but much less for strategy and tactics where someone may want to click on a button precise number of times to create N units and things like that.

**Comment by Julianiolo** [comment]
I had a similar issue, because on my laptop for some reason if you double tapped, it would bunch up the release and the new press into one frame, so that it was just registered as a single click, not a double click.
Altough the fix to that problem would probably be something like setting the "last frame clicked" variable on such a bunched up release&click? Since raylib just checks the "current is clicked" and "last was clicked" to check if a mouse button was pressed

**Comment by Julianiolo** [comment]
Yeah, True just a problem caused by the same cause if that makes sense lol.

Although may I suggest maybe having each IsMouseButtonX function just return the number of clicks? That should work equal to the current version. Although it might give problems with people using them "incorrectly" idk.

Anyway that would be kind of a big change so not sure on how feasible that is.

**Comment by actondev** [comment]
Just my 2 cents, in order to follow the current API, `GetMouseButtonPressed` should return a `MouseButton` enum, which should be extended to add a `MOUSE_BUTTON_NONE = -1`. So for every registered click between two frames it should return the button for which a click was registered and finally returns -1. Same for the `Released` version

**Comment by raysan5** [comment]
No plans to add a `GetMouseButton*()`, that functionality can be easely implemented at user side just scanning all mouse buttons.
