### ISSUE TITLE
[games] wave_collector game is broken w/ OpenGL 1.1 and OpenGL 3.3(on Linux)

### ISSUE THREAD

**Issue by define-private-public** [raysan5/raylib#338]
This is how OpenGL 1.1 looks:
![wave_opengl_11_linux_broken](https://user-images.githubusercontent.com/4551425/28698063-b926e3a4-730e-11e7-96f5-95390ec8ed76.png)

It's not really playable.

This is how OpenGL 3.3 looks:
![wave_opengl_33_linux_broken](https://user-images.githubusercontent.com/4551425/28698075-cff5e1f2-730e-11e7-9991-4aa9346db714.png)

This may look good, and is playable, but the issue here is that the lines aren't matching up with the dots.  Take a look at the example on the web for how it should be displayed:
http://www.raylib.com/games/wave_collector.html

**Comment by raysan5** [comment]
Ok, more math issues, just need to reverse those lines for OpenGL 3.3: https://github.com/raysan5/raylib/blob/develop/src/shapes.c#L125

But first need to review https://github.com/raysan5/raylib/issues/335 for consistency with OpenGL 1.1.

About OpenGL 1.1 version, I think I never compiled this game for that backend... needs some review but the problem is related with custom framebuffer drawing, not supported in OpenGL 1.1...

**Comment by raysan5** [comment]
Issue corrected on commit https://github.com/raysan5/raylib/commit/ae35c37c8a98a0413ae525719bbbdee53dfcc86d

Now it should work with OpenGL 1.1 and OpenGL 3.3.

Please, close the issue if it works ok.

**Comment by define-private-public** [comment]
I tested, they work.
