### ISSUE TITLE
IsGestureDetected inconsistent parameters

### ISSUE THREAD

**Issue by jestarray** [raysan5/raylib#3463]
```c

// src/rgestures.h line 127
bool IsGestureDetected(int gesture);                    // Check if a gesture have been detected

// src/raylib.h line 1170
RLAPI bool IsGestureDetected(unsigned int gesture);     // Check if a gesture have been detected
```
how come one is `int` and the other is `unsigned int`? Which one should it be? Originally it was an int(in rust bindings)

**Comment by ubkp** [comment]
@jestarray `gesture` is `enum` ([L79-L91](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L79-L91)). Quoting [this answer](https://stackoverflow.com/questions/2579230/signedness-of-enum-in-c-c99-c-cx-gnu-c-gnu-c99): _"An enum is guaranteed to be represented by an integer, but the actual type (and its signedness) is implementation-dependent."_

In the case of `IsGestureDetected()` I don't think it matters, since underflowing or overflowing that parameter will be out of bounds of that `enum` valid gestures anyway. But, IMHO, could probably be changed to `int gesture` on `raylib.h` just for the sake of consistency.
