### ISSUE TITLE
[?] Failed to initialize Graphic Device

### ISSUE THREAD

**Issue by glowiak** [raysan5/raylib#3493]
### Issue description

I am trying to compile my game for windows, so that more people can play it. Windows is such a retarded platform that it does not ship with any compiler by default, so I had to download the Raylib installer that didn't even run. I extracted it manually to locations specified in readme.txt, and it compiled with no errors and no warnings.

When trying to run the built executable it fails with error code 1 and this message:

<img src="https://i.imgur.com/dR3VxIz.png">

### Environment

I tested it on Windows 8 Release Preview, and Windows 10 (both x86_64) with the same result. All of it was done on VirtualBox as I don't want to waste my disk space on actual Windows.

### Issue Screenshot

<img src="https://i.imgur.com/dR3VxIz.png">

### Code Example

I don't know what code caused this, on my Gentoo install it works as intended.

**Comment by raysan5** [comment]
@glowiak This issue is related to using an old GPU or outdated graphic drivers. It does not support OpenGL 3.3.

The solution is updating drivers or recompiling raylib for an older OpenGL version like 2.1 or 1.1. Here more info: https://github.com/raysan5/raylib/wiki/Frequently-Asked-Questions#can-i-run-raylib-in-my-old-pc
