### ISSUE TITLE
[parser] Feature request: Can we add data size to structs?

### ISSUE THREAD

**Issue by JupiterRider** [raysan5/raylib#3522]
Would it be possible to add a new field to the structs which shows the data size in bytes?
For example:
```json
"structs": [
    {
      "name": "Vector2",
      "description": "Vector2, 2 components",
      "size": 8,
      "fields": [
        {
          "type": "float",
          "name": "x",
          "description": "Vector x component"
        },
        {
          "type": "float",
          "name": "y",
          "description": "Vector y component"
        }
      ]
    },
```
This would help me to generate bindings, because depending on the OS, you have to pass values by reference, if they exceed a certain size. 
This is the Windows ABI for example:
https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170

I think this shouldn't be hard to implement, because C has the `sizeof` operator.

**Comment by ubkp** [comment]
@JupiterRider I could be wrong, but, from memory, I think the size is platform/implementation dependent as per spec omission.

**Comment by raysan5** [comment]
@JupiterRider I'm afraid that, as @ubkp commented, the structs size is platform-dependant, for example, it's not the same on x86 or x64 architectures (but it can also change depending on other factors). [More info here](https://github.com/raysan5/raylib/wiki/raylib-data-structures).

Adding that info to the parser could be missleading.

**Comment by orcmid** [comment]
I agree that this should not be done, although I don't understand the explanation nor the example given by @JupiterRider.

There could be a `size_t` field at the *beginning* of a **struct** type *T*, and it could be initialized to **sizeof**(*T*).   

That's a nightmare burden at the C Language level.  Also, it means that a trip-wire between pass by value and pass by reference could be hit, and that matters even more in all of the raylib code where **struct** type-named values are returned as the results of functions.  Fortunately, the parameters are mostly treated as **const** so that's moderately safe.

This also doesn't satisfy the request, if that JSON is meant to be extractable with the specific value for a platform and build configuration.  I assume that's why the request can't be satisfied.  It's also problematic at run-time even though feasible.  Definitely impractical.
