### ISSUE TITLE
[rtext] Font size is being treated as an integer, but stb truetype accepts float size

### ISSUE THREAD

**Issue by GaryMcWhorter** [raysan5/raylib#3766]
### Issue description

Font size in raylib is passed along the api as an int, but truetype accepts a float value. The reason why this is important is because the sharpness of a font rasterized by stb truetype is highly dependent on this value, with steps as small as 0.05f making a noticeable difference. By using integer font sizes, only some fonts (especially affecting pixel fonts) are able to align properly to the rasterization grid. If we use a float value instead, we are able to fine tune the size necessary per font to reach perfect rasterization.

To enable this to work, a few functions and a struct need to be altered to change the type from int to float.
This is a big api change, but the results should be a great benefit.

### Issue Screenshot

Here we can see a font rasterized at 13pt, with a severe subpixel halo:
![image](https://github.com/raysan5/raylib/assets/52535319/47f24ec3-a982-4088-90f2-ebb831aa4492)

Not good at 12pt either:
![image](https://github.com/raysan5/raylib/assets/52535319/a100d841-9c4a-4166-9c83-03f5ea51d8f7)

But 12.7pt works perfectly!
![image](https://github.com/raysan5/raylib/assets/52535319/5c5193fb-8fab-4025-b092-8cc688605859)

### Code Changes
```c
// raylib.h line 310
typedef struct Font {
    float baseSize;           // Base size (default chars height) <-- Change from int to float
    int glyphCount;         // Number of glyph characters
    int glyphPadding;       // Padding around the glyph characters
    Texture2D texture;      // Texture atlas containing the glyphs
    Rectangle *recs;        // Rectangles in texture for the glyphs
    GlyphInfo *glyphs;      // Glyphs info data
} Font;
```
```c
// change fontSize from int to float for the following function signatures
// note, the respective forward declarations will need to be updated as well
// rtext.c line 361
Font LoadFontEx(const char *fileName, float fontSize, int *codepoints, int codepointCount)

// rtext.c line 507
Font LoadFontFromMemory(const char *fileType, const unsigned char *fileData, int dataSize, float fontSize, int *codepoints, int codepointCount)

// rtext.c line 565
GlyphInfo *LoadFontData(const unsigned char *fileData, int dataSize, float fontSize, int *codepoints, int codepointCount, int type)
```

**Comment by raysan5** [comment]
This is a breaking change and I'm considering it carefully. Also, it seems a bit werd that a font size should be requested with decimal values, it makes me think something is not properly considered on raylib internal font rasterizer...

raylib uses `stb_truetype` for font rasterization but maybe font size "points" and "pixels" are not properly calculated, it requires some further investigation before implementing this change.

**Comment by orcmid** [comment]
@raysan5 
It turns out that fractional font sizes (in points) are used real world typography and I suspect in quality renderings, such as with PostScript or other tools designed for high-quality rendering.  Browsers seem to allow them but some (necessarily?) round to integral sizes (in the equivalent pixels) and in different ways.

**Comment by designerfuzzi** [comment]
**Units/Geviert != pt != px.**
Fonts are given in "Units/Geviert" since long before ttf existed. In fact the unit is used since the invention of font letters to be used in printing. `Pt` is a unit that is based on unit/geviert and interpreted as fraction relative to dpi on screen (either 72dpi or 96dpi or even higher). 

With rasterized pixel oriented screens it was needed to make those fractions appear as integer to match a full pixel as half pixels can't be shown and aliasing was considered intense computing. Which lead to standardisation of some pt values and later even optimisation of rasterisation for some selected integer values, in particular the small interpretations, like 4.5pt, 5pt, 6pt, 7pt, 8, 9, 10.5, 11. That allowed to have different pixel alignment for each of those scales.

Up to this day professional glyph development software offer pixel previews where a fraction of a vector would fall into so that typographs can make tiny changes to make their fonts appear more crisp in certain integer font sizes. Another way is to use a specific ceil and floor (alignments) for all fractional values when they fall into a specific range, considering the logic that a glyph line that aligns below one pixel threshold would become invisible. 

Windows was known for its aliasing issues which also lead to a printing/graphic industry using mostly macs.Therefor some pt values are not shown in editors on purpose (like ms word) to avoid exposing the problem. 

PS: _the english translation for the german term "Units/Geviert" is "FUnits/EM", where "EM" stands for "em square", which is a square whose side length is equal to the font's point size. Each glyph is designed within this square grid. Which also means that even explicit square aligned fonts come in values that are fractions of the unit (em square)._

**Comment by orcmid** [comment]
@designerfuzzi 
> That means it has literally nothing to do with postscript. Postscript is solely a format to pack data that also allows to give relative size of a sheet so it can be properly reproduced. In other words it supports printing systems, not screen systems. Displaying fonts is always an alignment enterprise, unless we talk about bitmap fonts which are designed to only match certain bitmap sizes and some fixed scales.

I don't think that's completely accurate with regard to imaging with PostScript, Interpress, TeX, or other final-form imaging/printing systems.  Those systems have to deal with font rendering via digital graphics, whether screens or laser printers.  There are cross-overs between imaging on screens and on paper, although I do agree that the nomenclatures get murky.

My impression with raylib is that there is a confusion between pixels (and some presumed dpi) and other typographical measures with regard to text.

And thank you for the elaborate account.

**Comment by designerfuzzi** [comment]
well if we'd take it not so narrow than pdf is successor to postscript.
 
"PostScript is a page description language developed by Adobe Systems in the 1980s. It describes the appearance of a printed page in a device-independent manner. PostScript files contain instructions that describe how to draw text, graphics, and images on a page, and they can be interpreted by a PostScript-compatible printer or by software that interprets PostScript code."
So for printers or 'rip (aka computers that render print data to generate physical templates for printing machines). Which typical lead to fonts being included in the postscript file, either as bezier paths or later as entire font's for which they needed to be standardised. 

and the logic follow up on those widely accepted standards is PDF.
"PDF is a file format developed by Adobe Systems in the 1990s. Designed to present documents, including text formatting and images, in a manner independent of application software, hardware, and operating systems. PDF files can contain a variety of content, including text, graphics, multimedia elements, and interactive elements."

Where postscript can be seen as a subset of PDF, despite that is not 100% true anymore. 
In fact postscript always needed an interpreter to be shown on screen for any double check before expensive printing. We still have those, formerly postscript viewers nowadays PDF viewers. Even if it might feel as if that is a native feature of modern OS'es it is still specific software sometime even with an entirely different rendering system.

**Comment by orcmid** [comment]
@designerfuzzi I don't want to continue this conversation since it is now far afield from the subject of this discussion.  I do want to correct some historical difficulties with the material you are quoting.

I would like to point out that PDF started out as a customization of PostScript to be page-oriented, which PostScript did not require.  Also, PostScript was used in a sort-of-native way on the original Macintosh.  It is not appropriate to think of one as a subset or successor of the other.

I also worked on a project where Adobe provided a preprocessor board for Windows PCs that would emit Interpress from Postscript files.  This was to allow a document processing flow from Windows through a Windows-based server that acted as a front-end to DocuTech, which used XNS protocols and ripped Interpress.  That work was done prior to announcement of DocuTech.  I don't know if it ever shipped.  

I worked on a similar project that used a form of ODA and shipped images through a customized Unix server to DocuTechs.  This was used in a book preservation project at Cornell University, and the resulting scanned documents are available online from there.  They could also be printed and bound on-demand via a DocuTech installed there.  There are no font issues here, and the differences between write-white and write-black xerographic printing not a particular issue at 1200 spi :).

More than that, I recall when all of those document-publishing forms were introduced and I knew some of the people involved.  That's an interesting use of "rip."  I'd forgotten about that.  I use PDF/A wherever I can :).

**Comment by designerfuzzi** [comment]
Sure. Agree, typo expert, font dev and former Doc Admin of Bild and Spiegel here. 
It was all about why integer based atlas rendering is good for bitmap fonts but not entirely valid for ttf/otf fonts And the postscript stuff was your output. I solely quoted Adobes definitions, guessing it doesnt matter if pdf/X4 or what ever .. 

I just wanted to confirm that font systems are float based, no matter what ms-word says.

**Comment by raysan5** [comment]
I've been investigating this issue and raylib `LoadFont*()` functions considers that size refers to font **pixels height**, that per [`stb_truetype`](https://github.com/nothings/stb/blob/master/stb_truetype.h), used for the glyph rasterization process, effective is considered as a pixel-height value and font generation [scaling from the provided **size in pixels**](https://github.com/raysan5/raylib/blob/master/src/rtext.c#L629) input parameter is applied.

As per my understanding and @designerfuzzi explanation, the issue relies in the EMs used to create the font, that can not be directly mapped to an integer pixel-size value, for example, a value of *1.1em* has no mapping to integer pixel size:

Points | Pixels | EMs
-- | -- | --
12pt | **16px** | 1em
13pt | **17px** | 1.05em
13.5pt | **18px** | 1.125em
14pt | **19px** | 1.2em

Solution to this issue is not that trivial. One possible solution would be changing the expected font input size from **pixels** to **points** (to keep the level of simplicity), but it would break all codebases using `LoadFontEx()`, that expects input parameter in **pixels**. Here a related note in `stb_truetype` code:

```
Font Size in Pixels or Points
   The preferred interface for specifying font sizes in stb_truetype
   is to specify how tall the font's vertical extent should be in pixels.
   If that sounds good enough, skip the next paragraph.

   Most font APIs instead use "points", which are a common typographic
   measurement for describing font size, defined as 72 points per inch.
   stb_truetype provides a point API for compatibility. However, true
   "per inch" conventions don't make much sense on computer displays
   since different monitors have different number of pixels per
   inch. For example, Windows traditionally uses a convention that
   there are 96 pixels per inch, thus making 'inch' measurements have
   nothing to do with inches, and thus effectively defining a point to
   be 1.333 pixels. Additionally, the TrueType font data provides
   an explicit scale factor to scale a given font's glyphs to points,
   but the author has observed that this scale factor is often wrong
   for non-commercial fonts, thus making fonts scaled in points
   according to the TrueType spec incoherently sized in practice.
```

The proposed solution of using `float` for size could also confuse users about what that parameters refers to and it implies a redesign of many raylib elements (i.e `Font.baseSize`, loading, assignments...), not to mention the potential breaking changes in other codebases.

So, after lot of thinking, I'm afraid it will keep it as it is and just recommend using a different font that could be mapped to a perfect pixel-size.
