### ISSUE TITLE
[models] Billboards not working properly when drawing in front of lines

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#38]
It seems there is some depth-test issue when `DrawBillboard()` in front of grid lines.

Related raylib example: `models_billboard.c`

Related functions [models.c]:

    void DrawBillboard(Camera camera, Texture2D texture, Vector3 center, float size, Color tint)

Lines, Triangles and Quads are placed in different buffers inside `rlgl.c`. When calling `rlglDraw()`, buffers drawing order is always: Triangles, Quads and Lines. On a 2D orthographic issue this could represent a problem but not on a 3D perspective view because depth-test is enabled... So, why lines behind billboard quad are not visible?

**Comment by victorfisac** [comment]
If you change drawing order to lines, triangles and quads the problem dissapears... But there is always a depth issue due the drawing order (easy to see when drawing semi-transparent objects). I supose it cannot draw lines behind quads because they are not rendererd yet...

http://stackoverflow.com/questions/5984887/opengl-z-sorting-transparency

Discarting pixels is a possible solution when drawing opaque textures with transparent pixels like the billboard texture. But when drawing semitransparent objects one always won't be rendered behind the other based on its drawing order. A possible solution as the link says is render all opaque objects and then render semitransparent order from back to front... Or directly [render everything from back to front relative to the camera](http://gamedev.stackexchange.com/questions/68957/order-of-render-with-transparency-opengl).

**Comment by raysan5** [comment]
Hi @victorfisac ,
Thank you very much for the info, you're right.
One solution would be spliting buffers for opaque and transparent elements but that requires a big code review... Need to think about it...

**Comment by raysan5** [comment]
As proposed, a simple fixed has been applied (changing drawing order to lines, triangles and quads).

It works very good because in a previous commit it was added depth information to all vertex data.

Fixed on commit https://github.com/raysan5/raylib/commit/e5a56fa98515337c805e5a641cd3787cb6898596
