### ISSUE TITLE
[rtext] Font glyph images height could be bigger than font size

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#3858]
Font atlas generation assumes that font glyph images height can not be bigger  than font size (assumed as max height) but it seems that's not the case, it should be reviewed.

More detailed info here: https://github.com/raysan5/raylib/issues/2991#issuecomment-1975093390

**Comment by designerfuzzi** [comment]
Indeed if we think of characters that like "g" or "y" or "ç" and so on, they all have dangling content below the baseline. In fact font software is meant to deal with that. If where only about the graphics a simple svg editor would be sufficient enough, but its the baseline and hints, kerning (despite not that interesting for raylib), referenced letters that makes it a font. 

LineHeight is already addressed quite flexible by keeping it as global and apply where needed. When a font is loaded the image size of the letters seem already correct. But stitching them together to an Atlas assumed they all are the same height not larger than lineheight leading to choped-off visual.

Can create a simple test_font ttf or otf using the hanging graphics for ya. 
Fonts can also be higher above their baseline + lineheight. 
Because of that there should be some relative coordinate to which `offsetY` and respective its origin (0) are relative to.

**Comment by raysan5** [comment]
@designerfuzzi Please, could you provide a font to test this issue, I've been trying to find one for about an hour and I can't find any...

**Comment by raysan5** [comment]
It seems this issue is very difficult to reproduce, closing it. A warning log message was added in case it happens.

**Comment by fosskers** [comment]
Forgive the resurrection. If the warning in question is:

> WARNING: FONT: Character [0x0000007c] size is bigger than expected font size

then I have a font that triggers this.
