### ISSUE TITLE
[gestures] GESTURE_HOLD not detected properly

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#40]
Gestures detection system doesn't detect HOLD properly, it changes to GESTURE_DRAG instead.

Related functions [gestures.c]:

    static void ProcessMotionEvent(GestureEvent event);

ProcessMotionEvent() is launched only when an event has been detected, gestures update logic should be reviewed to detect HOLD state correctly.

Here it is a quick draft of gestures detection states:

![image](https://cloud.githubusercontent.com/assets/5766837/9696191/ff5170de-536b-11e5-98a4-8237b8f50789.png)

**Comment by victorfisac** [comment]
I reviewed the module a little bit... During DOWN event, although in UpdateGestures() currentGesture is set to HOLD when currentGesture is TAP two frames in a row, I think this value is overwriten by ProcessGestureEvent() because **during the DOWN event, there is no check if the drag vector magnitude is less than FORCE_TO_SWYPE (and set it as HOLD because the movement is very little) or change it to DRAG (because user is really moving his finger by the screen) so it is changed to DRAG.**

Adding the following code inside of TOUCH_MOVE (line 221) case fixs the problem:

```c
if(magnitude > FORCE_TO_SWIPE)
{
     currentGesture = GESTURE_DRAG;
     draggingTimeCounter++;
}
else currentGesture = GESTURE_HOLD;
```

I think it is a good way to ensure the user has a little margin to move finger without detecting it as movement. I will test more and commit it in my fork...

**Comment by victorfisac** [comment]
To enter in GESTURE_HOLD state, current gesture and previous gesture must be GESTURE_TAP two frames in a row.

When touching screen, GESTURE_TAP is called but in next frame, if touch position doesn't change the gesture callback is not called so previous gesture value is not changed. It must be changed in UpdateGestures() to change its value every frame and then check if current and previous are TAP, switch to HOLD.

Tested changes in code and works fine. Previous comment idea can be an enhacement... I'm going to pull you a request...

**Comment by raysan5** [comment]
Thanks @victorfisac for taking care of this issue and for your pull request https://github.com/raysan5/raylib/commit/ed674d865ba2fc845a91aea6c77dffae7576e0c0

Currently we are refactoring `ProcessGestureEvent()` function from `gestures.c`, it was quite complicated and it can be simplified.
