### ISSUE TITLE
[rlgl] ERROR: MAX_TRIANGLES_BATCH overflow

### ISSUE THREAD

**Issue by SethArchambault** [raysan5/raylib#419]
I am making a game which prints a whole bunch of hexagons - each made using DrawPoly. 
After putting down a bunch of tiles,  the program closes, and I see the error message "MAX_TRIANGLES_BATCH overflow". 

Which seems to come from this line:
https://github.com/raysan5/raylib/blob/53280a56e3f4ab576fafeb75a68031fcdc4089fa/src/rlgl.c#L677

It looks like this is defined here:
https://github.com/raysan5/raylib/blob/53280a56e3f4ab576fafeb75a68031fcdc4089fa/src/rlgl.h#L98

It's a 36 x 19 map, and I'm using 2 hexagons for each tile (1 for the tile, 1 for a shadow of the tile).  At 684 hexagons, it crashes(4104 triangles)..

How should I get around this issue? 
I can probably find a way to render this with fewer triangles, but is this a hard upper limit? 
Thanks!

**Comment by raysan5** [comment]
Hi @SethArchambault! Thanks for pointing this issue! Also related to https://github.com/gen2brain/raylib-go/issues/12 and https://github.com/raysan5/raylib/issues/267.

I already solved this issue for `MAX_QUADS_BATCH` but not for `MAX_TRIANGLES_BATCH`, my idea was replacing all elements drawing just by quads instead of using triangles, that way, I have to manage internally only one vertex buffer (quads) instead of three (lines, triangles, quads).

I'll correct this issue in the following days, in the meantime you can just change value in `rlgl.h` and recompile the library with Notepad++ script `raylib_source_compile` or using provided Makefile.
```c
#define MAX_TRIANGLES_BATCH     8192
```

**Comment by raysan5** [comment]
Solution implemented in commit https://github.com/raysan5/raylib/commit/4dcc02ff1ef4d6ab6c10ece84c47892f12290908

It's not the best solution but it will work for now.
