### ISSUE TITLE
[rcore] Ability to rebind Capture/F12 hotkey

### ISSUE THREAD

**Issue by Clawthorn** [raysan5/raylib#4219]
The title says it all pretty much. It would be super nice to have something similar to `SetExitKey(int key)` but for the capture functionality, so that you can rebind/disable it at runtime without having to recompile the entire library.

The current implementation feels incredibly clunky, since by default you can't really allow the player to rebind and use F12, lest you want to burn a hole in their SSD and fill their game directory with random PNGs.

And if you do recompile the library to explicitly disable the F12 hijack, you have no way of manually triggering a GIF recording if you do want one, since there's no programmer-facing API to manually trigger it (similar to `TakeScreenshot(const char *fileName)`). In fact, disabling just `SUPPORT_SCREEN_CAPTURE` seems to disable the ability to CTRL + F12, so you can't really "half-disable" the capture system while keeping the GIF recording.

If this cannot be done then may I at least suggest that the default key be changed to `Print Screen` rather than F12, since that's the key most people associate with capturing screenshots. And it's less likely the player would want to rebind and use that as a game hotkey.

**Comment by raysan5** [comment]
Capturing functionality was added for convenience for my students. Anyone with that requirement should implement their own solutions at user side. Using `PrintScreen` could result in issues on some platforms, so no plans to change it for now.

**Comment by fasterik** [comment]
I just ran into this. I didn't even know GIF capture was a feature of Raylib. I have a system-wide hotkey bound to Ctrl+Shift+F12 to start/stop screen capture in OBS. So when I start an OBS capture, Raylib also starts capturing a GIF which causes a severe drop in frame rate.

It really doesn't make sense for a graphics/windowing library to force this on the user. For programs that want to do GIF capture, it would be convenient enough to have an API like the following: `if (IsKeyPressed(hotkey)) StartGIFCapture()`. For the vast majority programs that want to bind F12 or use system-wide hotkeys, it should be opt-in.

**Comment by raysan5** [comment]
@fasterik This feature is being reviewed, disabled by default and it's up to user to enable it and recompile raylib if desired.

**Comment by fasterik** [comment]
@raysan5 I'm not sure I understand your comment. Screen capture is enabled in the build I'm using, which is the Raylib 5.5 x64 MSVC lib from the releases page. Or do you mean that it's up to the user to recompile raylib to _disable_ screen capture?

**Comment by jordan4ibanez** [comment]
My suggestion:
```c
void SetScreenshotKey(int key);
```

This is EXTREMELY important! 

If you use default bindings you have NO access to any of this code unless it has been changed in the binding! Like in raylib-d (https://code.dlang.org/packages/raylib-d) which uses the releases that are made on this github repo so that the setup is stream lined and official as possible.

This makes it so in other languages you now have to set up additional compilation pipelines to change a simple key binding! The way this is currently hard coded with no ability to change this the way you should be able to with your bindings is horrible! 

Look at this mess: https://github.com/jordan4ibanez/classic_tale/blob/main/source/utility/screenshot.d 

I have to take your CWD screenshot and rename it then move it instead of that being one unit where I can just tell raylib where to output the named screenshot! I have no access to rebind f12 in any of my raylib games. If I could set the keybinding to whatever this wouldn't be an issue.

Also if f12 is the end all be all of the raylib library then why do we have:
```
 void TakeScreenshot(const char *fileName);                // Takes a screenshot of current screen (filename extension defines format)
```

That function might as well not exist. Just tell the players of your game or the users of your program to hit f12.

I know it kinda looks like I'm standing on a crack on the sidewalk and declaring there is a ravine under me, but it is just boggling my mind that this is like this.
