### ISSUE TITLE
[rcore][SDL] `GetWorkingDirectory()` returns application directory after initialization

### ISSUE THREAD

**Issue by quicktea8313** [raysan5/raylib#4388]
This is an issue with the SDL backend.

Before Raylib is inititalized, GetWorkingDirectory() returns the correct working directory.  After initialization, it instead returns the same as GetApplicationDirectory().  This also causes resources not to load if your application is running from somewhere other than the current directory.

**Comment by raysan5** [comment]
@quicktea8313 thanks for reporting!

**Comment by asdromundo** [comment]
Hello, I'm using Raylib 5.6.0dev from the main branch, and I'm still having this issue when using the SDL backend.

Resources won't load unless running the binary from the current directory.

Not sure if this was reintroduced somehow since the thread is marked as completed

**Comment by raysan5** [comment]
@asdromundo Not sure if I understand, resources are loaded from the path provided to the `Load*()` method, relative to the system working directory, it's up to the developer to consider that on the user side.

**Comment by asdromundo** [comment]
@raysan5 When using the SDL backend I have the problem described in the original post of this thread. When accesing the binary from a different directory it fails to load the resources in the binary location.

From a terminal located in the root of the raylib binary (in my case named overdrawn) it can Load the resources accordingly. Thus double clicking the binary directly works alright but opening from a terminal fails in any other location but the same as the binary.

![Image](https://github.com/user-attachments/assets/7992e5d3-7cfc-4a21-ba1d-bb6b3a7538ef)

```bash
./overdrawn
```
The load from same directory behaivor and also GLFW backend behaivor (from any directory):
![Image](https://github.com/user-attachments/assets/36bb76e5-1190-44bc-aeb7-d5d3a3adf5a4)

Whereas trying to run the binary from other directory (for example the parent directory):
```bash
overdrawn/overdrawn
```
![Image](https://github.com/user-attachments/assets/f2dc00e8-6903-45eb-bdf6-dd72b2f8e02c)

I suspect is the same problem that the OP described with the GetWorkingDirectory() & GetApplicationDirectory() SDL problems because using the exact same code with a GFLW backend works from any calling directory (in this example the parent one).

**Comment by raysan5** [comment]
@asdromundo Ok, thanks for the further description, better keep the comments for future users getting here! 😄
