### ISSUE TITLE
RenderTexture2D not rendering models.

### ISSUE THREAD

**Issue by TheLumaio** [raysan5/raylib#441]
I'm not sure which commit it was but whichever one removed the `rlClearScreenBuffers` from `BeginTextureMode` caused a bug where models won't render. Text and shapes render fine. Compiling the post processing example shows this bug and adding the line back seems to fix the issue.

**Comment by a3f** [comment]
https://github.com/raysan5/raylib/commit/b760f16f9b3a967675b5cccd39a5172634f3f2d4#diff-cdfc1aea8847d91e401cad52d98e6d70L931

**Comment by TheLumaio** [comment]
Is there a reason that line was removed or was it just an oversight?

**Comment by a3f** [comment]
@raysan5 will have to answer that. I am just noting the commit in question :)

**Comment by TheLumaio** [comment]
Ok so not being a tired idiot and actually looking it at I can see you just have to call `ClearBackground` again after `BeginTextureMode`.

**Comment by a3f** [comment]
Does the post processing example still misrender? If so, could you file a pull request?

**Comment by raysan5** [comment]
Hi @TheLumaio! Thanks for finding this issue! 

Just changed it a while ago because I needed a custom clear color for `RenderTexture2D` framebuffer different than the one used for the default framebuffer (specifically, needed a transparent color to draw an image with alpha on it). Just broke the expected behaviour.

Probably that line shouldn't be removed... but then, if calling `ClearBackground()` inside `BegintextureMode()` while perform a double clearing of the buffer... but [reading this post](https://stackoverflow.com/questions/37335281/is-glcleargl-color-buffer-bit-preferred-before-a-whole-frame-buffer-overwritte), it seems that nowadays the cost of that operation is negligible.

@a3f, thanks for providing the related commit, I'd correct it now.

**Comment by raysan5** [comment]
Corrected in commit https://github.com/raysan5/raylib/commit/1d5fbef93db3f4ead04fd23885df1ddabe97b232
