### ISSUE TITLE
[textures] LoadTextureFromImage() Texture could not be created in Multithread

### ISSUE THREAD

**Issue by dginu85** [raysan5/raylib#448]
Hi nice people,
I do not understand why it does not create the texture:
look at the code, where am I wrong?

```
void GetImageFromCache(char * path, std::function<void(Image)>CallBack) {
CallBack(LoadImage(path));
}
std::thread t(GetImageFromCache,PATH,[this](Image img) {
TEXTURE_NORMAL = LoadTextureFromImage(img);
});
```

**Comment by TheLumaio** [comment]
To the best of my knowledge that's because you need an opengl context to load textures. The new thread doesn't have one.

**Comment by raysan5** [comment]
Hi @TheLumaio! Thanks for the answer! You're right on the assumption!

**Comment by dginu85** [comment]
Hello,
Thanks for your answer.
I need to load not to block the main process in dynamic loading of the asset.
@TheLumaio  @raysan5

**Comment by TheLumaio** [comment]
This is a pretty common problem, a simple google search will lead to a lot of different ways to solve it. You might need to change raylib youself to implement those solutions though unless @raysan5 wants to add it to the framework but I think it's a little out of scope of what raylib was meant to do.

**Comment by Geams** [comment]
@TheLumaio 
<p>You are probably right with "out of scope of what raylib was meant to be".</br>
raylib.com: ".. raylib is a simple and easy-to-use library to <b>learn</b> videogames programming".</br>
In that sense, supporting the development of commercial grade apps is out of scope.</p>
<p>But I think that facilitating the use of OpenGL in c programs should include loading game assets
asynchronously. </br>Raylib should at least include example code that works on all supported platforms.</p>
Personally, I favor examples and templates over bloated API's, that's why I am trying out raylib.</p>

**Comment by TheLumaio** [comment]
That being said, I believe raylib is fully capable of being used for commercial products. Even if raylib doesn't directly contain abstraction layers for certain things like async texture loading you still have all the tools necessary to facilitate that yourself.

**Comment by dginu85** [comment]
Guys, I created a linux distribution based on this library to draw the interface, I created all the components.
The system starts in three seconds.
I can not block myself, for this problem.
This library is fantastic enough complete and works very well.
but for realistic use, you have to download assets dynamically.

Example of a very used application in games:
Thread main -> Draw all;
Secondary Thread -> Capture the camera and return a raw image.

There are thousands of reasons to create textures dynamically.

**Comment by raysan5** [comment]
> Personally, I favor examples and templates over bloated API's, that's why I am trying out raylib.

Agree.

About textures loading in a secondary thread, what do you mean exactly? Two options:

 - Load image in a secondary thread and then upload data to VRAM (texture) in main thread. That's easy.
 - Load image and upload data to VRAM (texture) in secondary thread. Not that easy, [check this info](https://www.khronos.org/opengl/wiki/OpenGL_and_multithreading).

Try to prepare a sample about first method this week (or maybe in the following hours). Leave this issue open.

**Comment by raysan5** [comment]
[loading_multithread.zip](https://github.com/raysan5/raylib/files/1736697/loading_multithread.zip)

Here it is an example of multithreading data loading from disk (it actually writes to disk to simulate the loading wait time because reading from disk is quite fast).

If compiling with MinGW, it requires compilation parameters `-static` to link statically with default pthreads library. 

I'm closing this issue now, please, feel free to reopen it if needed.
