### ISSUE TITLE
[rcore] Allow developers to target high performance GPU without modifying Raylib

### ISSUE THREAD

**Issue by Volcanic-Penguin** [raysan5/raylib#4590]
### Issue description

By default it seems Raylib targets the integrated GPU on hybrid systems, and to target the high performance GPU I had to change this row in the CMake settings..

cmake_dependent_option(GLFW_USE_HYBRID_HPG "Force use of high-performance GPU on hybrid systems" OFF

..from OFF to ON and rebuild Raylib. Since I'm using Raylib with Rust (and this would apply to any non C developer) it would be nice to be able to target the high performance GPU without having to dig into the C code. One of my computers has an integrated GPU that outputs 4K30 and a high performance GPU that outputs 4K60, and I wouldn't want my game to be capped to 30 fps for no good reason. 

Personally I think Raylib should target the high performance GPU by default since Raylib is meant for game development and games generally need better performance than other types of applications. But if others disagree with this, it would be nice to at least have some sort of function exposed in the Raylib library to control this, like `TargetHighPerformanceGPU()` or something that you could run before `InitWindow()`

Thanks for reading!

### Environment

Raylib 5.0 with Rust (raylib-rs)
Windows 10
Platform backend: DESKTOP (GLFW)
Renderer: Intel(R) HD Graphics 530 / NVIDIA GeForce GTX 960M

**Comment by asdqwe** [comment]
> Personally I think Raylib should target the high performance GPU by default since Raylib is meant for game development and games generally need better performance than other types of applications.

I disagree with this, it should not be enabled by default. Hybrid GPU schemas are very driver/kernel/OS dependent, vary wildly in implementation and are borderline broken most of the time, specially across platforms (typing this from a system where I had to BIOS/EFI disable `Nvidia GF119M` just to get any ressemblance of consistency). I'm not against allowing `GLFW_USE_HYBRID_HPG`, but if the dev wants it, should be exclusively up to him to deal with it.

> But if others disagree with this, it would be nice to at least have some sort of function exposed in the Raylib library to control this, like `TargetHighPerformanceGPU()` or something that you could run before `InitWindow()`

Not sure if that's possible, since that's a compile-time option ([doc](https://www.glfw.org/docs/3.3/compile.html#compile_options_win32)). Also that feature is Windows and GLFW only, so no other platform would use it.

**Comment by raysan5** [comment]
@asdqwe Completely agree with the stated points.

**Comment by TrueSgtMonkey** [comment]
> [@asdqwe](https://github.com/asdqwe) Completely agree with the stated points.

Has this been added to RayLib? Unsure what the function is called if it has been.

**Comment by orcmid** [comment]
@raysan5 

>>> @TrueSgtMonkey Personally I think Raylib should target the high performance GPU by default since Raylib is meant for game development and games generally need better performance than other types of applications.

> > [@asdqwe](https://github.com/asdqwe) Completely agree with the stated points.
> 
> Has this been added to RayLib? Unsure what the function is called if it has been.

This is tricky.  I am unclear why this issue was closed without comment.  I have a GPU hybrid laptop and it is amazing how much apps, especially games, fumble when I have it shared with a large gamer monitor.  I gave up on that and upgraded to a desktop tower PC desktop  where using the HDMI port connection from the RTX GPU board makes HP display usage automatic.

I agree that scaling and monitor choices need to be dealt with in a platform-sensitive manner, probably before raylib `InitWindow`.  I've made a stab at that with regard to higher-resolution monitors, but it makes too much work for the app developer to adapt to the scaling for such displays at run-time.  This is tangential to the Hybrid GPU case, yet they sort of go together.
