### ISSUE TITLE
[rcore] SetGamepadVibration() doesn't work (Windows)

### ISSUE THREAD

**Issue by LxeC** [raysan5/raylib#4613]
✅ I tested it on latest raylib version from master branch
✅ I checked there is no similar issue already reported 
✅ I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki) 
✅ My code has no errors or misuse of raylib 

### Issue description

Using `GamepadSetVibration()` does not seem to work under Windows. 
Instead it shows a warning: `WARNING: GamepadSetVibration() not available on target platform`.

### Environment

- Windows 11
- Xbox One Gamepad, SpeedLink XEOX Pro (Both support XInput)
- Raylib 5.5

### Code Example

```cpp
#include "raylib.h"

int main(void)
{
    SetConfigFlags(
        FLAG_VSYNC_HINT |
        FLAG_MSAA_4X_HINT
    );
    
    InitWindow(1280, 720, "Test Gamepad Vibration");
    InitAudioDevice();
    SetTargetFPS(60);

    while (!WindowShouldClose())
    {
		if (IsKeyPressed(KEY_SPACE))
		{
			SetGamepadVibration(0, 0.5, 0.5, 1);
		}

		BeginDrawing();
		ClearBackground(RAYWHITE);
		EndDrawing();
    }

    CloseAudioDevice();
    CloseWindow();
    return 0;
}
```

**Comment by asdqwe** [comment]
Unfortunately `GLFW` doesn't have gamepad rumble/haptic/vibration support yet ([ref](https://github.com/glfw/glfw/issues/57)).

If you absolutely need that feature on Desktop, you'll have to use `PLATFORM_DESKTOP_SDL`.

**Comment by raysan5** [comment]
Yeap, I'm afraid it is a GLFW backend issue...

**Comment by superroket169** [comment]
Regarding this GLFW backend issue — since GLFW hasn't supported this for a long time, I looked into a way to handle it without touching GLFW at all:

bypass GLFW entirely for the write path, using the evdev EVIOCSFF/EVIOCRMFF ioctls and the FF_RUMBLE effect type directly, while leaving GLFW's existing read path (axes/buttons) completely untouched.

I built a working version of this approach in a personal project, though I used FF_CONSTANT there instead of FF_RUMBLE — repeatedly re-uploading a constant-force effect each frame to simulate vibration in software, rather than using the kernel's native rumble effect. I tested this on a Logitech wheel and it worked. Adapting it to FF_RUMBLE for SetGamepadVibration's two-motor model should be straightforward.

The part I'm least sure about is matching a GLFW joystick index to the correct /dev/input/eventX node. I'm considering /dev/input/by-id (matching by VID:PID against GLFW's joystick GUID) rather than GLFW's joystick GUID directly, but wanted to check whether this would be an acceptable approach before putting together a full PR.

Would this general direction be welcome for the GLFW backend?
