### ISSUE TITLE
RAYLIB_PATH for templates are incorrect.

### ISSUE THREAD

**Issue by ismyhc** [raysan5/raylib#473]
I just pulled master as of today Feb 18, 2018 and noticed a problem with the RAYLIB_PATH in each of the MakeFile for the templates. The don’t compile as is on raspberry pi.

Its currently:
```
RAYLIB_PATH = ..\..
```
Changed to the following and compilation works.
```
RAYLIB_PATH = ../..
```

**Comment by raysan5** [comment]
Thanks @ismyhc for detecting this issue. Reviewed in commit https://github.com/raysan5/raylib/commit/7e32a627e88035c21cd16daddca128a9b6024de9

**Comment by RDR8** [comment]
A question that's really about RAYLIB_RELEASE_PATH. How do you feel about getting the full path with something like:

    RAYLIB_PREFIX ?= ../..
    RAYLIB_PATH    ?= $( realpath $(RAYLIB_PREFIX)) ?

realpath may be specific to GNU make, which is fine on Linux. I think it's gmake on BSD.
Anyway, I'm using a form of that successfully on my fork. Having the fully qualified path would allow ldconfig to prepare RAYLIB_RELEASE_PATH for run-time linking to the freshly built libraylib.so staged in $(RAYLIB_PATH)/release/libs/linux. It's not really necessary since folks should be `make install`ing anyway. I don't know what other effects it might have. Thanks.
