### ISSUE TITLE
[core] Expose available video modes supported by monitor

### ISSUE THREAD

**Issue by srseil** [raysan5/raylib#514]
It would be nice if one could query the available video modes (mostly resolution and refresh rate) supported by the monitor. This is already possible through GLFW (see http://www.glfw.org/docs/latest/monitor_guide.html), so it should be fairly straightforward to expose just that through the API. The obvious use case for this is that the user can pick and choose the window resolution being used in the game/application itself, like in a typical settings menu, and that he is thereby presented with all the different video modes supported by his monitor.

**Comment by raysan5** [comment]
I tried to implement this function as following:
```c
RLAPI Vector2 *GetMonitorVideoModes(int *count); // Get current monitor available resolutions
```
It works ok (despite using Vector2 as storage and not registering refresh-rate), but after some testing I decided not to add it to the API.

In my tests, it returns up to 86 possible configurations for the monitor, some of them imply framebuffer distortion due to not matching monitor aspect ratio. Actually, raylib already deals with that on [window initialization](https://github.com/raysan5/raylib/blob/master/src/core.c#L1928) and framebuffer setup. For fullscreen, raylib tries to provide the most similar videomode to the requested screen resolution. 

If a more detailed control of videomodes is required, I just recommend `#include <GLFW/glfw3.h>` and use the provided functionality directly, not through a raylib wrapper. After all GLFW3 is already available through `libraylib.a`, not additional linkage is required.

Here it is an example:
```c
#include "raylib.h"
#include <GLFW/glfw3.h>

int main()
{
    InitWindow(800, 450, "monitor videomodes");

    int count;
    GLFWvidmode* modes = glfwGetVideoModes(glfwGetPrimaryMonitor(), &count);

    SetTargetFPS(60);

    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        BeginDrawing();
            ClearBackground(RAYWHITE);
            for (int i = 0; i < count; i++) DrawText(FormatText("%i x %i", (int)modes[i].width, (int)modes[i].height), 10, 15*i, 10, DARKGRAY);
        EndDrawing();
    }

    CloseWindow();        // Close window and OpenGL context

    return 0;
}
