### ISSUE TITLE
[rlgl] Internal buffers overflow

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#530]
Internal buffers have a size limit for better performance but if trying to accumulate more vertex than buffer-limit gives a buffer overflow ERROR.

There is already a check mechanism in `rlEnd()` but doesn't seem to be enough, specially when drawing polygons because number of vertex accumulated by `DrawPoly()` are not properly counted before `rlEnd()`.

This system should be reviewed.

**Comment by sherjilozair** [comment]
I looked at this issue, and came up with the following proposal for a solution:

I think the call to `rlglDraw` should be in `rlBegin` instead of `rlEnd`. This is because when the call to `rlBegin` happens we know how many vertices are going to be added. And if know that we can't fit all those vertices to the buffer, then we should call `rlglDraw`, empty the buffers, and then continue with adding the current shape.

This would adding a new argument to `rlBegin`, i.e. `n_vertices`, which allows the caller to specify how many vertices are going to be added. If `vcounter + n_vertices > MAX_TRIANGLES_BATCH `, then we call `rlgldraw`.

There are other solutions also available, such as to double `MAX_TRIANGLES_BATCH`, and then checking to see if `vcounter` exceeds `MAX_TRIANGLES_BATCH/2`.

Another method would be to dynamically allocate memory, but this is probably a very bad idea.

**Comment by raysan5** [comment]
Hi @sherjilozair, by default, we don't know in `rlBegin()` how many vertex are going to be drawn, we just set the drawing mode. That function can not be modified because it mimics `glBegin()` from OpenGL 1.1.

I think better solution could be launching `rlglDraw()` in `rlVertex3f()` but it's not that easy because we can miss some drawing triangles if max limit is reached at the middle of a draw...

**Comment by sherjilozair** [comment]
Wouldn't drawing graphics like this will cause partial shapes to be drawn on the screen?

**Comment by raysan5** [comment]
Issue corrected with commit https://github.com/raysan5/raylib/commit/ca690688149e90b8fc92713d31b17330f9ea8b43

A new function `rlCheckBufferLimit()` was added to check buffer limits before sending a big bunch of vertex.

I checked it and seems to work ok but feel free to re-open it if still fails in some situation.
