### ISSUE TITLE
[core] core_basic_window.c maxes out one cpu core

### ISSUE THREAD

**Issue by Danilodum** [raysan5/raylib#576]
Is this because of the SUPPORT_BUSY_WAIT_LOOP define? Can someone explain why this is the default?

**Comment by raysan5** [comment]
Related issue https://github.com/raysan5/raylib/issues/415

It's the default because is the safest and most accurate way in most platforms instead of dealing with system interrupts... but so the define, in case someone needs to change that behaviour. By the way, a 100% CPU usage doesn't mean that CPU can run other 1000 processes smoothly at the same time... lots of games work this way.

**Comment by Danilodum** [comment]
Idk, why I didn't find that related issue, thanks!
