### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by clix9** [raysan5/raylib#59]
Hi, out of curiosity, can there be support for the following features?

- OpenGL ES 1.1 support instead of OpenGL 1.1, which can allow the use of VBO's
- Render to Texture for OpenGL 3 / ES 2
- Lighting (and for OpenGL 3 / ES 2, a default shader that some supports lighting features)
- Light mapping (a second set of UV's in the Vertex Buffer)
- Generation of normals and UV's for spheres, boxes, planes, and other primitives

**Comment by raysan5** [comment]
Hello clix9! wow, that's a lot of features request! what are you building with raylib?!? :)

> OpenGL ES 1.1 support instead of OpenGL 1.1, which can allow the use of VBO's

No plans to support OpenGL ES 1.1. I supported OpenGL 1.1 because raylib 1.0 used OpenGL 1.1, since raylib 1.1 a new internal module [rlgl](https://github.com/raysan5/raylib/blob/master/src/rlgl.c) was created to abstract the graphic API and support OpenGL 3.3+ and OpenGL ES 2.0. Even the lowest-end devices I have (Raspberry Pi) support OpenGL ES 2.0. I didn't find the need to support a lower OpenGL ES version, why do you need this feature? Any special device?

> Render to Texture for OpenGL 3 / ES 2

Since raylib 1.3 rendering to texture is used internally for postprocessing shaders (using FBOs), actually, in the last commit or so I revised the code to make easier the FBO creation and management. I'm working on Oculus Rift support and I also need this feature but I don't know yet how to expose this feature to the user, any suggestion?

> Lighting (and for OpenGL 3 / ES 2, a default shader that some supports lighting features)

Yes, it's in my list: https://github.com/raysan5/raylib/issues/51

> Light mapping (a second set of UV's in the Vertex Buffer)

Not yet start thinking on lightmapping but it would be a great addition...

> Generation of normals and UV's for spheres, boxes, planes, and other primitives

Actually I'm working on a set of simple functions to generate procedural content (3d primitives and images), for the moment, no normals or uvs are planned but it would be a future addition... Any help is appreciated! :D

**Comment by clix9** [comment]
> What are you building with raylib?!?

I'd like to make a fully featured, cross platform game with Raylib, but it would need certain features.

> I didn't find the need to support a lower OpenGL ES version, why do you need this feature? Any special device?

I believe many netbooks still have only support up to OpenGL 1.4 on Windows, and many of the older smart phones have poor or limited OpenGL ES 2.0 support (i.e. shaders can be more expensive). Being that OpenGL ES 1.1 is a subset of OpenGL 1.4, you could use much of the same vertex buffer code.

> ..I revised the code to make easier the FBO creation and management... I also need this feature but I don't know yet how to expose this feature to the user, any suggestion?

Perhaps it's possible to extend the Texture2D struct to include flags and other information about whether it is a render to texture, then have functions to create, bind, and destroy the texture.

> Yes, it's in my list: #51

Will this lighting interface be available to the OpenGL 1.x codebase?

Thanks.

**Comment by raysan5** [comment]
Glad to hear you are planning to use raylib for a fully featured project!

About OpenGL ES 1.1, I've analyzing the cost of adding it and despite it's not too complicated it would take me some time; right now I prefer to invest that time in adding new modern features rathen than supporting old systems. Looking at [Android dashboards](http://developer.android.com/about/dashboards/index.html#OpenGL) for OpenGL ES 2.0 support, right now, most of the market phones support that version.

About the FBO exposing, I'll probably follow the XNA approach with RenderTargets or something similar.

The planned lighting sample will be done with shaders so it won't be available for OpenGL 1.1. The way to manage lighting on older OpenGL versions is quite different (and really limited).

**Comment by clix9** [comment]
Thanks,

That sounds fine. I'll likely consider forking the project and adding my own OpenGL ES 1.1 support.
