### ISSUE TITLE
[audio] Popping sound looping audio stream

### ISSUE THREAD

**Issue by fabslab** [raysan5/raylib#652]
I have a short sound that I want to loop. Unfortunately I can't set Sound instances to loop with raylib so I loaded it as a Music instance but whenever it loops to the beginning there is a popping sound at the start. I didn't have this issue with MonoGame (which I am porting my small game from) so I don't think it is the fault of the audio file.
The audio file is
https://github.com/fabslab/DeathRaceC/blob/master/DeathRace/Content/Audio/engine-running.ogg 

I'm running raylib 2.0 on windows and mac and experienced the issue on both.

As an aside, it seems strange that the LoadMusicStream doesn't support wav files while LoadSound does.

**Comment by fabslab** [comment]
As a workaround I made a new audio file that has the original audio looped multiple times in itself to reduce how often the pop is heard in game. It would great to be able to loop Sound instances still though for small files like mine.

**Comment by raysan5** [comment]
It seems related to loosing one frame with no proper buffers update or incomplete buffer that get's consumed too fast... it could take me some time to review it, maybe @mackron could help on that?

About `wav` support on `LoadMusicStream()`, it is on my TODO list... just couldn't find the time to add it yet...

**Comment by mackron** [comment]
Unfortunately I don't have time to properly fix this right at this second, but I've had a very quick look at the code, and I _think_ I might know what's going on. In this section here https://github.com/raysan5/raylib/blob/master/src/audio.c#L1725-L1732 there is some logic that updates the stream, and then checks the number of remaining samples and marks the stream as ending if the remaining count is <=0. Then immediately after that loop it checks the `streamEnding` variable and stops and restarts the stream before that very last update has a chance to actually be output to the speakers: https://github.com/raysan5/raylib/blob/master/src/audio.c#L1739-L1753. To put it simply, I think it's updating the very last part of the music stream, but then immediately stopping it before it's had a chance to output to the speakers.

The same logic exists for the OpenAL backend, so I don't _think_ using `USE_OPENAL_BACKEND` will make a difference, but it could be worth a shot as a temporary work around.

As a side note, what's stopping you from removing the OpenAL backend entirely? I know that you weren't happy with the size of the Emscripten build (I think there might be a few latency issues there as well) - is that the only thing? I only ask because having looked through this code it's reminded me that I would really like to do a big clean up on this (basically a complete rewrite if you're open to it), but I don't want to be doing work for two backends - one is already enough work! :)

**Comment by raysan5** [comment]
Hey @mackron! Thank you very much for the super-quick review! I see the issue, I'll try to fix it this week! :)

About OpenAL, yeah, my only concern was Emscripten size but... probably by now OpenAL backend could be completely removed. 

I like the API but, yes, I'm open to a complete rewrite or changes, I also feel it could be greatly improved, I originally wrote it 5 years ago...

**Comment by mackron** [comment]
I wouldn't make drastic changes to the public API (though a small number of changes could perhaps be necessary), but the internals need a bit of work. I'll email you at some point in the future and work out a plan.

**Comment by raysan5** [comment]
That's great David! No worries, take your time, I'm also very busy at the moment. :)

**Comment by raysan5** [comment]
Just for the record, OpenAL has been completely removed in commit https://github.com/raysan5/raylib/commit/c2aa1fed7b4b75c9bb560ffb9ff6cd8c99d7dd41

**Comment by mackron** [comment]
Cool! I have a few ideas on improving the audio engine. I'm thinking maybe late November, early December I will contact you and go through them if you're open to it.

**Comment by raysan5** [comment]
@mackron Sure! Let me know!

**Comment by raysan5** [comment]
Popping shouldn't occur anymore.
