### ISSUE TITLE
[audio] Raspberry Pi 3 B failed to initialize audio context

### ISSUE THREAD

**Issue by flashjaysan** [raysan5/raylib#654]
When I try to execute one (I tried all of them) of the audio examples, I got an error : failed to initialize audio context.
I'm running it on a Raspberry Pi 3 B model in shell mode.

**Comment by anatagawa** [comment]
Audio context failed to open.

RPI3 B here, and HDMI with Raspbian stretch.
All examples with audio failed. No errors after make with and without desktop.

**Comment by mackron** [comment]
Thanks. I'll try testing with a HDMI device as soon as I can get a chance.

**Comment by mackron** [comment]
@anatagawa Have you been able to test with the 3.5mm jack by any chance? Or a USB device? Also, if it's not too inconvenient, would you be able to compile with `#define MAL_DEBUG_OUTPUT` (either in code or on the command line) and post your results?

@raysan5 I think you should enable the null backend (get rid of `#define MAL_NO_NULL` from mini_al.c) so that initialization doesn't just outright fail. This should at least allow the programs to run, albeit without any sound.

**Comment by raysan5** [comment]
Checked on my Raspberry Pi 3, OS Raspbian 9 (stretch), raylib compiled and running on native mode (no X-windows), HDMI output. It works great. 

Audio initialization output:
```
[mini_al] Endian:  LE
[mini_al] SSE2:    NO
[mini_al] AVX2:    NO
[mini_al] AVX512F: NO
[mini_al] NEON:    NO
[ALSA] Default Playback Device (Playback)
  Format:      32-bit IEEE Floating Point -> 16-bit Signed Integer
  Channels:    2 -> 2
  Sample Rate: 44100 -> 44100
INFO: Audio device initialized successfully: Default Playback Device
INFO: Audio backend: mini_al / ALSA
INFO: Audio format: 32-bit IEEE Floating Point -> 16-bit Signed Integer
INFO: Audio channels: 2 -> 2
INFO: Audio sample rate: 44100 -> 44100
INFO: Audio buffer size: 2200
INFO: [resources/sound.wav] WAV file loaded successfully (44100 Hz, 32 bit, Mono)
```
My Raspbian could be a bit outdated, I'm updating it now and I'll do some more tests. Maybe issue is related to X-Windows compilation mode?

**Comment by mackron** [comment]
Hmm, that's weird... I'm wondering if it's failing in this code in mini_al:
```
pContext->alsa.asoundSO = mal_dlopen("libasound.so");
if (pContext->alsa.asoundSO == NULL) {
    return MAL_NO_BACKEND;
}
```
Perhaps @anatagawa and @flashjaysan don't have "libasound.so" and instead have only "libasound.so.2"? Are you able to check if "libasound.so" exists on your system?

In the mean time, I've pushed an update to mini_al's dev branch with a change that checks for "libasound.so.2" just in case. By the way @raysan5, make sure you don't use MAL_DEBUG_OUTPUT in your normal builds because it spams messages to stdout from the audio callback :)

**Comment by mackron** [comment]
Yeah I reckon I would have also installed the development packages. Unfortunately I don't have access to my RPI at this very moment, but are you able to check which "libasound.so" symlinks you have on your system? On my Linux Mint virtual machine I have both "libasound.so" and "libasound.so.2" which point to "libasound.so.2.0.0". I'm just wondering if there's any others I should be checking for...

**Comment by raysan5** [comment]
Ok, checked... it took me a while to find the library location... not very used to Linux... 

Found it on `/usr/lib/arm-linux-gnueabihf`:
```
libasound.so
libasound.so.2
libasound.so.2.0.0
```
There is no other symlink file there.

**Comment by anatagawa** [comment]
for me, only libasound.so.2 and libasound.so.2.0.0 , missing libasound.so , maybe this the problem

**Comment by anatagawa** [comment]
```
sudo apt-get install --no-install-recommends raspberrypi-ui-mods lxterminal gvfs
sudo apt-get install mesa-common-dev
sudo apt-get install libgl1-mesa-dev
sudo apt-get install libxcursor-dev
sudo apt-get install libxinerama-dev
sudo apt-get install libxrandr-dev
sudo apt-get install libxi-dev
sudo apt-get install libasound2-dev
```

with that, all works, different from the wiki page :)

**Comment by anatagawa** [comment]
I have tried compil raylib on DietPI , need other things :

-- sudo apt-get libraspberrypi-dev raspberrypi-kernel-headers
-- sudo apt-get install build-essential

and works very well

**Comment by raysan5** [comment]
@anatagawa thank you very much for the report!

Nice to know it works on `DietPi`! :D

**Comment by mackron** [comment]
Yeah that'll definitely be the problem. Normally libasound2-dev should not be required - it was a bug in mini_al which raylib uses internally.

**Comment by anatagawa** [comment]
but , there is a problem :)

i play music with PlayMusicStream.
- time length of 31s.
- loop is true by default

the music start correctly, played, and after 15sec, rewind.
i cant eart the last 15 sec.

same things with time length of 3min. after 1m30s, rewind.

**Comment by mackron** [comment]
Yeah that sounds like the total sample count of your audio source isn't getting multiplied by the channel count. What file format is your audio source?

**Comment by raysan5** [comment]
@anatagawa @mackron just touch that a while ago... yeah, it seems sample count is not considering channels properly... I'll review it tomorrow...

**Comment by mackron** [comment]
@raysan5 Yeah I'm pretty sure this is something to do with `music->totalSamples` not getting calculated correctly. There's some inconsistencies that I noticed, though. With MP3 you are setting it to the total sample count (total frame count * channels), whereas for Ogg and FLAC you are setting it to just the total frame count, so I reckon this bug is also happening with FLAC. I think you need to change the following (needs testing):

```
music->totalSamples = (unsigned int)stb_vorbis_stream_length_in_samples(music->ctxOgg);
to
music->totalSamples = (unsigned int)(stb_vorbis_stream_length_in_samples(music->ctxOgg) * info.channels);
```
and
```
music->totalSamples = (unsigned int)music->ctxFlac->totalSampleCount/music->ctxFlac->channels;
to
music->totalSamples = (unsigned int)music->ctxFlac->totalSampleCount;
```
It looks like stb_vorbis is using the wrong terminology for `stb_vorbis_stream_length_in_samples()`. It's misleading - what it's _actually_ returning is the total number of PCM frames. You can see this by looking at the implementation of `stb_vorbis_stream_length_in_seconds()`.

**Comment by raysan5** [comment]
@mackron thanks for locating the issue! Corrected on commit https://github.com/raysan5/raylib/commit/83d90c6e49f31b1e43d8046c7a35c84a9446da49.

**Comment by raysan5** [comment]
@anatagawa Updated raylib Wiki with new info.
