### ISSUE TITLE
Drawing a rectangle with a mismatched sign for width and height does not work

### ISSUE THREAD

**Issue by redstonedash** [raysan5/raylib#671]
if you write
`DrawRectangle(100,100,-100,-100,BLACK);`
ray lib will draw a rectangle that looks the same as
`DrawRectangle(0,0,100,100,BLACK);`
however if you write
`DrawRectangle(100,100,-100,100,BLACK);`
or
`DrawRectangle(100,100,100,-100,BLACK);`
no rectangle will be rendered.

**Comment by raysan5** [comment]
Yeah, that's the expected behaviour. You're providing a negative width and height for the size of the rectangle.

Actually, first form shouldn't work...

**Comment by jkaup** [comment]
Is there a reason for that to be the expected behavior? It would make some cases a lot simpler if the width and/or height could be negative.

For example when implementing a drag selection box that updates when you move the mouse, you would only need to set the X and Y of the rectangle when pressing the mouse button and then updating the width and height with the new mouse positions when it moves.

The code becomes much more complex when negative width/height are not allowed as you need to also change the X and Y when the end points move to the left/up of the starting XY.

**Comment by raysan5** [comment]
@jkaup Personally I find more logical to not support negative width and height for a rectangle drawing.

**Comment by jkaup** [comment]
Fair enough, it makes sense from the mathematical perspective. Thanks for your response.
