### ISSUE TITLE
[build] Support Windows builds on Travis CI

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#681]
As per latest news, Travis CI has added [Windows build support](https://blog.travis-ci.com/2018-10-11-windows-early-release).

Right now Windows builds are managed with AppVeyor, it works great, but maybe in a future it could be a good idea to unify all platforms building in a single CI system.

This issue is open for discussion on this topìc.

**Comment by raysan5** [comment]
Tried to implement it on commits https://github.com/raysan5/raylib/commit/d2e861fdce806294e569f1afef28e06c30509365 and https://github.com/raysan5/raylib/commit/34d110bb3e327f86def2fc6801e8b17a33188114... but still failing...

**Comment by a3f** [comment]
As you said AppVeyor works and I don't see what's to gain in return for the effort of getting the same targets to build on Travis. I have however fixed your changes to travis.yml, CMake was generating a Visual Studio project not a Makefile, that's why it was failing to build with mingw32-make.

You can take a look at the appveyor.yml to see how to configure CMake to select MinGW instead.

**Comment by raysan5** [comment]
Hi @a3f! Thank you very much for looking into this! It was just a test, trying to figure out how Travis CI worked. I'll close this issue for now. :)

**Comment by a3f** [comment]
Something else to consider, AppVeyor CI runs in parallel to the Travis CI build, so someone trying to use CI to sanity check their commits will have to wait longer if we exclusively use Travis CI.. Of course, there is the additional hassle of registering with one more CI provider, but that's a one-time cost. AppVeyor also seems faster, building raylib with Visual Studio 2017 in 4 minutes compared with 2 minutes for Travis CI.
