### ISSUE TITLE
[core] Problems with HiDPI on Mac

### ISSUE THREAD

**Issue by jdmoreira** [raysan5/raylib#737]
The following code
```c
int main() {
    int screenWidth = 100;
    int screenHeight = 100;

    InitWindow(screenWidth, screenHeight, "");
    SetTargetFPS(60);

    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(WHITE);
        for (int x = 0; x <= screenWidth; x++) {
            DrawLine(x, 0, x, screenHeight, BLACK);
        }
        EndDrawing();
    }

    CloseWindow();
    return 0;
}

```

produces the following screen

<img width="116" alt="screenshot 2019-01-24 at 22 33 46" src="https://user-images.githubusercontent.com/385456/51786865-d2e53f00-216a-11e9-9aae-855c0c2c70c9.png">

I would expect the whole screen to be black. Seems like it could be an HiDPI problem?

**Comment by raysan5** [comment]
Have you tried with other screen sizes?

On Windows HiDPI device it works ok.

**Comment by a3f** [comment]
I've got the same issue on macOS Mojave with 600x600 screen size as well.

**Comment by jdmoreira** [comment]
Yes, I've tried multiple screen sizes. It's unrelated to screen size I think.
Surprisingly `DrawLineEx` works well even with thickness of `1.0`

I can try to dig deeper and see what I can find

**Comment by raysan5** [comment]
Ok, that's probably related to OpenGL lines drawing and macOS driver implementation.

`DrawLineEx()` works ok because it uses rectangles to draw the line, so thick is explicitly defined. Whne drawing a line, thick depends on OpenGL implementation... just think about it like lines are drawn with an offset of -0.5 pixels to fit the expected pixel position...

Not an easy solution for this problem...
