### ISSUE TITLE
[physac] Collision handling and performance

### ISSUE THREAD

**Issue by ChrisDill** [raysan5/raylib#743]
I am not sure how to respond to collisions. Found this issue https://github.com/victorfisac/Physac/issues/31 recommending to check collision seperately. Doesn't that lead to duplicated checks?

From a quick look, it checks every one against every other. Thats fine for a few objects but I can see that being a issue with more objects.

**Example of what I am trying to do**
My player can shoot bullets at enemies. I want a callback when a bullet hits a enemy so I can destroy the bullet and apply damage.

**Comment by raysan5** [comment]
Hi @ChrisDill, not sure what's the performance for lots of objects (maybe several hundreds?), probably @victorfisac can give us some numbers?

**Comment by SolarLune** [comment]
@ChrisDill That doesn't sound like an absurd number of collision checks. I feel like you would probably be fine with a very ignorant collision system unless you were doing checks between hundreds, or even thousands of objects. I should know because I made a very ignorant collision system called [Resolv](https://github.com/SolarLune/resolv), haha.

It probably would be best to try following the recommendation on using Physac and see if it fills your needs efficiently. If not, then you can see about refactoring and optimizing.

**Comment by ChrisDill** [comment]
@SolarLune Thanks thats a good point. It is easy to overthink it. I like your physics library design!
I guess my main issue is responding to collisions. Maybe a example could be useful here.

**Comment by ChrisDill** [comment]
Update on this issue. Testing using physac_demo, performance lags after 15-20 bodies. I think its because the cost of all the manifolds being generated leading to alot of costly collision checks.

One solution I have seen with other libraries is using axis alligned bounding boxes first to see if a object might be colliding then checking for a more detailed collision afterward. The axis alligned check is cheaper and would allow for more objects.

**Comment by raysan5** [comment]
Closing it. I'm afraid I can not give support to `physac` library...
