### ISSUE TITLE
[models] MAX_BATCH_ELEMENTS overflow on DrawSphere()

### ISSUE THREAD

**Issue by bjornwah** [raysan5/raylib#800]
There seems to be an issue when drawing many spheres using the DrawSphere function. Calling DrawSphere 18 times works but after that the program exits with the following error message:  

`ERROR: MAX_BATCH_ELEMENTS overflow`

The message comes from here; starting at line 1136 in rlgl.h: 

```
    if (vertexData[currentBuffer].vCounter < (MAX_BATCH_ELEMENTS*4))
    {
        vertexData[currentBuffer].vertices[3*vertexData[currentBuffer].vCounter] = vec.x;
        vertexData[currentBuffer].vertices[3*vertexData[currentBuffer].vCounter + 1] = vec.y;
        vertexData[currentBuffer].vertices[3*vertexData[currentBuffer].vCounter + 2] = vec.z;
        vertexData[currentBuffer].vCounter++;

        draws[drawsCounter - 1].vertexCount++;
    }
    else TraceLog(LOG_ERROR, "MAX_BATCH_ELEMENTS overflow");
```

It seems that vCounter is increased by 1727 for each call to DrawSphere, and at some point it will exceed MAX_BATCH_ELEMENTS*4, defined by:

`    #define MAX_BATCH_ELEMENTS            8192`

([19 calls x 1727 = 32813] > [4x 8192 = 32768])

Code example reproducing the issue (Tested using MSVC 2017 x64)

```
int main(int /*argc*/, char** /*argv*/)
{
    int screenWidth = 1920 / 2;
    int screenHeight = 1080 / 2;
    InitWindow(screenWidth, screenHeight, "star PAK ATTACK");

    Camera3D camera = { 0 };
    camera.position = { -10, 0.0f, -3.0f };
    camera.target = { 0.0f, 0.0f, 0.0f };
    camera.up = { 0.0f, 1.0f, 0.0f };
    camera.fovy = 45.0f;
    camera.type = CAMERA_PERSPECTIVE;

    Vector3 pos = { 0 };
    while (!WindowShouldClose())
    {
       BeginDrawing();
       BeginMode3D(camera);
       ClearBackground(RAYWHITE);
       for(unsigned int n = 0; n < 19; n++)
       {
          DrawSphere(pos, 1.0f, RED);
       }
       EndMode3D();
       EndDrawing();
    }
}
```

Output:

> 
> INFO: Initializing raylib 2.5-dev
> INFO: Display device initialized successfully
> INFO: Display size: 1920 x 1080
> INFO: Render size: 960 x 540
> INFO: Screen size: 960 x 540
> INFO: Viewport offsets: 0, 0
> INFO: GLAD: OpenGL extensions loaded successfully
> INFO: OpenGL 3.3 Core profile supported
> INFO: GPU: Vendor:   Intel
> INFO: GPU: Renderer: Intel(R) HD Graphics 530
> INFO: GPU: Version:  3.3.0 - Build 21.20.16.4550
> INFO: GPU: GLSL:     3.30 - Build 21.20.16.4550
> INFO: Number of supported extensions: 231
> INFO: [EXTENSION] DXT compressed textures supported
> INFO: [EXTENSION] ETC2/EAC compressed textures supported
> INFO: [EXTENSION] ASTC compressed textures supported
> INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
> INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
> INFO: [TEX ID 1] Base white texture loaded successfully
> INFO: [SHDR ID 1] Shader compiled successfully
> INFO: [SHDR ID 2] Shader compiled successfully
> INFO: [SHDR ID 3] Shader program loaded successfully
> INFO: [SHDR ID 3] Default shader loaded successfully
> INFO: Internal buffers initialized successfully (CPU)
> INFO: Internal buffers uploaded successfully (GPU)
> INFO: OpenGL default states initialized successfully
> INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
> INFO: [TEX ID 2] Default font loaded successfully
> ERROR: MAX_BATCH_ELEMENTS overflow
> 
>

**Comment by ProfJski** [comment]
Hello, Raysan5!  First off, let me say that I love this library.  I'm an amateur programmer and I hunted for a while for a simple way to present 3D graphics without coding a ton of OpenGL.  I mostly do many-body physics and fractals projects.  I just downloaded Raylib and it has been great so far.  Thank you so much!!

I noticed the same issue as @bjornwah .  18 spheres is the limit with DrawSphere().  If I use DrawSphereEx() or DrawSphereWires() and turn down the number of rings and slices, I can get maybe fifty.  Yet I'm able to push 10,000 DrawCube() calls each frame without a problem.  The FPS drops to about 30, but that's not an issue for me.  I presume that means each sphere creates _a lot_ of vertices?

My platform: Debian 9, Gnome, Xorg, Mesa, Intel Skylake quad-core, Code::Blocks.  AMD Polaris 10, Gallium 0.4.  Everything initializes happily.

From other threads, it looks like changing the MAX_BATCH_ELEMENTS value at line 104 in rlgl.h is a possible solution?
https://github.com/raysan5/raylib/blob/01367fcb1e1c9e00a74cbbe146d415fd64110d30/src/rlgl.h

From later in the code, the memory allocation for the batch seems to be here?

      vertexData[i].vertices = (float *)malloc(sizeof(float)*3*4*MAX_BATCH_ELEMENTS);        // 3 float by vertex, 4 vertex by quad
        vertexData[i].texcoords = (float *)malloc(sizeof(float)*2*4*MAX_BATCH_ELEMENTS);       // 2 float by texcoord, 4 texcoord by quad
        vertexData[i].colors = (unsigned char *)malloc(sizeof(unsigned char)*4*4*MAX_BATCH_ELEMENTS);  // 4 float by color, 4 colors by quad
    #if defined(GRAPHICS_API_OPENGL_33)
        vertexData[i].indices = (unsigned int *)malloc(sizeof(unsigned int)*6*MAX_BATCH_ELEMENTS);      // 6 int by quad (indices)
    #elif defined(GRAPHICS_API_OPENGL_ES2)
        vertexData[i].indices = (unsigned short *)malloc(sizeof(unsigned short)*6*MAX_BATCH_ELEMENTS);  // 6 int by quad (indices)

I'm on a desktop platform so I've got tons of memory to spare.  Would there be any problem increasing this limit substantially?  It looks like 20 floats, 16 unsigned chars, and 6 unsigned ints per element get allocated on the stack.  8K times that is a pretty small allocation for me.  Would it break anything else to increase it, say, by a factor of 10x or 100x?

I will try playing around with it, but since I saw this post near the top of the forum, I just wanted to say I am experiencing the same thing.  In the meantime, depending on what you want to render, DrawCubes may be the way to go.

**Comment by bjornwah** [comment]
@ProfJski  If you want a quick workaround you could start with reducing the fidelity of the spheres by reducing slices/rings:

`void DrawSphereEx(Vector3 centerPos, float radius, int rings, int slices, Color color)`

The number of vertices created for each draw call is 

`(rings + 2) * slices * 6`

in the default case, that is (calling DrawSphere):

`18 * 16 * 6 = 1728`

Reducing rings/slices could considerably reduce the number of vertices.  Try with something like 4 rings and 4 slices and see if it looks acceptable for your application. Then you should be able to make 227 spheres without overflow.

**Comment by raysan5** [comment]
`DrawSphere()` function lacks `rlCheckBufferLimits()` check. It's a 10 minuts fix... but I'm out of computer for some days...

**Comment by ProfJski** [comment]
@bjornwah Thank you for the formula!  FWIW, changing MAX_BATCH_ELEMENTS in rlgl.h doesn't alter the limit.  I increased it by a factor of 100x (812900) but it still throws the same error with more than 18 spheres.  raylib.h doesn't include rlgl.h so I guess it's something I need to find and change in the source code and recompile?  My intended use is representing a large number of particles in a gravity simulator: so far about 1,000,000 particles with an OpenCL routine to parallelize the math.  But even 50k-100k would give a decent working model.  So I will use cubes for now!

What perplexes me is that I can push 100,000 DrawCube calls in the same simple program, and it handles that just fine, which is clearly over 8129*4.  I realize DrawCube is probably just passing two vertex vectors to OpenGL (two corners of the cube) vs 1728, but how can it batch 100,000 DrawCube calls just fine?  It's clearly "batching" the spheres somehow, because each one is 1728 vertices, which fit one-at-a-time, and only when the loop tries to draw more than 18 does it fail.  Yet sending 100,000 cubes the same way works--why?  Presuming each cube sends two vertices, 200,000 / 1728 = 57 spheres' worth.  My simple tweak of one of the raylib samples is below.  I just added a camera zoom out.  If one changes the DrawCube call to DrawSphere, it goes from 100,000 being fine, to 18 max.  That's what's odd.

While 100,000 cubes drops my frame rate to 2 FPS (on an AMD Polaris card, RX 570), I don't care about real-time frame rates since I can push screen shots to .png and make a movie afterwards, which is what I'm doing in my current flat 2D SDL approach which does 1M particles about 7 minutes per frame of compute time.  It's an O(n^2) problem, so n=100K renders speedily enough.

In the meantime, there's plenty of other smaller-scale physics sims I can try to implement in raylib.

```
#include "raylib.h"
#include <cmath>

int main()
{
    // Initialization
    //--------------------------------------------------------------------------------------
    int screenWidth = 800;
    int screenHeight = 600;
    int counter=0;

    InitWindow(screenWidth, screenHeight, "raylib [models] example - geometric shapes");

    // Define the camera to look into our 3d world
    Camera camera = { 0 };
    camera.position = (Vector3){ 0.0f, 30.0f, 30.0f };
    camera.target = (Vector3){ 0.0f, 0.0f, 0.0f };
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
    camera.fovy = 45.0f;
    camera.type = CAMERA_PERSPECTIVE;

    SetTargetFPS(60);   // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        counter++;
        camera.position=(Vector3){0.0f,60.0+0.1f*counter,60.0+0.1f*counter};

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(RAYWHITE);

            BeginMode3D(camera);

            for (float x=0.0; x<100000; x+=6.28/72.0) {

                DrawCube((Vector3){30.0*cos(x), 0.25*x, 30.0*sin(x)}, 1.0, 1.0, 1.0, LIME);

                }

                DrawGrid(30.0, 1.0f);        // Draw a grid

            EndMode3D();

            DrawFPS(10, 10);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

The only change I made to the program are these three lines, which overflows beyond 18 spheres in the for-loop:
```
            for (float x=0; x<18.0; x+=1.0) {

                DrawSphere((Vector3){30.0*cos(x), 0.25*x, 30.0*sin(x)}, 1.0, LIME);

                }
```

Since I write code in relatively few leisure hours, it might take me a while to look at the source code.

Cordially,
ProfJski

**Comment by ProfJski** [comment]
@raysan5 Thanks so much! I'll definitely contribute for your efforts.  I was trying out CINDER earlier, but the dynamic library approach was too hard for me to get going with Code::Blocks and I didn't look forward to working outside an IDE in only Cmake.  So I kept looking.  Raylib is so much easier to get going, and tailored exactly to the needs of doing some graphical physics.

**Comment by raysan5** [comment]
@ProfJski Excuse me for the previous quick explanation, issue has already been corrected on commit https://github.com/raysan5/raylib/commit/8c22f685d168000eabfc994a09c3a2a61f7f633f. Now you can push as many vertex as you want! :)

About `MAX_BATCH_ELEMENTS`, that number is set to define the maximum size of the dynamic buffer that will be uploaded to GPU every frame. You can increase this value as much as you want but this could suppose a bottleneck on the process of sending the vertex data from RAM to VRAM. Current `MAX_BATCH_ELEMENTS` was chosen conservatorily to allow fast data transfer to GPU.

Thanks for using raylib, please, keep me updated with your progress! :)

**Comment by ProfJski** [comment]
Works great!  Thanks so much, @raysan5.  Updated, and it now pushes 10,000 DrawSphere() at 3 FPS, and if I turn down the settings on DrawSphereEx to 4 rings, 4 slices, I can get about 100,000 DrawSphereEx() at about 3 FPS as well.  If I make something attractive it out of it, I'll post it on the forums somewhere.

Do you prefer a one-time donation via PayPal or a slower trickle on Patron?

**Comment by raysan5** [comment]
@ProfJski Glad to read it works! You can post your progress in raylib Discord, in showcase channel!

If you want to contribute with a donation, I prefer PayPal.
