### ISSUE TITLE
[core] Stuttering on animated elements every second or so

### ISSUE THREAD

**Issue by unscrypted** [raysan5/raylib#865]
When I just do a full compile of a fresh download of raylib 2.5 and run demos, I observe stuttering in movement that occurs about once per second.  The clearest example is the shapes_bouncing_ball demo.  I have run this exercise on three computers with varying monitor types.

I also just tried to multiply movement change by GetFrameTime() and to no avail.

**Comment by raysan5** [comment]
@unscrypted Could you try recompiling raylib [uncommenting this line](https://github.com/raysan5/raylib/blob/master/src/config.h#L48) and run the example again?

That line avoids the system-halt time mechanism to sync framerate (it also increases CPU usage).

**Comment by unscrypted** [comment]
Thank you - Yes, that fixes it, but indeed significantly raises CPU usage.  :-\

**Comment by a3f** [comment]
> I have run this exercise on three computers with varying monitor types.

The OS you're on can be relevant.

**Comment by raysan5** [comment]
@unscrypted Ok, nice! At least we detected the issue origin! I'll try to do some tests...

@a3f by the issue details, it's Windows and probably related to WinMM library... :(

**Comment by unscrypted** [comment]
@a3f  I have noted this issue on OSX Mojave 10.14.5 and Windows 10, if that helps.

**Comment by flashback-fx** [comment]
Can confirm this also happens on KDE. I noticed it but I thought it was related to what this -> https://github.com/tildearrow/kwin-lowlatency is trying to fix. Compiling with SUPPORT_BUSY_WAIT_LOOP makes the stutter go away as well.

**Comment by raysan5** [comment]
Thanks for your answers, it seems a generalized issue while using the system halt mechanism to wait for remaining frame time after drawing (`Sleep()`, `nanosleep()`, `usleep()`). Just for reference, [here it is the related code](https://github.com/raysan5/raylib/blob/master/src/core.c#L3073).

This issue requires some investigation.

**Comment by JamieMair** [comment]
This stuttering problem occurred on my laptop using the Intel HD 630 driver (for integrated graphics). I also have a mobile 1050ti on my system which ran the same code with no stuttering. I have since updated to the latest driver on intel's website and the problem has gone away.

**Comment by raysan5** [comment]
@JamieMair Hey! Thank you very much for the feedback! Righ now all my computers use Intel GPU, I'll try updating drivers.

It would be great getting more feedback on this issue...

**Comment by simpsond** [comment]
It's happening to me, but it isn't painfully obvious.  I had to really pay attention to see it in the shapes_bouncing_ball example.

MacBook Pro (2018)
Mojave 10.14.6
2.9 GHz Intel Core i9
32 GB 2400 MHz DDR4
Radeon Pro 560X 4 GB  (Activity Monitor indicated example was requiring the discrete GPU)
Intel UHD Graphics 630 1536 MB

I'm happy to assist on the macOS side however I can.

**Comment by raysan5** [comment]
@simpsond thanks for the details! Yeah, it's not that painful... still not easy to solve...

Any feedback and testing on macOS platform is welcome! Thanks! :)

**Comment by dbrookman** [comment]
Did some digging on this one, and it's definitely a frame timing / pacing issue. 

System halts just aren’t accurate enough to wake the program up in time to deliver the rendered frame when the screen refreshes. `usleep()` and `nanosleep()` seem to wait the provided time and then some because of system overhead. I'm not completely sure about `Sleep()` as I don't have access to a Windows computer, but I'm guessing it's hitting the same problem.

If the interval for providing a frame is always variable, we have no chance of matching the fixed refresh rate of the display, and we likely end up displaying the same frame twice.

So, we can't count on system halts for a fixed framerate. We can count on the accuracy of busy wait loop, but it has to constantly keep checking, and maxes out the CPU.

Something that would work is not halting - taking `Wait()` out of `EndDrawing()` - and just rendering frames as fast as the computer lets us. This smooths out the motion, as new frames can be drawn and shown variably without duplicates but this does lead to a problem.

Moving from a fixed framerate to a variable framerate, this ends up sort of being a breaking change. Anything that gets moved a fixed ammount per frame (a lot of the examples will have problems like this) will probably appear to move too fast. We can have OpenGL take care of this with `glfwSwapInterval(1)` and make sure things run at exactly the refresh rate, but the motion on a 120hz monitor will be twice as fast as on a 60hz monitor.

This can be fixed by [multiplying these changes](https://en.wikipedia.org/wiki/Delta_timing) by both the original target FPS & `GetFrameTime()`, so that they are relative to seconds, but those are changes that would have to be made.

**For example**:

The constant x / y speed of the ball [here](https://github.com/raysan5/raylib/blob/c387bc586d9c8b9fe9bb840926d12526aaad9116/examples/shapes/shapes_bouncing_ball.c#L24) would have to change from the distance the ball travels per frame
```c
Vector2 ballSpeed = { 5.0f, 4.0f };
```
to the distance the ball travels per second
```c
Vector2 ballSpeed = { 300.0f, 240.0f };
```

and the updating of the ball's position [here](https://github.com/raysan5/raylib/blob/c387bc586d9c8b9fe9bb840926d12526aaad9116/examples/shapes/shapes_bouncing_ball.c#L42)
```c
ballPosition.x += ballSpeed.x;
ballPosition.y += ballSpeed.y;
```
would have to change be multiplied by the time it took for the last frame to be drawn in seconds
```c
ballPosition.x += ballSpeed.x * GetFrameTime();
ballPosition.y += ballSpeed.y * GetFrameTime();
```

**Comment by raysan5** [comment]
@dbrookman thanks for the detailed review. Changes you propose require a complete redesign of multiple parts, no plans to do that for the moment... I think the best option is just leave the busy wait loop as an option for the user...

**Comment by raysan5** [comment]
I've been working on this issue for a while. I tested `shapes_bouncing_ball.c` example under several situations on Windows. Here the results of my tests:

On Vsync enabled (`SetConfigFlags(FLAG_VSYNC_HINT)`) and no-fps-cap (`//SetTargetFPS(60)`), everything works great, no stuttering.

On busy wait loop enabled (raylib compiled with `SUPPORT_BUSY_WAIT_LOOP` enabled). everything works great, no stuttering.

Stuttering only happens when using `Sleep()` (or equivalent platform functions) to halt the CPU for a time span. Returning time is really unpredictable and I'm afraid there is no solution for that.

I took some timming measures on two different situations: Sleep vs Busy Wait Loop and the results were quite interesting: [log_timming_sleep.txt](https://github.com/raysan5/raylib/files/3922847/log_timming_sleep.txt) vs [log_timming_wait_loop.txt](https://github.com/raysan5/raylib/files/3922848/log_timming_wait_loop.txt)

Note the difference between the requested wait time (`Req.Wait`) vs the real time waited (Real.Wait) but also note that when avoiding kernel calls like `Sleep()` the program usually updates and draws faster (approximately x4), that's very interesting and I'm wondering if it can be related to running on a platform with 4 logic processors...

I feel we did anything that was on our hands. I'm closing this issue for now.
