### ISSUE TITLE
[core][rlgl] Redesign Shaders/Textures system, use Materials

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#92]
Right now, `struct Shader` references the `Texture2D` objects; `struct Model` keep references to `Shader` and `Texture2D` objects. 

This data organization could be upated for a more professional (and coherent) layout. A new `struct Material` is proposed to include `Shader` and multiple `Texture2D` objects.

This change requires some internal raylib redesign, mainly of [rlgl] module, but in long term it will be very beneficial for raylib. ;)

**Comment by raysan5** [comment]
Implemented in commit https://github.com/raysan5/raylib/commit/c9d22c7a14a84b24a94f876c9e438c621b4bf420

Still some work required to improve new `struct Material` usage...

**Comment by raysan5** [comment]
Directly related to issue https://github.com/raysan5/raylib/issues/96

**Comment by victorfisac** [comment]
Standard Material/Lighting system update 01: c60cc9e
Standard Material/Lighting system update 02: 80eb4f3

**Comment by victorfisac** [comment]
Answering 9811a37 commit description: "It seems there are some problems with DrawLights()"

I think DrawLights() is correct. It draws:
- **Point light**: sphere wires.
- **Directional light**: it draws a sphere wire in its position and cube wires in target position. To set up a directional light, you just have to set up the direction vector that uses the standard shader by subtract target - position (it's the same position(0, 0, 0) target(0, 1, 0) than position (1, 1, 1,) target (1, 2, 1))... I used that way because I think is more simple and visually easy to understand light parameters (and 3D Max uses that way).
- **Spot light**: it draws a cone in its position (axis oriented) and a cube wires in target position....

So, I didn't see any problem in DrawLights().

But, **I have seen another problem**... Sometimes, **if I move the lights variables definitions to a different order** (using current order of the example works fine), **there is a light that is not sent to shader or something because you cannot see its effect in the model**. I don't know where is the issue: CreateLight() or SetShaderLights()...

I will review it before adding shader maps feature.

**Comment by raysan5** [comment]
Closed by pull request https://github.com/raysan5/raylib/commit/4b93349db575bedb48b8c13e95d37df1ec694387

Many thanks to @victorfisac for his amazing work!

**Comment by victorfisac** [comment]
You are welcome @raysan5 . It will be improved over time.
